"""1-line descriptions for well-known artists in the salon collection.

For artists not listed here, the generator falls back to their subgroup's
blurb — so every chip in the UI gets SOME description.

Format: DESCRIPTIONS[genre_slug][artist_name] = "1-line description"
Aim for 30-80 chars. Avoid trailing period to feel like a chip caption.
"""

DESCRIPTIONS = {

# ─── Ambient (11 — all known) ───────────────────────────────
"ambient": {
    "Empyrium": "ドイツの森が雪の重さで沈む、 Black Metal出自の牧歌",
    "Tenhi": "フィンランドの夕暮れを、 ピアノとアコギだけで実演",
    "Dargaard": "中世墓所をシンセで歩くオーストリアのゴシック儀式",
    "KAUAN": "ロシア発、 雪原の中の祈祷。 言葉を超える音",
    "Nucleus Torn": "スイス発。 合唱・チェロ・声明を1枚に詰める豪奢",
    "NACHTREICH": "Empyrium連作の妹分。 氷の奥の灯り",
    "Fjallstorm": "スウェーデンの白夜。 短いが結晶のような完結性",
    "IN SCISSORS": "国産。 ヨーロッパ儀式音楽を日本語の語彙で書き直した稀少盤",
    "MURGRIND": "国産。 森と王座のフォーク・アンビエント",
    "Bruno Mars": "整理ミス枠。 1枚だけ混入したポップスター",
    "2008 The Cycle of Fifths": "コンピレーション枠",
},

# ─── Healing (well-known artists) ────────────────────────
"healing": {
    "Akira Kosemura": "日本のポストクラシカル。 Bill Evansの呼吸を独奏に折りたたむ",
    "Maksim Mrvica": "クロアチアの派手ピアニスト。 大衆の門を一段で上げた",
    "Aukai": "ロンロン (アンデス胡弓) の余韻。 砂漠のECM",
    "Anoice": "渋谷から立ち上がるドローン × 弦楽。 静けさの中の緊張",
    "Druid": "ケルティック・スピリチュアル。 部屋の温度を2℃下げる",
    "Yanni": "1980-90年代New Age大スター。 シンセ叙事詩",
    "kitaro": "日本のシンセ詩人。 地球の音を編んだ世代",
    "Yiruma": "韓国の人気ソロピアニスト。 「Kiss the Rain」",
    "Kevin Kern": "アメリカのソロピアノ詩人。 静謐の標準形",
    "George Winston": "ソロピアノNew Ageの祖。 December盤で有名",
    "Ryuichi Sakamoto": "坂本龍一。 戦場のメリークリスマス、 YMO",
    "sakamoto ryuichi": "別表記の坂本龍一",
    "Eleni Karaindrou": "ECMの映画音楽詩人。 Theo Angelopoulosの作曲家",
    "Two Steps From Hell": "ハリウッド予告編音楽の支配者",
    "Brian Crain": "静かなアメリカン・ピアノ。 結婚式の定番",
    "DEPAPEPE": "日本のアコースティック・ギターデュオ",
    "David Lanz": "ソロピアノの叙情。 ナラダ・レーベル代表格",
    "Ah Nee Mah": "ネイティブ・アメリカン × ケルト融合の癒し",
    "Karunesh": "ドイツのワールド/瞑想ニューエイジ",
    "Deuter": "ドイツのスピリチュアル・ニューエイジ巨匠",
    "Govi": "ニューエイジ・ギターの世界派",
    "Sojiro": "宗次郎。 オカリナで自然と神話を奏でる",
    "Bandari": "Pacific Moon系のリラクゼーション・ピアノ",
    "Daishi Dance": "日本のピアノ × ハウスのプロデューサー",
    "Hayato Sumino": "角野隼人。 古典×YouTubeの世代",
    "Nujabes": "瀬葉淳。 Lo-fi Hip-Hopのレジェンド",
    "S.E.N.S": "深見和宇とこさかゆうとの伝説的シンセDuo",
    "Balmorhea": "テキサスのポストクラシカル。 ピアノと砂塵",
    "Library Tapes": "Sonic Pieces系のスウェーデン・ピアノ",
    "Poppy Ackroyd": "英国のヴァイオリン×ピアノのポストクラシカル",
    "Sofiane Pamart": "フランスのソロピアノ。 ラッパー客演で有名",
    "Hayato Sumino": "角野隼人。 ピアノYouTuberから武道館へ",
    "Jim Brickman": "アメリカの定番ソロピアニスト",
    "Peter Kater": "グラミー受賞の癒し系ピアノ",
    "Philip Wesley": "メロディック・ソロピアノ",
    "Phillip Keveren": "クラシック・カバー編曲の名手",
    "Robin Spielberg": "オーディエンス参加型ソロピアノ",
    "Michele McLaughlin": "アメリカの新世代ソロピアノ",
    "Vladimir Sterzer": "ロマンティック・ピアノ",
    "Yuki Kuramoto": "倉本裕基。 日本人ソロピアノ詩人",
    "Yuki Saiki": "斎木ゆき。 リラクゼーション・ピアノ",
    "Yukie Nishimura": "西村由紀江。 日本のピアノ詩人",
    "Yuriko Nakamura": "中村由利子。 日本ピアノ詩人の世代",
    "Louis Landon": "アメリカの叙情ソロピアノ",
    "Marc Enfroy": "心地よいピアノ・ニューエイジ",
    "Matthew Mayer": "アメリカのソロピアノ",
    "Max Highstein": "瞑想・癒し系ピアノ",
    "Peter Bence": "ハンガリーのピアノ・ヴィルトゥオーゾ。 YouTubeでバズった",
    "Scott D. Davis": "メタル曲をピアノで弾く人",
    "Stuart Hoffman": "現代ピアノ・ニューエイジ",
    "Steven Daane": "現代ソロピアノ",
    "Ryan Stewart": "アメリカのソロピアノ",
    "Richard Clayderman": "「渚のアデリーヌ」 のフレンチ・ポップピアノの王者",
    "Giovanni Marradi": "イタリア系のロマンティック・ピアノ",
    "Danny Wright": "アメリカのソロピアノ",
    "James Michael Stevens": "アメリカの叙情ピアノ",
    "Robert Haig Coxon": "瞑想・癒し系シンセ",
    "Steven Halpern": "アメリカン・ニューエイジ草分け",
    "Eric Tingstad": "ニューエイジ・ギター巨匠",
    "Tim janis": "アメリカン・パストラル",
    "Tron Syversen": "ノルウェーのアンビエント",
    "Jo Blankenburg": "現代映画音楽作曲家",
    "Mars Lasar": "オーストラリアのシンセ・アンビエント",
    "Bjørn Lynne": "ノルウェーのゲーム/シネマ作曲家",
    "Logos": "リチャード・バーマー。 シンセ・アンビエント",
    "Zero-Project": "ギリシャのインスト・ロック/ニューエイジ",
    "Pacific Moon Records": "日本系ヒーリング・レーベル",
    "Loreena McKennitt": "重複枠。 カナダのケルト女王",
    "Image": "ニューエイジ・コンピレーション",
    "Kuara": "アンビエント枠",
    "kitaro": "日本のシンセ詩人",
    "Niall": "ケルト・スピリチュアル",
    "Nicholas Gunn": "アメリカのフルート・ニューエイジ",
    "Phil Coulter": "アイルランドのピアノ・トラディショナル",
    "R. Carlos Nakai": "ネイティブ・アメリカン・フルート巨匠",
    "Robert Tree Cody": "ネイティブ・アメリカン・フルート",
    "Ron Korb": "ワールド・フルートのカナダ人",
    "Pablo Arellano": "アメリカのソロピアノ",
    "Llewellyn": "ウェールズ系癒し作曲家",
    "OSHO": "瞑想 (Osho関連音源)",
    "Bodhi": "癒し系ニューエイジ",
    "Cathal MacDara": "アイルランド系ヒーリング",
    "Domo records": "Domoレコードのコンピ",
    "Douglas Blue Feather": "ネイティブ系フルート",
    "Gandalf": "オーストリアのケルト/ニューエイジ",
    "Wonders Of Nature": "自然系コンピ",
    "CUSCO": "ドイツのアンデス系ニューエイジ",
    "Mustafa Avşaroğlu": "トルコの作曲家",
    "Wang Sanpu": "中国系ヒーリング",
    "Edward Simoni": "パンフルート奏者",
    "Henry Arland": "クラリネット系イージーリスニング",
    "Eric Hilton": "Thievery Corporation のメンバー",
    "Eric Chiryoku": "国産ヒーリング",
    "Aaron Amida Ang": "東洋的ヒーリング・ギター",
    "Acker Bilk": "英国のクラリネット・ジャズ系イージー",
    "Acoustic Cafe": "ヴィタリ・コラチェスキーのコンピ",
    "Akiko Usui": "国産ヒーリング作曲家",
    "Air Element": "アンビエント枠",
    "ALIAKE": "国産アンビエント",
    "Ann Licater": "ネイティブ・フルート",
    "Ann Sweeten": "ニューエイジ・ピアノ",
    "Andrea Rongioletti": "イタリアのピアノ・ヒーリング",
    "Angel Tears": "セレナ天使系ヒーリング",
    "Aurio Corra": "ヒーリング作家",
    "Autumn's Grey Solace": "ゴシック・ドリームポップ",
    "Back to Earth": "癒し系ヒーリング",
    "Beautiful Fantasy II": "コンピ盤",
    "Bernadette Bevans": "ハープ系ヒーリング",
    "Bill Douglas": "アメリカのピアノ作曲家",
    "Carlyle Fraser": "ハープ系ヒーリング",
    "Cecilie": "北欧系ピアノ",
    "Celtic Fairy Lullaby": "ケルト子守唄",
    "CHILDHOOD": "コンピ枠",
    "cicada": "国産アンビエント",
    "feel": "コンピ枠",
    "Fly North": "ヒーリング・ピアノ",
    "Hennie Bekker": "南アフリカ生まれの自然+シンセ作曲家",
    "Jonathan Harrington": "ピアノ・ヒーリング",
    "Kebin Keller": "ピアノ作曲家",
    "Medwyn Goodall": "英国の癒し作曲家",
    "Minstrel Streams": "アコースティック・ヒーリング",
    "Music 2 Hues": "ヒーリング・コンピ",
    "Sleep & Meditation Manifestation": "睡眠・瞑想機能音楽",
    "Stuart Jones": "癒し系作曲家",
    "Terry Oldfield": "Mike Oldfieldの兄。 New Ageフルート",
    "Thors": "癒し系作曲家",
    "Pacific Moon Records": "Pacific Moonレーベル",
    "Lisa Lynne & George Tortorelli": "ケルト・ハープ・デュオ",
    "Sheila's Disciples": "ヒーリング枠",
    "Threefold": "癒し系作曲家",
    "Roger Subirana": "スペイン系シンセ",
    "Remi Orts Project": "癒しコンピ",
    "Vadim Kiselev": "ピアノ・ヒーリング",
    "Pascal Coppe": "癒し系作曲家",
    "Hands two Hands": "ヒーリング・コンピ",
},

# ─── Progressive ───────────────────────────────────────────
"progressive": {
    "Genesis": "1973年の英国田園詩。 Hackettのギターは50年経っても新しい",
    "Marillion": "Genesis後継、80年代後半以降の叙情ネオプログ",
    "Big Big Train": "21世紀英国シンフォプログの代表。 田園詩×12分組曲",
    "Mike Oldfield": "Tubular Bells。 多重録音の天才",
    "Yes": "Jon Anderson在籍時のシンフォニックプログ巨人",
    "Jon Anderson": "Yesの声。 ソロでも宇宙的",
    "Pink Floyd": "重複枠的にシンフォプログ巨匠",
    "Cast": "メキシコのシンフォニック・プログ。 Yes/Genesisの遺伝子",
    "Pendragon": "英国ネオプログ。 Marillion同世代",
    "Galahad": "英国ネオプログ。 90年代以降",
    "ART BEARS": "Henry Cow直系のRIO。 政治と歌の融合",
    "After Crying": "ハンガリー古典×プログのRIO代表",
    "Aranis": "ベルギーのチェンバーRIO",
    "Magma": "クリスチャン・ヴァンデのフランス・ジャズロック巨人",
    "Kansas": "アメリカン・プログ。 「Dust In The Wind」",
    "A.C.T": "スウェーデンの合唱と数学のプログ",
    "Barock Project": "イタリアのネオプログ",
    "Celeste": "イタリア72年の伝説的シンフォ",
    "Jordan Rudess": "Dream Theaterのキーボディスト",
    "Rick Wakeman": "Yesの伝説的キーボーディスト",
    "Premiata Forneria Marconi": "PFM。 イタリアン・プログの巨匠",
    "Il Balletto Di Bronzo": "イタリア72年シンフォ名盤",
    "New Trolls": "イタリアの古典シンフォ",
    "Latte E Miele": "イタリアのキリスト教コンセプト・プログ",
    "Quella Vecchia Locanda": "イタリア72年シンフォ",
    "Maxophone": "イタリア75年シンフォ",
    "LOCANDA DELLE FATE": "イタリアン・プログの隠れ名盤",
    "Tortilla Flat": "ドイツの隠れ名盤",
    "Anglagard": "スウェーデン90s復興プログ",
    "Anekdoten": "スウェーデンのKing Crimson系プログ",
    "Moon Safari": "スウェーデンのコーラスシンフォ",
    "Isildurs Bane": "スウェーデンの実験プログ",
    "iamthemorning": "ロシアのチェンバー・ポストプログ",
    "The Pineapple Thief": "英国モダン・ポストプログ",
    "Subsignal": "ドイツのモダン・プログ",
    "Tiger Moth Tales": "英国のソロ・プログ",
    "Willowglass": "英国のシンフォニック・プログ",
    "ESP Project": "英国のソロ・シンフォプログ",
    "Mystery": "カナダのネオプログ",
    "Pallas": "スコットランドのネオプログ",
    "IO Earth": "英国のシンフォプログ",
    "IOEarth": "別表記のIO Earth",
    "Mandalaband": "英国のシンフォニック・コンセプト",
    "Pattern-Seeking Animals": "Spock's Beard派生のアメリカン・プログ",
    "Thank You Scientist": "アメリカのジャズ・プログ",
    "Joey Frevola": "ソロ・ギタープログ",
    "Hardscore": "プログ・コンセプト",
    "Inner Drive": "アメリカン・プログ",
    "Vienna": "プログ枠",
    "Sanhedrin": "ヘヴィプログ",
    "Lost World": "ロシアのジャズロック",
    "Malady": "フィンランドのモダンプログ",
    "Kaizen": "プログ枠",
    "UZVA": "フィンランドのチェンバープログ",
    "Tirill": "ノルウェーの女性ヴォーカル・フォークプログ",
    "Lindh Par and Bjorn Johansson": "スウェーデンのプログ",
    "Kimmo Porsti": "フィンランドのドラマー・プログ",
    "Yuka & Chronoship": "日本のシンフォニック・プログ",
    "STELLA LEE JONES": "日本のドリーミー・プログ",
    "Mr. sirius": "日本のシンフォプログ",
    "Karfagen": "ウクライナのシンフォプログ",
    "Pesniary": "ベラルーシの古典プログ",
    "Wojciech Ciuraj": "ポーランドのプログ",
    "Quaterna Requiem": "ブラジルのチェンバープログ",
    "Diego Schissi": "アルゼンチンのモダン・タンゴ",
    "Sedmina": "スロベニアのフォークプログ",
    "Zypressen": "クロアチアのシンフォ",
    "SAGRADO": "ブラジルのジャズロック",
    "Stamatis Spanoudakis": "ギリシャのシンフォニック作曲家",
    "Taxidi": "ギリシャのプログ",
    "Savina Yannatou": "ギリシャの女性ボーカル世界音楽",
    "Cordame": "カナダのチェンバー・ジャズロック",
    "Maraca": "プログ枠",
    "Outer Limits": "日本の古典プログ",
    "Tai Phong": "ベトナム/フランスのジャズロック",
    "NU": "プログ枠",
    "MUSIC 4 A WHILE": "プログ・コンピ",
    "Tin Hat Trio": "アメリカのチェンバー・アヴァン",
    "Musica Urbana": "スペインのジャズロック",
    "Fruupp": "アイルランドの70sシンフォ",
    "Mauro Pagani": "イタリアの世界音楽プログ",
    "Popol Vuh": "ドイツのアンビエント・クラウト",
    "Parzzival": "ドイツのフォークプログ",
    "Vivo": "プログ枠",
    "Wapassou": "フランスのチェンバー・プログ",
    "iamthemorning": "ロシアのポストプログ",
    "Nova Cascade": "プログ枠",
    "Syrinx Call": "ドイツのプログ",
    "Pikapika TeArt": "プログ枠",
    "PTF": "プログ枠",
    "Organic Noises": "プログ枠",
    "Rodrigo Leão & Cinema Ensemble": "Madredeus元メンバーのシネマ・プログ",
    "Emmett Elvin": "英国のソロ・プログ",
    "Er.J.Orchestra": "プログ枠",
    "Fall of Episteme": "プログ枠",
    "Finnegans Wake 4th": "プログ枠",
    "Flairck": "オランダのアコースティック・プログ",
    "Guranfoe": "プログ枠",
    "Harmonium": "ケベックのシンフォプログ",
    "Homunculus Res": "イタリアのカンタベリー風プログ",
    "Ibis": "イタリアの古典プログ",
    "Island": "スイスのアコースティック・プログ",
    "La Coscienza di Zeno": "イタリアのモダン・シンフォプログ",
    "La Maquina Cinematica": "プログ枠",
    "Lifesigns_-_2017_-_Cardington__FLAC": "Marillion参加メンバーのプログ",
    "Russkaja": "オーストリアのロシア風プログ",
    "Ser un Peyjalero": "プログ枠",
    "Silhouette": "オランダのネオプログ",
    "The Samurai Of Prog": "国際プログコレクティブ",
    "Stéphane Collin": "プログ枠",
    "Susanne Lundeng": "ノルウェーのフィドル奏者",
    "Syndone": "イタリアのモダン・プログ",
    "All Traps on Earth": "Anglagardの後継プログ",
    "Acintya": "プログ枠",
    "Air Craft": "プログ枠",
    "Ainur": "プログ枠",
    "Anacrusa": "アルゼンチンのプログ",
    "Andre Mehmari": "ブラジルのジャズピアノ",
    "Ann Gaytan": "プログ枠",
    "Apairys": "プログ枠",
    "Asturias": "日本のシンフォプログ",
    "Autumn Chorus": "プログ枠",
    "B. J. Lindh": "スウェーデンのジャズプログ",
    "Black Tape For A Blue Girl": "アメリカン・ダーク・ロマンティック",
    "Blazing Bronze": "プログ枠",
    "Bruno Sanfilippo": "アルゼンチンのアンビエント・ピアノ",
    "Charlie Cawood": "英国のオリエンタル・プログ",
    "Chris": "プログ枠",
    "Ciccada": "ギリシャのフォークプログ",
    "Clarinet Factory": "チェコのチェンバー",
    "Concerto Moon": "日本のメロディアス・パワーメタル/プログ",
    "Phaedra": "プログ枠",
    "Katzen Kapell": "スウェーデンのジャズプログ",
    "Stéphane Collin": "プログ枠",
    "seffer": "プログ枠",
    "Yugen": "イタリアのアヴァン・プログ",
    "UNIVERSAL TOTEM ORCHESTRA": "アヴァンプログ",
    "Kalacakra": "ドイツのクラウト",
    "Opus Arise": "プログ枠",
    "Opus Avantra": "イタリアのアヴァン・チェンバー",
    "Premiata Forneria Marconi": "PFM",
    "Marco Antonio Araújo1984 Lucas [Brazil PRW 016].ape": "ブラジルのプログ",
    "After Crying": "ハンガリーのRIO",
    "Karfagen": "ウクライナのシンフォプログ",
    "Eris Pluvia": "イタリアの90sプログ",
    "Gatto Marte": "イタリアのプログ",
    "Hostsonaten": "イタリアのプログ",
    "Arti E Mestieri": "イタリアのジャズプログ",
    "Premiata Forneria Marconi": "PFM",
},

# ─── Jazz & Fusion ────────────────────────────────────────
"jazz": {
    "Bill Evans Trio": "ジャズピアノトリオの極北。 1961年Village Vanguard",
    "Bill Evans, Jim Hall": "Undercurrent。 沈黙と沈黙の間にだけ音楽がある",
    "Bill Evans": "ジャズピアノトリオの究極形",
    "Charlie Haden & Pat Metheny": "Beyond The Missouri Sky。 西部のフォークジャズ",
    "Charles Mingus": "ベース×作曲のジャズ巨人",
    "Gerry Mulligan": "Cool Jazzのバリトンサックス",
    "Eric Dolphy": "Out To Lunch。 1964年の前衛ジャズ",
    "Esjbjorn Svensson Trio": "e.s.t. スウェーデンの21世紀ECMトリオ",
    "Helge Lien Trio & Tore Brunborg": "ノルウェーの葬礼すら踊らせる静謐",
    "Avishai Cohen": "イスラエル・ジャズ。 弦と低音の対話",
    "Eddie Higgins": "アメリカの叙情ピアノ・トリオ",
    "Enrico Pieranunzi": "イタリアのスタンダード解釈の教科書",
    "Bill Laurance": "Snarky Puppyの英国キーボード",
    "Bill Laurance & Michael League": "Snarky Pupperの2人デュオ",
    "Brian Culbertson": "アメリカン・スムーズ・ジャズ",
    "Billy Childs": "アメリカのモダン・ジャズピアノ",
    "Great Jazz Trio": "ハンク・ジョーンズらの黄金トリオ",
    "Charlie Haden": "ベースの抒情詩人",
    "Pat Metheny": "ジャズギターの21世紀標準",
    "Keith Jarrett": "Köln Concert。 即興の至高",
    "The Koln Concert": "Keith Jarrett 1975の伝説",
    "Hiromi Uehara": "上原ひろみ。 日本のヴィルトゥオーゾ・ジャズピアノ",
    "Kamasi Washington": "現代スピリチュアル・ジャズの旗手",
    "Jaco Pastorius": "エレクトリック・ベースの神",
    "Incognito": "英国アシッド・ジャズ",
    "Indigo Jam Unit": "日本のインディー・ジャズ・トリオ",
    "jizue": "日本のポストロック・ジャズ",
    "Marbin": "シカゴのジャズ・フュージョン",
    "Steve Kuhn": "アメリカのインプロビゼーション・ピアニスト",
    "Walter Bishop Jr": "1950s-70sジャズピアノ",
    "The Bad Plus": "アメリカのトリオ。 ロックのジャズ化",
    "The Bill Holman Band": "アメリカン・ビッグバンド古典",
    "Tingvall Trio-Pax": "スウェーデンのモダン・ピアノトリオ",
    "RUSCONI": "スイスのトリオ",
    "Tiger Okoshi": "日本のトランペッター",
    "Uptown Jazz Underground": "現代ジャズコレクティブ",
    "Emil Brandqvist Trio": "スウェーデンのリリカル・トリオ",
    "Giovanni Mirabassi Trio & Strings": "イタリアの叙情ピアノ",
    "Michel Camilo & Tomatito": "ピアノ×フラメンコギターの巨人",
    "Milton Nascimiento": "ブラジル音楽の巨匠",
    "Pavol Bodnár & InterJAZZional Band": "スロバキアのジャズ",
    "Playwright": "日本のフォークジャズ",
    "Richard Tee": "アメリカのジャズ/R&Bピアニスト",
    "Andrea Abbadia": "イタリアのジャズピアノ",
    "Autumn Tears": "実はゴシック・ネオクラ (誤分類枠)",
    "Charles Mingus": "ジャズ作曲家の巨人",
    "Diederik Wissels": "ベルギーのジャズ",
    "Debussy, Arturo Benedetti Michelangeli": "クラシック誤分類枠",
    "DLRAW.TO_Oto_no_hazure_no_renkinjutsushi vol 01-06": "ジブリ吹奏楽コンピ",
    "EGEA": "イタリアのジャズ・レーベル",
    "Giovanni Guidi, Gianluca Petrella, Louis Sclavis, Gerald Cleaver": "ECMジャズ・カルテット",
    "Mingui Ingaramo": "ジャズ枠",
    "Juan Garcia": "ジャズ枠",
    "Nakagawa Poesy 1996": "日本のジャズ",
    "MA_Recordings": "MA Recordingsレーベル",
    "Masterpieces By Ellington": "Duke Ellington名作集",
    "SUPER SOUND COLLECTION スタジオジブリ吹奏楽": "ジブリ吹奏楽",
    "Nocni Optika": "ジャズ枠",
    "XRCD 国府弘子NEWYORK UNCOVER": "国府弘子NY録音",
    "acro jazz": "アコースティック・ジャズ",
    "Hiromi": "Hiromi Uehara",
    "Joshua Redman": "現代アメリカン・ジャズ・サックス",
    "Sonny Rollins": "ジャズ・サックスの巨人",
    "Diana Krall": "カナダのヴォーカル・ジャズ",
    "David Benoit & Russ Freeman": "アメリカン・スムーズ・ジャズ",
    "Gabriele Mirabassi e Richard Galliano": "クラリネット×アコーディオン・デュオ",
    "Musique à Neuf": "ジャズ枠",
    "Musicazur": "ジャズ枠",
},

# ─── Classic ──────────────────────────────────────────────
"classic": {
    "The Art of Arturo Benedetti Michelangeli": "完璧主義の極致。 「音は置かれている」",
    "Gilils": "Emil Gilels。 ロシア黄金期、 金属の重さで弾く",
    "Rachmaninoff Piano Concerto 2-Rubinstein 1950 & 1956": "ルービンシュタインのラフマニノフ名盤",
    "Leopold Wlach": "オーストリアのクラリネット名手",
    "Hayato Sumino": "角野隼人。 古典×YouTubeの世代",
    "Nobuyuki Tsujii": "辻井伸行。 触覚で世界を読むピアニスト",
    "まらしぃ": "ニコニコ動画から武道館へ。 大衆と古典の橋",
    "Healing Piano": "リラクゼーション・ピアノ・コンピ",
    "Piano Master": "ピアノ・マスター・コンピ",
    "share": "コンピ枠",
    "accelerate": "コンピ/ファイル枠",
    "クラシックBest9": "クラシック・コンピ",
    "クラシック音楽による 目覚めがすっきりするCD": "目覚めコンピ",
    "フジ子・ヘミング　チャイコフスキー：ピアノ協奏曲第一番 他": "遅咲きの伝説、 トロイカの一筆書き",
    "スプリングコンサート": "コンピ枠",
    "Great.Pianists.of.the.20th.Century": "20世紀名ピアニスト集",
    "『Great.Pianists.of.the.20th.Century』.Vol.58.-.Evgeny.Kissin": "Kissinの20世紀名ピアニスト盤",
    "フジ子・ヘミング チャイコフスキー：ピアノ協奏曲第一番 他 (UCCD-1086『トロイカ』)": "フジ子・ヘミングのトロイカ",
},

# ─── Metal & Hard Rock ──────────────────────────────────
"metal": {
    "Blind Guardian": "トールキンを丸ごと音楽化。 30年揺るがない芯",
    "Adagio": "フランスのネオクラ・メタル。 Adagio for Strings の血統",
    "Beast in Black": "フィンランドの誇張過剰なメタル80s愛",
    "Amorphis": "Kalevalaを音楽にした北欧叙事詩メタル",
    "Ancient Bards": "イタリアのソプラノ叙事詩メタル",
    "Behemoth": "ポーランドのブラックメタル至高峰",
    "Dark Tranquillity": "メロデス第一世代",
    "Children of Bodom": "Alexi Laihoの北欧メロデス",
    "Arch Enemy": "Angela Gossowらの女性ヴォーカル・メロデス",
    "Amberian Dawn": "フィンランドのソプラノ・パワーメタル",
    "Powerwolf": "ドイツのカトリック様式パワーメタル",
    "Sabaton": "スウェーデンの戦争パワーメタル",
    "Helloween": "ジャーマン・パワーメタルの祖",
    "Edguy": "Tobias Sammet率いるパワーメタル",
    "Avantasia": "Edguyのコンセプト・サイドプロジェクト",
    "Kamelot": "アメリカのシンフォニック・パワーメタル",
    "Kamelot (Progressive Melodic Power Metal • United States)": "Kamelot重複",
    "Gamma Ray": "Helloween Kai Hansenのパワーメタル",
    "Nightwish": "フィンランドのシンフォニックメタル王",
    "Within Temptation": "オランダのシンフォニックメタル",
    "Lacuna Coil": "イタリアのゴシックメタル",
    "After Forever": "Floor Jansen初期のシンフォメタル",
    "Therion": "スウェーデンのオペラティック・メタル",
    "Epica": "オランダのシンフォニック・メタル",
    "Dream Theater": "プログメタルの王",
    "Liquid Tension Experement": "Dream Theater派生のプログ",
    "Opeth": "スウェーデンのプログ・デス→プログロック",
    "Leprous": "ノルウェーのモダン・プログメタル",
    "Persefone": "アンドラのプログメタル",
    "Seventh Wonder": "スウェーデンのプログメタル",
    "SYMPHONY X": "アメリカのプログ・パワーメタル",
    "Queensryche": "アメリカのプログメタル古典",
    "Megadeth": "Dave Mustaineのスラッシュメタル巨人",
    "Slayer": "スラッシュメタルの神",
    "Judas Priest": "Heavy Metalの定義者",
    "Iron Maiden": "ブリティッシュ・ヘヴィメタル巨人",
    "Guns N' Roses": "アメリカン・ハードロック巨人",
    "Gary Moore Gold": "Gary Moore。 ブルース・ロック・ギター",
    "Ihsahn": "Emperorのソロ。 ブラックメタル知性派",
    "Emperor": "ノルウェーのシンフォニック・ブラック",
    "Equilibrium": "ドイツのフォーク・メタル",
    "Eluveitie": "スイスのケルティック・フォークメタル",
    "Ensiferum": "フィンランドのヴァイキング・メタル",
    "Moonsorrow": "フィンランドのペイガン・メタル",
    "Insomnium": "フィンランドのメロディック・デス",
    "In Flames": "Gothenburgメロデスの代表",
    "At The Gates": "メロデス第一世代",
    "Kalmah": "フィンランドのメロデス",
    "Sigh": "日本の前衛ブラックメタル",
    "Sentenced": "フィンランドのゴシック・メロデス",
    "Lacrimosa": "ドイツ・スイスのゴシックメタル",
    "DragonForce": "英国のスピード・パワーメタル",
    "Sonata Arctica": "フィンランドのメロディック・パワー",
    "Stratovarius": "フィンランドのパワーメタル古典",
    "Rhapsody Of Fire": "Luca Turilliのファンタジー・メタル",
    "Twilight Force": "スウェーデンのファンタジー・メタル",
    "Gloryhammer": "Christopher Bowes率いる馬鹿馬鹿しさのパワーメタル",
    "X JAPAN": "日本のヴィジュアル系・メタル",
    "Loudness": "日本のヘヴィメタル先駆者",
    "Galneryus": "Syuの日本産プログ・パワーメタル",
    "聖飢魔II": "デーモン閣下の日本元祖ヘヴィメタル",
    "浜田麻里": "日本の女性メタル・ヴォーカル",
    "Onmyo-Za": "陰陽座。 和風ヘヴィメタル",
    "LOVEBITES": "日本の女性パワーメタル",
    "Mai Yajima": "矢島舞依。 日本の女性メタルボーカル",
    "Damian Hamada's Creatures": "聖飢魔II 派生の和風ファンタジーメタル",
    "Cacophony": "Marty Friedman & Jason Beckerの伝説",
    "Chthonic": "閃靈。 台湾のシンフォニック・ブラック",
    "MALICE MIZER": "Manaの日本ゴシック・ヴィジュアル系",
    "Dir En Grey": "日本のオルタナティブ・ヴィジュアル系",
    "MUCC": "ムック。 日本のオルタナ・ヴィジュアル系",
    "Steve Vai": "ロックギターのヴィルトゥオーゾ",
    "Uli Jon Roth": "Scorpions元ギタリスト",
    "Symphonity": "チェコのシンフォメタル",
    "Sixx.A.M": "Mötley Crüeの Nikki Sixx",
    "Vow Wow": "日本のハードロック古典",
    "Anthem": "日本のヘヴィメタル古典",
    "Sex Machineguns": "日本のジョーク・ヘヴィメタル",
    "Crowne": "Henrik Janssonら欧州パワーメタル",
    "Volcano": "プログメタル枠",
    "Ten": "英国のメロディアス・ハードロック",
    "Wuthering Heights": "デンマークのフォーク・パワー",
    "Whispered": "フィンランドのサムライ・メロデス",
    "WarKings": "シンフォニックパワー",
    "Victorius": "ドイツのファンタジー・パワー",
    "Vision Divine": "イタリアのプログ・パワー",
    "Pathfinder": "ポーランドのシンフォ・パワー",
    "Primal Fear": "ドイツのパワーメタル",
    "Nocturnal Rites (Power Metal • Sweden)": "スウェーデンのパワーメタル",
    "Theocracy": "アメリカのキリスト教プログメタル",
    "Last Autumn's Dream": "メロディアス・ハードロック",
    "Light Bringer": "日本のメロディック・パワー",
    "Lione": "メロディック・メタル",
    "Heavenly": "フランスのパワーメタル",
    "Hyperion": "シンフォニック・パワー",
    "Edu Falaschi": "Angra元ヴォーカル",
    "Frozen Crown": "イタリアの女性パワーメタル",
    "Fair Warning": "ドイツのメロディアスHR",
    "Majestica": "Tommy Johanssonのファンタジー・パワー",
    "Luca Turilli (Symphonic Power Metal • Italy)": "Rhapsody元ギタリスト",
    "Dalriada": "ハンガリーのフォークメタル",
    "Dark Moor": "スペインのシンフォニック・パワー",
    "Dark Lunacy": "イタリアのメロデス",
    "Dark the Suns": "フィンランドのゴシック・デス",
    "Damian Hamada's Creatures": "和風ファンタジー・メタル",
    "Beat Weil": "ドイツ語圏のメタル",
    "Blaze": "Iron Maidenの Blaze Bayley",
    "Blood Incantation": "アメリカのプログレッシブ・デス",
    "Bloody Cumshot": "メタル枠",
    "Breaking Benjamin": "アメリカのオルタナ・メタル",
    "Astralion": "フィンランドのパワーメタル",
    "Alesana": "アメリカン・ポストハードコア",
    "Angra": "ブラジルのプログ・パワー",
    "Azrael": "メタル枠",
    "Alchemy Crystal": "シンフォメタル",
    "DGM": "イタリアのプログ・パワー",
    "Derdian": "イタリアのパワーメタル",
    "Embraced": "メタル枠",
    "Eternity's End": "ジャーマン・パワーメタル",
    "Evergrey": "スウェーデンのプログ・ダーク",
    "Fugatta": "メタル枠",
    "Gire": "メタル枠",
    "Graveworm": "イタリアのゴシック・ブラック",
    "GYZE": "日本のメロディック・パワー",
    "Hagane": "日本のヘヴィメタル",
    "Haggard": "ドイツのオーケストラル・メタル",
    "Japanese Folk Metal (2018.11.07) Japanese Folk Metal": "日本フォークメタル・コンピ",
    "Kelly Simonz's Blind Faith": "ケリー・サイモン",
    "Lareine": "日本のヴィジュアル系",
    "Malevolence": "英国のメタル/ハードコア",
    "Matenrou Opera": "摩天楼オペラ。 日本のV系シンフォ",
    "Meadows End": "スウェーデンのメロデス",
    "MinstreliX": "日本のメロディック・パワー",
    "MY MATERIAL SEASON": "日本のメロディック・パワー",
    "Myrath": "チュニジアのオリエンタル・プログメタル",
    "NoGoD": "日本のヴィジュアル系",
    "Obscura": "ドイツのテクニカル・デス",
    "Profugus Mortis": "メタル枠",
    "Rising.Shadows": "メタル枠",
    "Ryujin": "日本のサムライ・メタル",
    "Sad Legend": "韓国のブラックメタル",
    "Serenity 2016": "オーストリアのシンフォニック・パワー",
    "Serenity In Murder": "日本のメロデス",
    "Serenity In Murder 2017": "日本のメロデス",
    "She-Ja": "日本のヘヴィメタル",
    "Shiver of Frontier": "日本のメロディック・パワー",
    "SKYWINGS": "日本のメロディック・パワー",
    "Sunburst 2016": "ギリシャのプログ・パワー",
    "Sunset Wings": "メタル枠",
    "Swallow the Sun": "フィンランドのゴシック・ドゥーム",
    "Thomas Bergersen": "Two Steps From Hell共同創設者",
    "Thousand Eyes": "日本のメロデス",
    "Tina Guo": "中国・米国のチェロ・メタル",
    "Titanium 2016": "メタル枠",
    "Xandria 2017": "ドイツのシンフォメタル",
    "Zemeth": "日本のメロディック・パワー",
    "Zeno": "日本のメロディック・メタル",
    "Delirion": "メタル枠",
    "新しいフォルダー": "整理ミス枠",
    "Serpent": "メタル枠",
    "Waltari": "フィンランドのアヴァンメタル",
},

# ─── Indies ────────────────────────────────────────────
"indies": {
    "Imperial Circus Dead Decadence": "同人音楽の究極形。 デスメタル×アニソン10分曲",
    "Asriel": "Ragnarok 19CD-BOXの集大成。 同人物語OPの壁",
    "Dragon Guardian": "RPG音楽×メタル×物語。 Blind Guardianの日本版本物",
    "Garnet Cathedral": "ゴシック×ヴァイオリン×女性ボーカル。 西洋寄り同人",
    "CROSS VEIN": "ヘヴィメタル×ソプラノ。 商業ライン寸前の同人",
    "Aura Noctis": "イタリアのゴシック・ファンタジー (重複)",
    "Octaviagrace": "シューゲ×ファンタジーのアトモスフェリック",
    "AYUTRICA": "ノベルゲーOST周辺の叙情派",
    "Hagall×152Hz": "電子×女性ボーカルの同人",
    "AL Fantasia": "RPG風同人音楽",
    "Barbarian On The Groove 3.0": "東方Project系統の重ねサークル",
    "CORONA －Orgel Collection－": "オルゴール・カバー集",
    "Aleile": "シューゲ寄り女性ボーカル同人",
    "Frost Fragment": "アトモスフェリック同人",
    "B.rose&crown": "ゴシック・サークル",
    "-LostFairy": "シューゲ・サークル",
    "Dark PHOENiX": "シンフォメタル同人",
    "Unlucky Morpheus": "東方アレンジから独立したシンフォメタル",
    "TEARS OF TRAGEDY": "日本の女性ヴォーカル・シンフォメタル",
    "love solfege": "東方アレンジのコーラスサークル",
    "TAMUSIC": "東方ヴァイオリン・アレンジサークル",
    "Liz Triangle": "東方アレンジサークル",
    "k-waves LAB": "東方アレンジ",
    "Diverse System 4.0": "電子音楽コンピ",
    "Rokugen Alice 3.0": "東方アレンジ",
    "黒夜葬「創作音源集 -骸-」": "ダーク同人",
    "狂奏楽団": "シンフォニック同人",
    "Imperial Circus Dead Decadence": "重複",
    "Klaus -Nostalgias": "実験系同人",
    "Tears Nocturn": "ゴシック同人",
    "Theodor Bastard": "ロシアの民族エレクトロニカ",
    "Zephyr Violin Duo": "ヴァイオリン・デュオ",
    "Lost my Proust": "シューゲ系同人",
    "LostFairy": "別表記",
    "Rejection": "実験同人",
    "Release Hallucination": "実験同人",
    "Resonecia": "シューゲ同人",
    "Roman so Words": "東方アレンジ系",
    "Sana": "同人",
    "soLi (2021.12.08) My Garden …": "シューゲ同人",
    "Symholic": "実験同人",
    "夢想茶館": "和風同人",
    "星猫音楽": "同人",
    "TAMUSIC": "東方ヴァイオリン",
    "AriableyeS": "東方アレンジ",
    "Iyunaline Feat. 中原涼": "ノベルゲー周辺",
    "Krik／Krak": "ノベルゲーOST",
    "Laqshe": "ノベルゲー",
    "Link to You？ (SHIKI) 1.0": "ノベルゲー",
    "MALIKLIYA": "ノベルゲーOST",
    "Queen of Wand": "ノベルゲー",
    "RoyReine": "実験同人",
    "SiMPLE EQUATiON": "ノベルゲー",
    "Souwer": "ノベルゲー",
    "stellatram": "ノベルゲー",
    "SUNRISE FACTORY": "ノベルゲー",
    "Tinkerbell sound label": "ノベルゲー音源",
    "Tinkerbell Sound Label (CrossingYourself)": "別表記",
    "Tynwald music": "ノベルゲー音源",
    "Voltage of Imagination 2.1": "ボカロ系",
    "Yuria Miyazono": "ノベルゲー周辺",
    "Studio A'": "ノベルゲー",
    "yucat": "ノベルゲー周辺",
    "Arthur": "オルゴール同人",
    "Clinochlore": "ピアノ同人",
    "kano": "ピアノ同人",
    "kaoling": "ピアノ同人",
    "mamomo": "ピアノ同人",
    "morinoco_studio": "アンビエント同人",
    "西本梨江 ピアノ, 村川千尋 バイオリン": "クラシカル・デュオ",
    "オトノネ。音楽集-第一楽章- [CD][FLAC+CUE+LOG+BK]": "同人音楽集",
    "][Hi-Res]祈りの丘": "ピアノ同人",
    "なぐもりずの音楽室": "ピアノ同人",
    "Hoshineko Sounds 1.0": "オルゴール同人",
    "arcane": "ピアノ同人",
    "ARForest x nayuta": "アコースティック同人",
    "Sound of Swing": "ハードコア同人",
    "WAVE": "ハードコア",
    "M-Groove": "電子・ハウス",
    "RESOUND WAV": "ハードコア",
    "Rigel Theatre": "シンフォニック・ハードコア",
    "5150": "メタル系",
    "78": "メタル系",
    "Elixir Nocturne": "シンフォメタル",
    "Melnik／ニャントロ人／初音ミク": "ボーカロイドP",
    "Wolpis Carter": "ボカロ歌い手",
    "wowaka": "ボカロ伝説的P (故人)",
    "bermei.inazawa": "電子系同人",
    "cy：cle": "電子系同人",
    "Electro.muster": "電子系同人",
    "el ma Riu": "電子系同人",
    "ffffff Records": "電子系同人レーベル",
    "Mag2 Software": "電子系同人",
    "ZIZZ Studio music collection": "ゲームDTMサークル",
    "Tuatha De Danann": "ブラジルのケルト・フォーク",
    "forest": "アコースティック",
    "Fiorista Felice": "コーラス同人",
    "Ether&エルム凪": "実験同人",
    "MiddleIsland": "実験同人",
    "Noah": "実験同人",
    "notte": "実験同人",
    "onoken": "東方アレンジ",
    "dama": "コンピ枠",
    "Elliot Hsu": "ピアノ同人",
    "Elymusia": "シンフォニック同人",
    "himajin-sound (たけやん)": "コンピ枠",
    "maracy": "ピアノ同人",
    "Marchen Station": "シンフォニック同人",
    "mozell kuhu": "実験同人",
    "nayuta": "ボーカル同人",
    "pub house himari": "同人",
    "sea-no": "同人",
    "Street": "同人",
    "Studio A'": "同人",
    "timeless melody 茶太": "ピアノ・カバー",
    "toyKasket": "同人",
    "Unknown": "整理用フォルダ",
    "新しいフォルダー": "整理ミス枠",
    "埼玉最終兵器 & Aether": "メタル同人",
    "柊南(ひいな)＆clan(くらん)": "同人",
},

# ─── JPOP ──────────────────────────────────────────────
"jpop": {
    "Aimer": "少し枯れた声の質感が、 アニメ主題歌の鋳型を内側から変えた人",
    "Ado": "21世紀の声優ボーカル。 顔を出さない歌手の天井を上げた",
    "Ali project": "耽美×ゴシック×軍歌。 独自の語彙でしか書けない世界",
    "Gackt": "マラフ×クラシック×ヴィジュアル系。 日本の唯我独尊",
    "B'z": "稲葉浩志×松本孝弘。 日本のロック支配者",
    "BUMP OF CHICKEN": "藤原基央の物語歌。 21世紀日本の青春",
    "GLAY": "TAKURO率いる90s代表ロックバンド",
    "Garnet Crow": "中村由利の声と岡本仁志のギター",
    "JAM Project": "アニソン界のスーパーグループ",
    "Janne Da Arc": "yasuのヴィジュアル系王道ロック",
    "KAMIJO": "Versailles。 日本中世幻想の作家",
    "Kalafina": "梶浦由記プロデュースの女声三人組",
    "Yuki Kajiura": "梶浦由記。 アニメ音楽×コーラスの匠",
    "Yoasobi": "ikura×Ayaseの21世紀新世代",
    "Official髭男dism": "藤原聡らのソウル系JPOP",
    "ずっと真夜中でいいのに。 4thアルバム「形藻土」": "ずとまよ。 ACAねの個性派",
    "神聖かまってちゃん 15周年記念ベストアルバム『聖なる交差点』": "の子率いるオルタナ",
    "Faylan": "梶浦由記関連のアニソン",
    "Hakubi": "京都の3ピース・オルタナ",
    "Ayahi Takagaki": "声優・歌手の高垣彩陽",
    "Ceui": "ノベルゲー主題歌系",
    "binaria": "ノベルゲー系",
    "ADAM at": "アコースティック・ピアニスト",
    "DJ OKAWARI": "ジャズ×ヒップホップのトラックメイカー",
    "Pia-no-jaC": "ピアノ×カホンのデュオ",
    "Sound Horizon": "Revoの幻想音楽サークル",
    "Sound Horizon + Revo 2.0": "Sound Horizonサイドプロジェクト",
    "SUEMITSU & THE SUEMITH": "末光篤のシネマティック・ピアノロック",
    "Aimer": "重複",
    "kokia": "国際的な日本人女性ヴォーカル",
    "majiko": "切ない声の女性ヴォーカル",
    "Mili": "ENDER LILIES等を作るバイリンガル・グループ",
    "Rurutia": "幻想的な女性ヴォーカル",
    "Suara": "アニソン・ノベルゲー歌手",
    "Uru": "現代女性シンガーソングライター",
    "ReoNa": "アニソン・現代叙情",
    "Yousei Teikoku 3.0": "妖精帝國。 ゴシック・ヴィジュアル",
    "Moi dix Mois": "Manaのゴシック・ヴィジュアル",
    "MUCC": "ムック (重複)",
    "hizaki": "Versailles派生のV系ギタリスト",
    "Lia": "Keyのアニソン女性歌手",
    "MELL": "I'veのアニソン歌手",
    "Tiara": "アニソン",
    "Zwei": "アニソン女性デュオ",
    "fhána": "アニソン4人組",
    "eufonius": "アニソン",
    "fripSide": "アニソン・電子",
    "TWO-MIX 25th Anniversary ALL TIME": "永野裕子×篠原一彦のアニソンユニット",
    "GRANRODEO 20th BEST ALBUM「DOUBLE DECADES OF GR」": "GRANRODEO。 アニメロックデュオ",
    "mao Best Album「voice」": "mao。 アニソン女性ヴォーカル",
    "水樹奈々 4thベストアルバム「THE MUSEUM Ⅳ」": "水樹奈々のベスト",
    "林原めぐみ 30th Anniversary Best Album「VINTAGE DENIM」": "林原めぐみ30周年ベスト",
    "茶太 Works": "茶太。 ノベルゲー歌手",
    "茶太 Works Best Ⅱ": "茶太ベスト2",
    "Wakana": "Kalafina元メンバー",
    "vip店長": "アニソン",
    "Luz": "歌い手",
    "mol-74": "京都のオルタナ・ロック",
    "L'Arc en Ciel": "L'Arc～en～Ciel。 90s〜00sロック巨人",
    "L’Arc en Ciel": "別表記",
    "SARD UNDERGROUND": "ZARD後継のロックバンド",
    "SEKAI NO OWARI 7thアルバム「Nautilus」[96kHz／24bit]": "セカオワ。 ファンタジー・ポップ",
    "TM NET": "TM NETWORK。 80sシンセポップ巨人",
    "WANDS": "90sビーイング系ロック",
    "ZARD Forever": "ZARD坂井泉水のベスト",
    "倍賞千恵子": "日本の女優・歌手",
    "宇多田ヒカル 25周年記念アルバム「SCIENCE FICTION」[96kHz／24bit]": "宇多田ヒカル25周年",
    "ポルノグラフィティ 25周年記念ベストアルバム「ポルノグラフィティ全書": "ポルノグラフィティ25周年",
    "森山直太朗 -素晴らしい世界": "森山直太朗。 「さくら」",
    "米津玄師 6thアルバム「LOST CORNER」[48kHz／24bit]": "米津玄師。 21世紀JPOP王",
    "Miyuki Nakajima": "中島みゆき。 シンガーソングライターの女王",
    "美空ひばり": "昭和歌謡の女王",
    "あたらよ 1stアルバム「極夜において月は語らず」": "あたらよ。 オルタナバンド",
    "三月のパンタシア 10周年記念ベストアルバム「多彩透明なブルーだった」": "三月のパンタシア",
    "三月のパンタシア 5th Album「愛の不可思議」[48kHz／24bit]": "三月のパンタシア5th",
    "亜咲花 3rd Album「Who’s Me？」": "亜咲花。 アニソン",
    "ヘブンバーンズレッド 麻枝准×やなぎなぎ 2ndアルバム「Welcome to the Dying Season」": "麻枝准×やなぎなぎ",
    "こはならむ": "こはならむ。 シンガーソングライター",
    "Reol": "Reol。 R&B/トラップJPOP",
    "Reol 4th Album「美辞学」[48kHz／24bit]": "Reol4th",
    "May’n": "May'n。 マクロスFのアニソン",
    "ORIGA": "ロシア出身のアニソン女性歌手",
    "Creepy Nuts": "R-指定×DJ松永",
    "ポルノグラフィティ": "ポルノグラフィティ",
    "Kagrra": "ヴィジュアル系",
    "NHK みんなのうたより ベストセレクション": "NHKみんなのうたコンピ",
    "CrosSing": "アニソン・コンピ",
    "CLIMAX": "コンピ枠",
    "好きです かわさき♪": "ご当地ソング",
    "いつも何度でも-いのちの名前": "ジブリ主題歌",
    "永遠のSEED": "ガンダムSEED主題歌",
    "Healing": "コンピ枠",
    "HAWAIIAN6": "日本のメロコア",
    "Blueberry & Yogurt": "Rita。 アニソン",
    "Omoinotake": "Soul/オルタナバンド",
    "orange pekoe": "渋谷系ジャズポップ",
    "茶太": "茶太",
},

# ─── Celt & Fantasy & Violin ─────────────────────────
"celt": {
    "Adrian von Ziegler": "スイスから一人で出すファンタジー音楽の量産機",
    "Antti Martikainen": "フィンランドの叙事詩作曲家。 北欧神話を音にする",
    "Trobar De Morte": "スペインの中世音楽復興。 死を歌う中世女性の現代版",
    "Ana Alcaide": "ニッケルハルパを弾くスペイン人。 ヨーロッパ周縁の音",
    "Aura Noctis": "イタリアのゴシック・ダーク・ファンタジー",
    "2Cellos": "ロックを2台のチェロで。 クラシックと大衆の境界",
    "David Garrett": "ドイツのクラシック・クロスオーバー・ヴァイオリン",
    "Lindsey Stirling": "アメリカのダンス・ヴァイオリン",
    "Tina Guo": "中国・米国のチェロ・メタル",
    "Caprice": "ロシアの中世幻想音楽",
    "Altan": "アイルランドの正統派フォーク",
    "The Chieftains": "アイルランド・トラディショナル巨人",
    "Celtic Thunder": "アイリッシュ・ヴォーカル・グループ",
    "Celtic Woman": "アイリッシュ・女性ヴォーカル・グループ",
    "Clannad": "Enya輩出のケルト・グループ",
    "Loreena McKennitt": "カナダのケルト女王 (重複)",
    "Austin Wintory": "Journeyの作曲家",
    "Mediavolo": "中世風ゴシック",
    "Marketa Irglova": "Onceの女性ヴォーカル",
    "FLEUR & Elena Voynarovskaya": "ウクライナのゴシック",
    "Savina Yannatou": "ギリシャの女性ヴォーカル",
    "The Wong Janice": "ハープ奏者",
    "Donis": "中世風女性ヴォーカル",
    "Sally Doherty & The Sumacs": "ケルト系",
    "Spiro": "英国のフォーク・カルテット",
    "Genevieve Walker": "クラシカル・ヴァイオリン",
    "Flook": "アイリッシュ・トラディショナル・カルテット",
    "Joanie Madden": "Cherish the Ladies のフルート奏者",
    "Leahy": "カナダのフィドル・ファミリー",
    "Mick McAuley, Winifred Horan": "Solas のフィドラー",
    "Luar na Lubre": "ガリシアのケルト",
    "Hevia": "スペインのバグパイプ・テクノ",
    "Green Hill_ 30 Years Of Celtic": "Green Hillレーベル30年",
    "The Swell Season": "Glen Hansard×Marketa Irglovaのデュオ",
    "The Swell Season, Glen Hansard & Marketa Irglova-Forward": "重複",
    "River Song": "ケルト系",
    "Jean-Luc Ponty": "フランスのジャズ・ヴァイオリン",
    "Jerry Goodman": "Mahavishnu Orchestraのヴァイオリン",
    "David Davidson_Rock Me Classical": "ロックをクラシックで",
    "Enigma Quartet": "弦楽カルテット",
    "Tin-Tin Quartet-Confrontation": "弦楽カルテット",
    "Julia Okrusko": "ヴァイオリン",
    "Darryl Way": "Curved Air のヴァイオリン",
    "Darol Anger": "アメリカのフィドル/ヴァイオリン",
    "Ayasa_Best_Album_-_BEST_II_FLAC": "AYASA。 日本のヴァイオリニスト",
    "92 Keys": "ピアノ・カバー",
    "西本梨江 ピアノ, 村川千尋 バイオリン": "クラシック・デュオ",
    "Logan Epic Canto": "シネマティック・トレイラー",
    "The London Studio Orchestra": "ロンドン・スタジオ管",
    "Mychael & Jeff Danna": "兄弟作曲家",
    "Nino rota": "ニーノ・ロータ。 イタリアの映画音楽",
    "Les Fragments de la Nuit": "フランスのチェンバー・ニューエイジ",
    "Vladimir Cosma": "フランスの映画音楽",
    "Solaris": "シネマティック",
    "David Arkenstone": "アメリカのファンタジー・ニューエイジ",
    "Diane Arkenstone": "David Arkenstoneの妻、 ニューエイジ",
    "Fox Amoore": "ファンタジー・ピアノ",
    "Peter Crowley": "ファンタジー・トレイラー",
    "Jeff Victor": "ファンタジー作曲家",
    "Epic Background": "シネマティック・コンピ",
    "Corde Oblique": "イタリアのダーク・ネオフォーク",
    "The Moon And The Nightspirit": "ハンガリーのダーク・ペイガン",
    "Ordo Funebris, Narsilion": "中世風ゴシック",
    "Keltania": "ダーク・ネオフォーク",
    "Kryptik Wood": "ダーク・ネオフォーク",
    "Theodor Bastard": "ロシアの民族エレクトロニカ",
    "Za frumi": "ペイガン・ネオフォーク",
    "Uriel": "ダーク・ネオフォーク",
    "Leah": "Leah McHenry。 ケルト・メタル",
    "Opium Moon": "アメリカン・ニューエイジ",
    "Nawang Dautar": "チベット系",
    "Enrico Fabio Cortese": "ピアノ・ヴァイオリン",
    "Nor Dar": "ケルト系",
    "Paulo Cesar Escobedo": "ラテン・ヴァイオリン",
    "Jessita Reyes": "ネイティブ・フルート",
    "Zhao Kun Yu": "中国系作曲家",
    "Gallo": "ケルト枠",
    "Chapitre Bleu-青の章": "コンセプト盤",
    "Legend of Excalibur": "アーサー王コンセプト盤",
    "style-3!": "コンセプト盤",
    "V-A": "Various Artistsコンピ",
    "benedikt": "ピアノ作曲家",
    "Beyond The Woods": "ケルト",
    "Barry O'sullivan": "ケルト・ハープ奏者",
    "Carlyle Fraser": "ケルト",
    "Cathal MacDara": "ケルト",
    "Derek Fiecher": "Fantasy Music。 別表記Derek Fiechter",
    "Faun": "ドイツのペイガン・フォーク",
    "Estampie": "中世音楽復興",
    "Mediaeval Baebes": "英国の中世女性ヴォーカル",
},

# ─── Game ─────────────────────────────────────────────
"game": {
    "Final Fantasy": "植松伸夫らのRPG音楽の文法を作ったシリーズ",
    "Dragon Quest": "すぎやまこういちのRPG音楽古典",
    "Falcom Sound Team jdk collection": "日本ファルコムの長きにわたる蓄積",
    "Bravely Default OST": "Revo (Sound Horizon) の音楽性が出たJRPG",
    "Baten Kaitos": "桜庭統の剛直なRPG音楽",
    "ENDER LILIES：Quietus of the Knights Original Soundtrack": "Mili作曲の慟哭の聖歌",
    "NieR": "岡部啓一のSquare Enix叙事詩",
    "OCTOPATH TRAVELER Original Soundtrack": "西木康智の現代JRPG",
    "Xenoblade Original Soundtrack": "光田康典らのモノリス・サウンド",
    "Kingdom Hearts": "下村陽子のディズニー×JRPG",
    "Calling All Dawns": "Christopher Tin。 Civilization IVグラミー",
    "Donkey Kong Country Trilogy": "David Wiseのジャングル×アンビエント",
    "ICO": "上田文人作品の幻想OST",
    "MOTHER 1+2 Original Soundtrack": "鈴木慶一×田中宏和",
    "Live A Live": "下村陽子",
    "Star Ocean": "桜庭統のスペースオペラRPG",
    "Tales of": "桜庭統のテイルズ",
    "TalesWeaver Original Soundtrack": "テイルズウィーバーOST",
    "Sekaiju no MeiQ": "古代祐三の世界樹の迷宮",
    "Yoko Shimomura": "下村陽子。 KH/FFXVの作曲家",
    "Yu-peng Chen": "原神のメインコンポーザー",
    "Yasunori Mitsuda Vocal Collection": "光田康典のヴォーカル集",
    "GRANBLUE FANTASY": "成田勤・植松伸夫のグラブル",
    "Symphony Sounds Record": "JRPGコンサート集",
    "LORD of VERMILION Re-2 FAN KIT": "光田康典のLoVファンキット",
    "Grand Knights History Original Soundtrack": "Vanillaware×崎元仁",
    "GRANDIA": "岩垂徳行のRPG音楽",
    "イースシリーズ": "ファルコム・イース",
    "Saga": "サガシリーズ",
    "Chrono": "光田康典・植松伸夫のクロノ",
    "テイルズ": "テイルズシリーズ",
    "ロマンシング サ・ガ": "ロマサガ・伊藤賢治",
    "Fire Emblem": "辻横由佳らのFE音楽",
    "Hentai Prison": "ノベルゲー",
    "OMORI OST": "Pedro Silva作曲のインディーRPG",
    "Ori and the Blind Forest by Gareth Coker": "Gareth Coker のOri",
    "Undertale": "Toby Fox の Undertale",
    "Dies irae": "正田崇のノベルゲー",
    "DemonsRoots": "ノベルゲー",
    "DRACULA": "Castlevania。 山下絹代らのドラキュラ",
    "Castlevania": "悪魔城ドラキュラシリーズ",
    "腐り姫": "ノベルゲー",
    "メメントモリ": "メメントモリゲー",
    "9-nine- Sound Premium Record": "ノベルゲー9-nine-",
    "AKABEiSOFT2": "ノベルゲーブランド",
    "ALcot": "ノベルゲーブランド",
    "AUGUST": "ノベルゲーブランド",
    "CROSS†CHANNEL": "ノベルゲー田中ロミオ",
    "Ever17_OST": "中澤工のEver17",
    "FAVORITE": "ノベルゲーブランド",
    "A New Story": "ノベルゲー",
    "Ar tonelico Hymmnos Musical Vocal Mini Album ~Cocona~": "アルトネリコ志方あきこ",
    "BALDR MASTERPIECE CHRONICLE Complete Vocal Collection": "BALDR シリーズ・ヴォーカル",
    "うたわれるもの 偽りの仮面＆二人の白皇 歌集": "うたわれるもの",
    "双星の陰陽師 Music Collection Album": "双星の陰陽師",
    "細井聡司ワークス": "細井聡司",
    "CUFFS SONGS BEST": "CUFFSノベルゲー",
    "SAGA PLANETS 四季ボーカルコレクション": "SAGA PLANETS",
    "GIGA BEST ALBUM -戯画ベストアルバム": "戯画ベスト",
    "GIGA BEST ALBUM": "戯画ベスト",
    "戯画ベストアルバム": "戯画ベスト",
    "ファタモルガーナの館": "ノベルゲーOST",
    "Marica ワークスベストアルバム「UNDER THE SUN」": "MaricaのVNワークス",
    "9-nine- Sound Premium Record": "9-nine-",
    "CROSS†CHANNEL ～In memory of all people～ SPECIAL SOUNDTRACK": "クロスチャンネル",
    "AKABEiSOFT2": "アカベィソフト2",
    "Bravely Default OST": "Revoのブレイブリー",
    "namco": "ナムコ",
    "SQUARE ENIX": "スクウェア・エニックス",
    "Gust": "ガスト",
    "KONAMI": "コナミ",
    "オリジナル・サウンド・オブ・グラディウス＆沙羅曼蛇 バトル ミュージック コレクション": "コナミの古典シューター",
    "capcom 30周年": "カプコン30周年",
    "NAMCO SOUND TEAM": "ナムコ・サウンドチーム",
    "ダライアスバースト": "ZUNTATA。 タイトーのシューター",
    "田中勝己": "コナミ作曲家",
    "細井聡司": "細井聡司",
    "浜渦正志": "FFXIIIの作曲家",
    "志倉千代丸": "Steins;Gate",
    "Stein Gate": "シュタインズ・ゲート",
    "Game Music Graffiti 任天堂大全集": "任天堂音楽集",
    "Kid Icarus Uprising Original Soundtrack": "古代祐三のパルテナの鏡",
    "Rockman Theme Song Collection": "ロックマン主題歌",
    "Metal Gear Solid Vocal Tracks": "MGSヴォーカル",
    "Monster Hunter": "甲田雅人のモンハン",
    "R4 -THE 20TH ANNIV. SOUNDS": "リッジレーサー4・20周年",
    "Pluto Original Soundtrack": "プルート・OST",
    "NOSTALGIA Music Collection Op.1 & Op.2": "コナミのピアノゲー",
    "RAIL SOUND THE BEST [N,A]": "鉄道ゲーOST",
    "双星の陰陽師 Music Collection": "双星の陰陽師",
    "Sakuna：Of Rice and Ruin original soundtrack[USA]／音楽：大嶋啓之": "天穂のサクナヒメ",
    "duca": "duca。 ノベルゲー歌手",
    "yozuca＊": "yozuca*。 ノベルゲー歌手",
    "I've Girls Compilation": "I've Soundのアニソン",
    "MANYO WORKS BEST!!": "Manyoの作曲集",
    "YUZUSOFT VOCAL COLLECTION 2006-2016": "ゆずソフト",
    "nine- Sound Premium Record": "9-nine-",
    "KOTOKO's GAME SONG COMPLETE BOX 「The Bible」": "KOTOKO",
    "Love Song from the Water": "ノベルゲー",
    "Neko Sound Collection": "ノベルゲー音源",
    "Single": "シングル",
    "Shade Music Laboratory": "ノベルゲー音源",
    "The Greatest Video Game Music": "ゲーム音楽コンピ",
    "TPR": "ピアノアレンジ",
    "Christopher Tin": "Civilization IV作曲家",
    "flashygoodness": "Tower of Heaven作曲家",
    "Ori and the Blind Forest by Gareth Coker": "Ori。 Gareth Coker",
    "wac": "wac。 BEMANI作曲家",
    "Laurence Manning": "ゲーム作曲家",
    "dai": "dai。 アニソン作曲家",
    "trabling": "ピアノアレンジ",
    "zircon": "Andrew Aversa。 ゲーム音楽家",
    "松本文紀": "ゲーム作曲家",
    "細井聡司ワークス -Vocalists": "細井聡司ヴォーカル",
    "メモオフ ピアノコレクション第２集": "メモリーズオフピアノ",
    "トラベリング・オーガスト2015 ピアノアレンジ集 “Primary Notes”": "AUGUSTピアノアレンジ",
    "ZIZZ Studio music collection": "ZIZZ Studio (重複)",
    "Job for a Rockstar_rar": "ヴォーカル",
    "FamilyJules": "ゲーム音楽カバー",
    "春眠旅団": "VNヴォーカル",
    "御伽櫻": "VNヴォーカル",
    "Falcom Sound Team jdk collection": "ファルコム",
    "Frontwing": "フロントウイング",
    "Katahane": "ノベルゲー",
    "Key": "Key (Kanon, AIR, CLANNAD)",
    "KiRite (SBPS-0008~9)": "KiRite",
    "Laplacian": "ノベルゲーブランド",
    "Leaf": "Aqua/Pleasureの古典VN",
    "Liar soft": "Liarソフト",
    "Quartett!": "Liar-softの音ゲー",
    "purple software": "ノベルゲーブランド",
    "Pulltop Vocal Collection": "プルトップ",
    "Sakura Musubi": "ノベルゲー",
    "SNOW ORIGINAL SOUNDTRACK": "PULLTOP の SNOW",
    "Symphonic Rain": "Kogadoのノベルゲー",
    "âge": "age (Muv-Luv)",
    "キラ☆キラ": "Overdrive",
    "借金姉妹２ SoundTrack": "ノベルゲー",
    "最果てのイマ ORIGINAL SOUND TRACK": "ノベルゲー",
    "PHANTASM 榊原ゆい": "榊原ゆいのノベルゲー楽曲集",
    "fengヴォーカルコレクション": "feng (sound edge)",
    "CaveStory": "天谷大輔のCave Story",
    "Complete Collection": "コンピ",
    "オリジナルサウンドトラック": "OST枠",
    "いますぐ": "コンピ枠",
    "Dragon Ball": "ドラゴンボール",
    "ZUN Touhou Official Music Collection": "ZUNの東方Project公式",
    "Epic Game Music": "ゲーム音楽コンピ",
    "Yasunori Mitsuda Vocal Collection": "光田康典 (重複)",
},

# ─── Anime ──────────────────────────────────────────
"anime": {
    "Frieren Beyond Journey's End Original Soundtrack": "Evan Call の葬送のフリーレン",
    "Code Geass Sound Collection": "中川幸太郎・黒石ひとみの叙事詩",
    "Elfen Lied Original Soundtrack": "ラテン語コーラスの「Lilium」",
    "Charlotte Original Soundtrack": "Anant・Lia・LiSA。 Key作品",
    "A Place Further than the Universe": "藤澤慶昌の南極日常",
    "86 Eighty-six": "澤野弘之系の戦闘ドラマOST",
    "Akame ga KILL! アカメが斬る！": "戦闘×悲劇OSTの典型例",
    "Hunter X Hunter": "古典蓄積の長期OST",
    "Fate Stay Night": "梶浦由記のFate",
    "ドラゴンクエスト ダイの大冒険": "ダイの大冒険",
    "鋼の錬金術師": "ハガレンOST",
    "BEST OF INUYASHA 百花繚乱 -犬夜叉 テーマ全集": "犬夜叉主題歌全集",
    "Slam Dunk": "スラムダンクOST",
    "Shangri-La": "シャングリラ",
    "ヒカルの碁 主題歌全集-ベスト オブ ヒカルの碁": "ヒカルの碁",
    "サイレントメビウス THE BEST MUSIC COLLECTION FLAC": "サイレントメビウス",
    "双星の陰陽師": "双星の陰陽師",
    "P.A.WORKS 20th Anniversary Theme Song Collection": "PA WORKSの20周年集",
    "Jyukai_BEST": "Jyukai。 アニソン女性ユニット",
    "森口博子 アニソンカバーアルバム 第2弾「ANISON COVERS 2」": "森口博子のアニソンカバー",
    "OST": "OST枠",
    "Project": "プロジェクト枠",
    "THE": "コンピ枠",
    "P.A.WORKS 20th Anniversary Theme Song Collection": "PAWORKS",
    "Chameleon Jazz with ANIME Flavor": "アニメ・ジャズ",
    "MARASY": "MARASY (まらしぃ)。 ピアノでアニソン",
    "高橋洋子": "「残酷な天使のテーゼ」 のエヴァOP歌手",
    "水樹奈々": "水樹奈々",
    "宮本駿一": "声優",
    "Wakana": "Kalafina元メンバー",
    "violet evergarden": "Evan Callのヴァイオレット・エヴァーガーデン",
    "Grimgar of Fantasy and Ash": "灰と幻想のグリムガル",
    "Heart of Magic Garden": "アニメOST",
    "DEAREST DROP": "アニメOST",
    "サイレント・ウィッチ": "沈黙の魔女",
    "メイドインアビス 烈日の黄金郷": "メイドインアビスS3",
    "Pluto Original Soundtrack": "プルートOST",
    "Gunslinger girl": "ガンスリンガーガール",
    "WOLF'S RAIN O.S.T": "菅野よう子のウルフズ・レイン",
    "ISEKAI": "異世界アニメコンピ",
    "BEST OF CHIHIROX": "アニソンコンピ",
    "animage 2 ~NEW ANIMATION SONGS~": "アニメージュ・コンピ",
    "animage ~NEW ANIMATION SONGS~": "アニメージュ・コンピ",
    "Anime": "アニメコンピ",
    "Anime collection ACG": "アニメコンピ",
    "Anime Piano": "アニメピアノ",
    "Anime Piano Works": "アニメピアノ",
    "Anime [Collection]": "アニメコンピ",
    "Never Let You Go": "アニメ歌曲",
    "魔法少女リリカルなのは": "なのはOST",
    "蒼穹のファフナー EXODUS": "ファフナーOP",
    "クロスアンジュ 天使と竜の輪舞": "クロスアンジュOP",
    "戦姫絶唱シンフォギアGX": "シンフォギアGX",
    "ave;new": "ave;newのアニメ歌曲",
    "Studio Ghibli": "宮崎駿作品・スタジオジブリ",
    "TVアニメ メイドインアビス 烈日の黄金郷 オリジナルサウンドトラック": "メイドインアビス3期",
    "TVアニメ「クロスアンジュ 天使と竜の輪舞」OP2テーマ「真実の黙示録」／高橋洋子": "クロスアンジュOP2",
    "TVアニメ「戦姫絶唱シンフォギアG」OPテーマ -「Vitalization」／水樹奈々": "シンフォギアG OP",
    "TVアニメ「蒼穹のファフナー EXODUS」OP&EDテーマ「イグジスト／暗夜航路」／angela": "ファフナー EXODUS OP/ED",
    "「Exterminate」水樹奈々": "シンフォギアGX OP",
    "｢Los! Los! Los!｣／ターニャ・デグレチャフ": "幼女戦記",
    "TVアニメ「転生貴族、鑑定スキルで成り上がる」OPテーマ「ReCoda／ブルーデイズ」／TRUE [鑑定スキル盤]": "転生貴族OP",
    "Vitalization": "シンフォギアOP",
    "イグジスト/暗夜航路": "ファフナーOP/ED",
    "真実の黙示録": "クロスアンジュOP2",
    "Exterminate": "シンフォギアGX OP",
    "Butter-Fly": "デジモンOP",
    "TVアニメ「魔法少女リリカルなのは」オリジナルサウンドトラック": "なのはOST",
    "TVアニメ『サイレント・ウィッチ 沈黙の魔女の隠しごと』Original Soundtrack": "サイレント・ウィッチOST",
    "片霧烈火": "片霧烈火。 ノベルゲー歌手",
    "機動天使エンジェリックレイヤー OP": "エンジェリックレイヤーOP",
    "KOTOKO": "KOTOKO。 アニソン女性歌手",
    "Helck": "Helck",
    "『とある科学の超電磁砲』OP「only my railgun -version 2024- & -15th Anniversary version-」fripSide[96kHz／24bit]": "とある超電磁砲OP only my railgun",
},

# ─── Nature ─────────────────────────────────────────
"nature": {
    "Gordon Hempton": "「Earth - A Day」 で知られる世界的サウンド・アーキビスト",
    "Dan Gibson's Solitudes": "1970年代から続くカナダ環境録音の老舗",
    "Andrew Fitzgerald": "ピアノと弦と自然音の融合",
    "KENJI KIHARA": "日本の山と川を録音した人",
    "Hennie Bekker": "南アフリカ＋カナダの自然+シンセ派",
    "Larkin": "笛+海の音の1980年代型ヒーリング",
    "Boom Library SOE Autumn": "プロ向け効果音ライブラリ",
    "Echoes Of Nature": "自然音アーキビスト",
    "Forest Ambience": "森の環境音",
    "Brian Hardin": "森のフィールドレコーディング",
    "Nature Sound Healing.ape": "ヒーリング・コンピ",
    "Nature Sound Retreat": "睡眠用自然音",
    "Andrea Rongioletti": "イタリアのピアノ・ヒーリング (重複)",
    "Marcia Green - Morning Piano and Nature Sounds": "ピアノ+自然",
    "Helen Rhodes & Joseph Wade": "Ein Sauna Tag。 サウナ用音楽",
    "Jamie Llewellyn": "ハイブリッド自然音",
    "Wisp X": "アンビエント自然",
    "ELF": "自然系コンピ",
    "K Ambient Sounds": "睡眠機能音楽",
    "Sleeping Music": "睡眠機能音楽",
    "Ambient Music for Cats": "猫用ヒーリング",
    "2019ボロヴィツィ村の朝": "ロシアの村の朝の録音",
    "David Sun": "海・水の音",
    "Criss Howell": "海岸線の録音",
    "Sounds of the Sea": "海の音",
    "Nature Sound Healing. ape": "重複",
    "Nature Sounds": "コンピ",
    "Nature Sounds Collection_ Forest Stream & Birds": "コンピ",
    "Sounds Of The Earth": "コンピ",
    "Sounds of Wildlife-Alone with the Rain": "コンピ",
    "The Sound Of Nature": "コンピ",
    "The Sounds Of Nature[2 Box Set": "コンピ",
    "WW Nature Sounds": "コンピ",
    "Tropical Jungle (Stereo)": "ジャングル",
    "walk in forest": "森の散策",
    "Nichole Reed": "ピアノ+自然",
    "Pau Viguer": "ピアノ+自然",
    "Retiro De Yoga Con Lluvia Serena De Piano": "ヨガ用ピアノ",
    "Relaxation": "リラクゼーション",
    "Thomas Skymund": "ヒーリング",
    "Studio Planet – Cinematic Sound Pack Collection": "シネマ用効果音",
    "Neal Robinson": "シネマ・サウンド",
    "4CD-2004FLAC": "コンピ",
    "Giovanni": "イタリア系自然",
    "Global Journey": "ワールドコンピ",
},

# ─── Blues & Folk ───────────────────────────────────
"blues-folk": {
    "Loreena McKennitt": "カナダのケルト女王。 シルクロードを音楽化した人",
    "McKennitt, Loreena": "別表記",
    "Natalie Merchant...Ophelia": "10000 Maniacsソロ転身後の最高作",
    "Annwn -《Orbis Alia》": "ドイツのケルト音楽",
    "Liberte": "ラトビアのフォーク",
    "Joran Elane": "ハイランド・フォーク",
    "Neun Welten": "ドイツのダーク・フォーク",
    "Lucy Rose": "英国のシンガーソングライター",
    "Rickie Lee Jones": "1979年デビューの米国の物語の歌い手",
    "Take A Picture": "コンピ",
    "Autumn Tears": "ゴシック × ピアノ × 弦 + 女性ボーカル",
    "Iridio": "ハイブリッド・ゴシック",
},

# ─── Pop & Rock ─────────────────────────────────────
"pop-rock": {
    "Hans Zimmer": "Interstellar・Inception。 21世紀劇伴の天井を引き上げた",
    "Hans Zimmer - Interstellar": "Interstellar Expanded",
    "Andrea Bocelli": "イタリア・テナーの大衆性",
    "Phantom of the Opera": "ロイドウェバーのミュージカル定番",
    "Bon Jovi 2010": "Bon Joviベスト",
    "Bon Jovi": "Bon Jovi",
    "Foo Fighters": "Dave Grohlの米国ロック定番",
    "Deep Purple": "ハードロック巨人",
    "Dua Lipa": "21世紀ポップ",
    "Eminem": "ホワイトラッパーの王",
    "Kylie Minogue": "オーストラリアのポップ女王",
    "Helene Fischer": "ドイツの歌姫",
    "Jamiroquai": "Jay Kayの英国アシッド・ジャズ",
    "Death Cab for Cutie": "米国インディーロックの叙情派",
    "Death Cab For Cutie": "別表記",
    "Copeland": "米国インディーロック",
    "Einar Stray": "ノルウェーのインディーロック",
    "Jack's Mannequin": "Andrew McMahonのプロジェクト",
    "Ben Folds & Nick Hornby": "Ben Folds×Hornby・歌詞コラボ",
    "Judee Sill": "70年代の伝説的SSW",
    "Leon Russell": "Mad Dogs & Englishmenの伝説",
    "Concerto Moon": "日本のメロディック・パワーメタル",
    "Jackie Evancho": "アメリカのクラシカル・クロスオーバー少女",
    "Ernie Watts": "サックス奏者",
    "High Llamas": "Sean O'Haganの英国チェンバーポップ",
    "Miracles of Modern Science": "プロ・チェンバー・ポップ",
    "Priscilla Ahn": "アメリカの繊細SSW",
    "Sigur Rós": "アイスランドのポストロック幻想",
    "Waking Ashland": "米国インディーロック",
    "Mae": "米国ポストハードコア",
    "Something Corporate": "Andrew McMahon系",
    "The Zombies": "60sブリティッシュ・サイケ",
    "Waltari": "フィンランドのアヴァン・メタル",
    "Tarja": "Nightwish元ヴォーカル",
    "Susan Boyle": "Britain's Got Talent からの世界的歌姫",
    "Waterflame": "Geometry Dash作曲家",
    "Vienna Boys' Choir": "ウィーン少年合唱団",
    "Voces8": "英国のヴォーカル・アンサンブル",
    "Real Group": "スウェーデンのアカペラ",
    "Paco de Lucía": "フラメンコ・ギターの神",
    "Dream State": "ロックバンド",
    "Andrea Bocelli - Duets (30th Anniversary)": "ボチェッリ30周年デュエット",
    "Between the Senses": "ロックバンド",
    "Dream": "ポップ",
},

}
