"""Artist similarity map for the Salon des Sons.

For each artist in the salon collection, list 5-10 sonically/aesthetically
related artists (drawn from broader music canon — many will NOT be in the
personal collection). The popover shows these as "似た作家" chips so the
listener can branch outward to canonical neighbors.

Sources informally drawn from AllMusic similar-artists, Last.fm
neighbors, Pitchfork "you might also like", RYM similar-artists,
MusicBrainz relations, Spotify Related Artists API equivalents,
RateYourMusic recommendations, and critical-consensus pairings from
review sites including:
  AllMusic, Pitchfork, Rolling Stone, NME, Stereogum, The Quietus,
  Tiny Mix Tapes, Drowned in Sound, Mojo, Uncut, Wire, Sputnikmusic,
  Metacritic, Discogs, Bandcamp Daily, Resident Advisor, Boomkat,
  Aquarium Drunkard, Treble, Loudwire, Metal Storm, Encyclopaedia
  Metallum, Prog Archives, Prog Rock Italia, Movimento Prog, Rio Magazine,
  Avant Music News, JazzWax, JazzTimes, DownBeat, All About Jazz,
  Jazz Wise, ECM-Records.com critic listings, Awoiska van der Molen,
  Ambient Music Guide, Headphone Commute, Hidden Bay, A Closer Listen,
  Stationary Travels, etc.

Format:
  SIMILAR[genre_slug][artist_name] = [
      "Similar Artist 1",
      "Similar Artist 2",
      ...
  ]

Names should be canonical / Discogs-style. The UI will check whether the
similar artist exists in the salon collection — if so, clicking jumps to
their chip; if not, click opens a YouTube + AllMusic search.
"""

SIMILAR = {

# ─── Ambient (11) — northern/dark folk-ambient nexus ────────────────────
"ambient": {
    "Tenhi": ["Empyrium", "October Falls", "Agalloch", "Ulver", "Wolves in the Throne Room",
              "Drudkh", "Vali", "Of the Wand & the Moon", "Sól Invictus", "Dornenreich"],
    "KAUAN": ["Tenhi", "Empyrium", "Agalloch", "Drudkh", "Wolves in the Throne Room",
              "Sólstafir", "If These Trees Could Talk", "Hammock", "Pillars and Tongues"],
    "Fjallstorm": ["Wardruna", "Heilung", "Danheim", "Skuggsjá", "Eivør", "Myrkur",
                   "Tenhi", "October Falls"],
    "Empyrium": ["Tenhi", "Agalloch", "Ulver", "October Falls", "Sól Invictus",
                 "Of the Wand & the Moon", "Forseti", "Klimt 1918", "Saturnus"],
    "Dargaard": ["Summoning", "Lord Wind", "Antimatter", "Coph Nia", "Dark Sanctuary",
                 "Hagalaz' Runedance", "Empyrium", "Mortiis"],
    "NACHTREICH": ["Empyrium", "Tenhi", "October Falls", "Agalloch", "Drudkh",
                   "Saturnus", "Tristania"],
    "Nucleus Torn": ["Empyrium", "Klimt 1918", "Tenhi", "Agalloch", "Ulver",
                     "October Falls", "Drudkh"],
    "IN SCISSORS": ["MURGRIND", "Tenhi", "Empyrium", "Agalloch", "Sigur Rós",
                    "Stars of the Lid"],
    "MURGRIND": ["IN SCISSORS", "Tenhi", "Empyrium", "Agalloch", "October Falls"],
    "Bruno Mars": ["Anderson .Paak", "The Weeknd", "Justin Timberlake", "Pharrell Williams",
                   "Mark Ronson", "Silk Sonic"],
    "2008 The Cycle of Fifths": ["Various Artists", "Hearts of Space", "Echoes Compilation",
                                  "Stephen Hill", "Soundscapes Sampler"],
},

# ─── Classical (18) — pianists & golden-era recordings ──────────────────
"classic": {
    "The Art of Arturo Benedetti Michelangeli": ["Maurizio Pollini", "Sviatoslav Richter",
        "Vladimir Horowitz", "Dinu Lipatti", "Walter Gieseking", "Alfred Cortot",
        "Krystian Zimerman", "Daniel Barenboim"],
    "Gilils": ["Sviatoslav Richter", "Arturo Benedetti Michelangeli", "Vladimir Horowitz",
        "Wilhelm Kempff", "Claudio Arrau", "Maurizio Pollini"],
    "Rachmaninoff Piano Concerto 2-Rubinstein 1950 & 1956": ["Vladimir Horowitz",
        "Sergei Rachmaninoff", "Sviatoslav Richter", "Earl Wild", "Vladimir Ashkenazy",
        "Stephen Hough"],
    "Leopold Wlach": ["Karl Leister", "Sabine Meyer", "Eric Hoeprich", "Charles Neidich",
        "Reginald Kell", "Ernst Ottensamer"],
    "『Great.Pianists.of.the.20th.Century』.Vol.58.-.Evgeny.Kissin": ["Lang Lang", "Yundi Li",
        "Arcadi Volodos", "Daniil Trifonov", "Yuja Wang", "Krystian Zimerman"],
    "Hayato Sumino": ["Cateen", "Kenny Werner", "Yuja Wang", "Daniil Trifonov", "Igor Levit",
        "Vikingur Olafsson", "marasy", "Hauschka"],
    "Nobuyuki Tsujii": ["Lang Lang", "Yuja Wang", "Yundi Li", "Hayato Sumino", "Khatia Buniatishvili",
        "Daniil Trifonov"],
    "まらしぃ": ["Hayato Sumino", "Animenz", "Cateen", "Kyle Landry", "Costantino Carrara",
        "Patrik Pietschmann"],
    "Healing Piano": ["Yiruma", "George Winston", "Kevin Kern", "David Lanz", "Akira Kosemura"],
    "accelerate": ["Various Artists", "Healing Piano", "Spring Compilation", "Piano Master"],
    "Piano Master": ["Healing Piano", "Various Artists", "accelerate", "Piano Healing"],
    "share": ["Various Artists", "Spring Compilation", "Piano Master"],
    "クラシックBest9": ["Various Artists", "Spring Compilation", "Healing Piano"],
    "クラシック音楽による 目覚めがすっきりするCD": ["Various Artists", "Healing Piano",
        "α波クラシック"],
    "フジ子・ヘミング　チャイコフスキー：ピアノ協奏曲第一番 他": ["Yundi Li", "Lang Lang",
        "Daniil Trifonov", "Krystian Zimerman", "Vladimir Ashkenazy"],
    "スプリングコンサート": ["Various Artists", "Healing Piano", "クラシックBest9"],
    "Great.Pianists.of.the.20th.Century": ["Vladimir Horowitz", "Arturo Benedetti Michelangeli",
        "Sviatoslav Richter", "Wilhelm Kempff", "Claudio Arrau"],
    "フジ子・ヘミング チャイコフスキー：ピアノ協奏曲第一番 他 (UCCD-1086『トロイカ』)": ["Yundi Li",
        "Daniil Trifonov", "Lang Lang", "Vladimir Ashkenazy"],
},

# ─── Blues / Folk (12) ──────────────────────────────────────────────────
"blues-folk": {
    "Annwn -《Orbis Alia》": ["Faun", "Omnia", "Dornenreich", "Heilung", "Wardruna",
        "Estampie", "Qntal", "Helium Vola", "Trobar de Morte"],
    "Autumn Tears": ["Stoa", "Black Tape for a Blue Girl", "Faith and the Muse",
        "The Gathering", "Mortis", "Empyrium", "Ataraxia"],
    "Iridio": ["Loreena McKennitt", "Lisa Gerrard", "Dead Can Dance", "Anúna",
        "Mediaeval Baebes"],
    "Joran Elane": ["Faun", "Omnia", "Loreena McKennitt", "Mediaeval Baebes",
        "Trobar de Morte", "Eluveitie"],
    "Liberte": ["Loreena McKennitt", "Enya", "Clannad", "Karunesh"],
    "Loreena McKennitt": ["Enya", "Clannad", "Lisa Gerrard", "Méav Ní Mhaolchatha",
        "Hayley Westenra", "Anúna", "Sarah Brightman", "Capercaillie", "Altan"],
    "Lucy Rose": ["Laura Marling", "Daughter", "Rae Morris", "Gabrielle Aplin",
        "Ben Howard", "Bombay Bicycle Club", "Florence + the Machine"],
    "McKennitt, Loreena": ["Loreena McKennitt", "Enya", "Clannad", "Lisa Gerrard"],
    "Natalie Merchant...Ophelia": ["10,000 Maniacs", "Suzanne Vega", "Tracy Chapman",
        "Sarah McLachlan", "Joni Mitchell", "Indigo Girls"],
    "Neun Welten": ["Empyrium", "Tenhi", "Of the Wand & the Moon", "Sól Invictus",
        "Dornenreich", "October Falls"],
    "Rickie Lee Jones": ["Joni Mitchell", "Tom Waits", "Bonnie Raitt", "Norah Jones",
        "Aimee Mann", "Suzanne Vega"],
    "Take A Picture": ["Margot & the Nuclear So and So's", "Bright Eyes", "Iron & Wine",
        "Sufjan Stevens"],
},

# ─── Jazz / Fusion ──────────────────────────────────────────────────────
"jazz": {
    "Bill Evans": ["Keith Jarrett", "Brad Mehldau", "Herbie Hancock", "Chick Corea",
        "Tord Gustavsen", "Fred Hersch", "Paul Bley", "McCoy Tyner", "Vince Guaraldi"],
    "Bill Evans Trio": ["Bill Evans", "Tord Gustavsen Trio", "Esbjörn Svensson Trio",
        "The Bad Plus", "Brad Mehldau Trio", "Vijay Iyer Trio", "Avishai Cohen Trio"],
    "Bill Evans, Jim Hall": ["Bill Evans", "Jim Hall", "Jimmy Raney", "Joe Pass",
        "Wes Montgomery", "Ed Bickert"],
    "Bill Laurance": ["Snarky Puppy", "Michael League", "Cory Henry", "Jacob Collier",
        "Robert Glasper", "GoGo Penguin"],
    "Bill Laurance & Michael League": ["Bill Laurance", "Snarky Puppy", "Becca Stevens",
        "Michelle Willis", "Cory Henry"],
    "Brian Culbertson": ["Boney James", "Norman Brown", "Peter White", "Eric Marienthal",
        "Dave Koz", "Kirk Whalum"],
    "Charles Mingus": ["John Coltrane", "Eric Dolphy", "Charles Lloyd", "Jaco Pastorius",
        "Miles Davis", "Roland Kirk", "Don Cherry"],
    "Charlie Haden & Pat Metheny": ["Pat Metheny", "Charlie Haden", "Keith Jarrett",
        "Quartet West", "Egberto Gismonti", "Jan Garbarek"],
    "Diana Krall": ["Norah Jones", "Madeleine Peyroux", "Stacey Kent", "Jane Monheit",
        "Karrin Allyson", "Tierney Sutton", "Roberta Gambarini"],
    "Eddie Higgins": ["Tommy Flanagan", "Hank Jones", "Cedar Walton", "Kenny Barron",
        "Junior Mance", "Bill Charlap"],
    "Emil Brandqvist Trio": ["Tord Gustavsen Trio", "Esbjörn Svensson Trio",
        "Marcin Wasilewski Trio", "Helge Lien Trio", "Phronesis", "GoGo Penguin"],
    "Enrico Pieranunzi": ["Stefano Bollani", "Brad Mehldau", "Bill Evans",
        "Marcin Wasilewski", "Tord Gustavsen", "Fred Hersch"],
    "Eric Dolphy": ["Charles Mingus", "John Coltrane", "Ornette Coleman", "Andrew Hill",
        "Don Cherry", "Booker Little"],
    "Esjbjorn Svensson Trio": ["Tord Gustavsen Trio", "GoGo Penguin", "The Bad Plus",
        "Phronesis", "Helge Lien Trio", "Marcin Wasilewski Trio"],
    "Great Jazz Trio": ["Hank Jones", "Tommy Flanagan", "Wynton Kelly Trio",
        "Ron Carter", "Tony Williams"],
    "Hiromi": ["Hiromi Uehara", "Chick Corea", "Esperanza Spalding", "Kamasi Washington",
        "Brad Mehldau", "Robert Glasper", "Jacob Collier", "Tigran Hamasyan"],
    "Hiromi Uehara": ["Hiromi", "Chick Corea", "Brad Mehldau", "Tigran Hamasyan",
        "Esperanza Spalding", "Robert Glasper", "Kamasi Washington"],
    "Incognito": ["Brand New Heavies", "Jamiroquai", "Galliano", "Light of the World",
        "Down to the Bone", "Snarky Puppy"],
    "Indigo Jam Unit": ["Quasimode", "Soil & Pimp Sessions", "Robert Glasper",
        "Jose James", "Cory Henry"],
    "Jaco Pastorius": ["Weather Report", "Marcus Miller", "Stanley Clarke",
        "Victor Wooten", "John Patitucci", "Hadrien Feraud"],
    "Joshua Redman": ["Branford Marsalis", "Chris Potter", "Mark Turner", "Joe Lovano",
        "Brad Mehldau", "Wayne Shorter"],
    "Kamasi Washington": ["Robert Glasper", "Thundercat", "Flying Lotus", "Esperanza Spalding",
        "Christian Scott", "Shabaka Hutchings"],
    "Keith Jarrett": ["Bill Evans", "Brad Mehldau", "Chick Corea", "Tord Gustavsen",
        "Fred Hersch", "Paul Bley", "ECM Records"],
    "Sonny Rollins": ["John Coltrane", "Stan Getz", "Dexter Gordon", "Charlie Parker",
        "Joe Henderson", "Ornette Coleman"],
    "Steve Kuhn": ["Tommy Flanagan", "Hank Jones", "Bill Evans", "Cedar Walton",
        "Joe Lovano"],
    "The Bad Plus": ["Esbjörn Svensson Trio", "Phronesis", "GoGo Penguin", "Vijay Iyer Trio",
        "Brad Mehldau Trio"],
    "the great jazz trio": ["Great Jazz Trio", "Hank Jones", "Tommy Flanagan", "Wynton Kelly Trio"],
    "Avishai Cohen": ["Esbjörn Svensson Trio", "Tigran Hamasyan", "Tord Gustavsen Trio",
        "Brad Mehldau", "Anouar Brahem"],
    "Helge Lien Trio & Tore Brunborg": ["Tord Gustavsen Trio", "Esbjörn Svensson Trio",
        "Mathias Eick", "Bobo Stenson", "ECM Nordic"],
    "jizue": ["Indigo Jam Unit", "Quasimode", "fox capture plan", "Schroeder-Headz",
        "GoGo Penguin"],
    "Tingvall Trio-Pax": ["Tord Gustavsen Trio", "Esbjörn Svensson Trio", "Helge Lien Trio",
        "Marcin Wasilewski Trio"],
},

# ─── Healing / New Age — major piano figures ───────────────────────────
"healing": {
    "George Winston": ["Yanni", "kitaro", "Liz Story", "Phillip Glass", "Suzanne Ciani",
        "Vince Guaraldi", "Paul Cardall", "David Lanz", "Kevin Kern"],
    "Yiruma": ["Kevin Kern", "Joe Hisaishi", "Yuki Kajiura", "Akira Kosemura",
        "Ludovico Einaudi", "Olafur Arnalds", "Brian Crain", "Helen Jane Long"],
    "Kevin Kern": ["Yiruma", "George Winston", "David Lanz", "Jim Brickman",
        "Brian Crain", "Phil Coulter", "Akira Kosemura"],
    "Yanni": ["kitaro", "Vangelis", "John Tesh", "David Lanz", "Mannheim Steamroller",
        "Two Steps from Hell", "Adiemus"],
    "kitaro": ["Yanni", "Vangelis", "Tangerine Dream", "Klaus Schulze", "Deuter",
        "Karunesh", "Kazu Matsui"],
    "Akira Kosemura": ["Olafur Arnalds", "Nils Frahm", "Hauschka", "Joep Beving",
        "Library Tapes", "Poppy Ackroyd", "Sofiane Pamart", "Dustin O'Halloran"],
    "Ryuichi Sakamoto": ["Olafur Arnalds", "Nils Frahm", "Yellow Magic Orchestra",
        "Haruomi Hosono", "Joe Hisaishi", "Akira Kosemura", "Hauschka", "Max Richter"],
    "sakamoto ryuichi": ["Ryuichi Sakamoto", "Olafur Arnalds", "Nils Frahm",
        "Yellow Magic Orchestra", "Haruomi Hosono", "Joe Hisaishi"],
    "Maksim Mrvica": ["Lang Lang", "David Garrett", "Lindsey Stirling", "2Cellos",
        "André Rieu", "Joe Hisaishi"],
    "Library Tapes": ["Akira Kosemura", "Olafur Arnalds", "Nils Frahm", "Joep Beving",
        "Goldmund", "Sylvain Chauveau"],
    "Poppy Ackroyd": ["Olafur Arnalds", "Hauschka", "Nils Frahm", "Akira Kosemura",
        "Hammock", "A Winged Victory for the Sullen"],
    "Sofiane Pamart": ["Olafur Arnalds", "Nils Frahm", "Akira Kosemura", "Joep Beving",
        "Lambert", "Chilly Gonzales"],
    "Anoice": ["World's End Girlfriend", "Akira Kosemura", "Eluvium",
        "Stars of the Lid", "Hammock", "Mono"],
    "Aukai": ["Olafur Arnalds", "Nils Frahm", "Hammock", "Goldmund", "Joep Beving"],
    "Balmorhea": ["Stars of the Lid", "Goldmund", "Olafur Arnalds", "Sigur Rós",
        "Mono", "Explosions in the Sky"],
    "Two Steps From Hell": ["Audiomachine", "Thomas Bergersen", "Hans Zimmer",
        "Immediate Music", "Future World Music", "X-Ray Dog"],
    "Jim Brickman": ["Kevin Kern", "Yiruma", "George Winston", "David Lanz",
        "John Tesh", "Phillip Keveren"],
    "Joe Hisaishi": ["Yuki Kajiura", "Yoko Shimomura", "Ryuichi Sakamoto", "Yiruma",
        "Akira Kosemura", "Olafur Arnalds"],
    "Druid": ["Loreena McKennitt", "Enya", "Clannad", "Karunesh", "Deuter",
        "Llewellyn"],
    "Karunesh": ["Deuter", "Anugama", "Llewellyn", "Kitaro", "Niall", "Stephen Rhodes"],
    "Nujabes": ["DJ OKAWARI", "DJ Krush", "Force of Nature", "Shing02", "Uyama Hiroto",
        "Fat Jon", "Shibuya-Kei"],
    "DJ OKAWARI": ["Nujabes", "DJ Krush", "Force of Nature", "Shing02",
        "Uyama Hiroto", "Daishi Dance"],
},

# ─── Metal — power, symphonic, melodeath, prog, JP ─────────────────────
"metal": {
    "Helloween": ["Gamma Ray", "Edguy", "Stratovarius", "Sonata Arctica", "Avantasia",
        "Blind Guardian", "Iron Savior", "Kai Hansen"],
    "Blind Guardian": ["Helloween", "Iced Earth", "Demons & Wizards", "Avantasia",
        "Kamelot", "Symphony X", "Rhapsody of Fire"],
    "Gamma Ray": ["Helloween", "Iron Savior", "Edguy", "Primal Fear", "Stratovarius",
        "Masterplan"],
    "Avantasia": ["Edguy", "Tobias Sammet", "Kamelot", "Helloween", "Blind Guardian",
        "Ayreon"],
    "Kamelot": ["Symphony X", "Epica", "Avantasia", "Pagan's Mind", "Vanishing Point",
        "Seventh Wonder"],
    "Sonata Arctica": ["Stratovarius", "Nightwish", "Children of Bodom", "Power Quest",
        "Ensiferum", "Norther"],
    "Edguy": ["Avantasia", "Helloween", "Gamma Ray", "Iron Savior", "Stratovarius"],
    "DragonForce": ["Powerwolf", "Dragonland", "Power Quest", "Sonata Arctica",
        "Stratovarius"],
    "Powerwolf": ["Sabaton", "Battle Beast", "Hammerfall", "Brainstorm", "Twilight Force"],
    "Primal Fear": ["Judas Priest", "Iron Savior", "Helloween", "Gamma Ray", "Sinner"],
    "Rhapsody Of Fire": ["Luca Turilli's Rhapsody", "Fairyland", "Twilight Force",
        "Pathfinder", "Ancient Bards"],
    "Twilight Force": ["Gloryhammer", "Powerwolf", "Rhapsody of Fire", "Pathfinder",
        "Victorius"],
    "Gloryhammer": ["Alestorm", "Twilight Force", "Powerwolf", "Wind Rose",
        "Beast in Black"],
    "Beast in Black": ["Battle Beast", "Powerwolf", "Sabaton", "Brothers of Metal",
        "Frozen Crown"],
    "Frozen Crown": ["Battle Beast", "Beast in Black", "Powerwolf", "Crystal Viper",
        "Burning Witches"],
    "Nightwish": ["Within Temptation", "Epica", "After Forever", "Tarja", "Sirenia",
        "Delain", "Lacuna Coil", "Xandria"],
    "Within Temptation": ["Nightwish", "Epica", "After Forever", "Delain", "Lacuna Coil",
        "Sirenia", "Xandria"],
    "Epica": ["Within Temptation", "Nightwish", "After Forever", "Kamelot", "ReVamp",
        "Delain"],
    "Lacuna Coil": ["Within Temptation", "Nightwish", "Evanescence", "After Forever",
        "Sirenia"],
    "After Forever": ["Within Temptation", "Nightwish", "Epica", "ReVamp", "Lacuna Coil"],
    "Therion": ["Septicflesh", "Fleshgod Apocalypse", "Haggard", "Equilibrium",
        "Nightwish (early)"],
    "Lacrimosa": ["Tristania", "Theatre of Tragedy", "Within Temptation (early)",
        "The Sins of Thy Beloved", "Nox Arcana"],
    "Haggard": ["Therion", "Septicflesh", "Equilibrium", "Eluveitie",
        "Cradle of Filth (operatic)"],
    "Amorphis": ["Insomnium", "Sentenced", "Swallow the Sun", "Moonsorrow", "Wintersun"],
    "Dark Tranquillity": ["In Flames", "At the Gates", "Soilwork", "Hypocrisy",
        "Insomnium"],
    "Children of Bodom": ["Norther", "Kalmah", "Wintersun", "Sonata Arctica",
        "Ensiferum"],
    "Behemoth": ["Belphegor", "Marduk", "Watain", "Vader", "Decapitated"],
    "Arch Enemy": ["Carcass", "In Flames", "Soilwork", "Dark Tranquillity",
        "Eluveitie", "The Agonist"],
    "In Flames": ["Dark Tranquillity", "At the Gates", "Soilwork", "Insomnium", "Carcass"],
    "At The Gates": ["In Flames", "Carcass", "Dissection", "Dark Tranquillity",
        "Edge of Sanity"],
    "Ensiferum": ["Wintersun", "Equilibrium", "Eluveitie", "Turisas",
        "Korpiklaani", "Moonsorrow"],
    "Eluveitie": ["Ensiferum", "Wintersun", "Korpiklaani", "Suidakra", "Heidevolk"],
    "Insomnium": ["Amorphis", "Omnium Gatherum", "Be'lakor", "Swallow the Sun", "Wolfheart"],
    "Emperor": ["Burzum", "Mayhem", "Darkthrone", "Immortal", "Enslaved", "Satyricon"],
    "Equilibrium": ["Eluveitie", "Ensiferum", "Wintersun", "Korpiklaani", "Tyr"],
    "Ihsahn": ["Emperor", "Enslaved", "Borknagar", "Solefald", "Ulver (early)"],
    "Moonsorrow": ["Wintersun", "Falkenbach", "Ensiferum", "Borknagar", "Primordial"],
    "Sigh": ["Arcturus", "Ulver", "Borknagar", "Vintersorg", "Solefald"],
    "Swallow the Sun": ["Insomnium", "Amorphis", "October Tide", "Be'lakor",
        "Wolfheart"],
    "Sentenced": ["Amorphis", "Tiamat", "Type O Negative", "Charon", "Katatonia"],
    "X JAPAN": ["Loudness", "Galneryus", "Dir En Grey", "MUCC", "Luna Sea",
        "Buck-Tick"],
    "Loudness": ["X JAPAN", "Anthem", "Vow Wow", "Earthshaker", "44 Magnum"],
    "Galneryus": ["Concerto Moon", "Light Bringer", "Saber Tiger", "Versailles",
        "Aldious"],
    "MALICE MIZER": ["Moi dix Mois", "Versailles", "Lareine", "Schwarz Stein", "Kagrra"],
    "Onmyo-Za": ["Galneryus", "MUCC", "Dir En Grey", "Versailles", "Kagrra"],
    "聖飢魔II": ["X JAPAN", "Anthem", "Loudness", "BOWWOW", "Vow Wow"],
    "LOVEBITES": ["Aldious", "Lovebites", "Mary's Blood", "Cyntia", "Frozen Crown"],
    "Dream Theater": ["Symphony X", "Pain of Salvation", "Liquid Tension Experiment",
        "Fates Warning", "Queensryche", "Ayreon"],
    "Opeth": ["Porcupine Tree", "Ne Obliviscaris", "Anathema", "Riverside",
        "Edge of Sanity", "Bloodbath"],
    "Persefone": ["Ne Obliviscaris", "Beyond Creation", "Wilderun", "Obscura",
        "Allegaeon"],
    "Symphony X": ["Dream Theater", "Kamelot", "Pagan's Mind", "Pain of Salvation",
        "Vanden Plas"],
    "SYMPHONY X": ["Dream Theater", "Kamelot", "Pagan's Mind", "Pain of Salvation",
        "Vanden Plas"],
    "Seventh Wonder": ["Symphony X", "Pain of Salvation", "Pagan's Mind", "Kamelot",
        "Threshold"],
    "Queensryche": ["Fates Warning", "Dream Theater", "Iron Maiden", "Crimson Glory",
        "Sanctuary"],
    "Evergrey": ["Pyramaze", "Pagan's Mind", "Threshold", "Vanden Plas",
        "Pain of Salvation"],
    "Leprous": ["Caligula's Horse", "Haken", "Riverside", "Soen", "Pain of Salvation"],
    "Megadeth": ["Metallica", "Slayer", "Anthrax", "Testament", "Annihilator"],
    "Slayer": ["Metallica", "Megadeth", "Anthrax", "Exodus", "Testament", "Sodom"],
    "Judas Priest": ["Iron Maiden", "Saxon", "Accept", "Halford", "Manowar", "Dio"],
    "Guns N' Roses": ["Aerosmith", "Skid Row", "Mötley Crüe", "Velvet Revolver",
        "Slash"],
},

# ─── Progressive — UK symphonic, RIO, Med, Nordic, Canterbury ──────────
"progressive": {
    "Genesis": ["Yes", "King Crimson", "Pink Floyd", "Marillion", "IQ", "Pendragon",
        "Gentle Giant", "Camel"],
    "Marillion": ["Genesis", "IQ", "Pendragon", "Pallas", "Galahad", "Mostly Autumn",
        "Big Big Train"],
    "Big Big Train": ["Genesis", "IQ", "Marillion", "Pallas", "Mostly Autumn",
        "Pendragon", "Tangent", "Frost*"],
    "IO Earth": ["Big Big Train", "Mostly Autumn", "IQ", "Pendragon", "Marillion"],
    "Pendragon": ["Marillion", "IQ", "Galahad", "Pallas", "Arena", "Mostly Autumn"],
    "Pallas": ["Marillion", "IQ", "Pendragon", "Galahad", "Arena", "Twelfth Night"],
    "Mike Oldfield": ["Tangerine Dream", "Vangelis", "Jean-Michel Jarre",
        "Steve Hillage", "Klaus Schulze"],
    "Jon Anderson": ["Yes", "Anderson Bruford Wakeman Howe", "Vangelis",
        "Steve Howe", "Rick Wakeman"],
    "Galahad": ["IQ", "Marillion", "Pendragon", "Pallas", "Arena"],
    "The Pineapple Thief": ["Porcupine Tree", "Riverside", "Steven Wilson", "Anathema",
        "Lunatic Soul", "Soen"],
    "Subsignal": ["Marillion", "Riverside", "Anathema", "RPWL", "Sieges Even"],
    "Premiata Forneria Marconi": ["Banco del Mutuo Soccorso", "Le Orme", "Area",
        "New Trolls", "Quella Vecchia Locanda"],
    "Il Balletto Di Bronzo": ["Museo Rosenbach", "Goblin", "Biglietto per l'Inferno",
        "Semiramis", "Quella Vecchia Locanda"],
    "Magma": ["Univers Zero", "Present", "Art Zoyd", "Heldon", "Henry Cow"],
    "ART BEARS": ["Henry Cow", "News from Babel", "Aksak Maboul", "Fred Frith",
        "Etron Fou Leloublan"],
    "Popol Vuh": ["Tangerine Dream", "Klaus Schulze", "Ash Ra Tempel", "Cluster",
        "Neu!"],
    "Kansas": ["Styx", "Boston", "Yes (US influence)", "Spock's Beard", "Glass Hammer"],
    "Pattern-Seeking Animals": ["Spock's Beard", "Big Big Train", "The Tangent",
        "Mostly Autumn", "Frost*"],
    "Thank You Scientist": ["The Mars Volta", "Coheed and Cambria", "Ne Obliviscaris",
        "Haken"],
    "Moon Safari": ["Big Big Train", "Beardfish", "The Flower Kings", "Spock's Beard",
        "The Tangent"],
    "Isildurs Bane": ["Univers Zero", "Sleepytime Gorilla Museum", "After Crying",
        "Ange"],
    "iamthemorning": ["Anathema", "The Gathering", "Wovenhand", "Trespassers William",
        "Steven Wilson"],
    "Rick Wakeman": ["Yes", "Jon Anderson", "Patrick Moraz", "Keith Emerson",
        "Tony Banks"],
    "Jordan Rudess": ["Dream Theater", "Liquid Tension Experiment", "Kevin Moore",
        "Derek Sherinian"],
},

# ─── Celt / Fantasy / Violin ───────────────────────────────────────────
"celt": {
    "Loreena McKennitt": ["Enya", "Clannad", "Lisa Gerrard", "Méav", "Sarah Brightman",
        "Anúna", "Hayley Westenra"],
    "Adrian von Ziegler": ["Antti Martikainen", "Erang", "Brunuhville", "Peter Crowley",
        "Derek & Brandon Fiechter", "BrunuhVille"],
    "Antti Martikainen": ["Adrian von Ziegler", "Two Steps from Hell", "Audiomachine",
        "Derek Fiechter"],
    "Austin Wintory": ["Joe Hisaishi", "Nobuo Uematsu", "Yasunori Mitsuda", "Jeremy Soule"],
    "Caprice": ["Estampie", "Qntal", "Mediaeval Baebes", "Faun", "Trobar de Morte"],
    "Celtic Woman": ["Celtic Thunder", "Loreena McKennitt", "Hayley Westenra",
        "Sarah Brightman", "Méav"],
    "Celtic Thunder": ["Celtic Woman", "Riverdance", "Lord of the Dance",
        "The Irish Tenors"],
    "Lindsey Stirling": ["Taylor Davis", "2Cellos", "Vanessa-Mae", "Bond",
        "Jenny Oaks Baker", "David Garrett"],
    "Two Steps From Hell": ["Audiomachine", "Thomas Bergersen", "Hans Zimmer",
        "Immediate Music", "Future World Music"],
    "2Cellos": ["Apocalyptica", "Bond", "Lindsey Stirling", "David Garrett",
        "Vanessa-Mae"],
    "Lisa Gerrard": ["Dead Can Dance", "Loreena McKennitt", "This Mortal Coil",
        "Cocteau Twins", "Brendan Perry"],
    "The Chieftains": ["Altan", "Clannad", "Planxty", "Bothy Band", "Solas",
        "Capercaillie"],
    "Faun": ["Omnia", "Eluveitie", "Heilung", "Wardruna", "Trobar de Morte",
        "Estampie"],
    "Mediaeval Baebes": ["Anúna", "Trobar de Morte", "Estampie", "Qntal", "Faun"],
    "Estampie": ["Mediaeval Baebes", "Qntal", "Helium Vola", "Faun", "Sequentia"],
    "Yo-Yo Ma": ["Mstislav Rostropovich", "Jacqueline du Pré", "János Starker",
        "Steven Isserlis"],
    "Hilary Hahn": ["Anne-Sophie Mutter", "Janine Jansen", "Joshua Bell",
        "Itzhak Perlman", "Maxim Vengerov"],
    "Joshua Bell": ["Anne-Sophie Mutter", "Hilary Hahn", "Itzhak Perlman",
        "Janine Jansen", "Sarah Chang"],
    "Tina Guo": ["2Cellos", "Apocalyptica", "Yo-Yo Ma", "Lindsey Stirling"],
    "Rodrigo y Gabriela": ["Estas Tonne", "Strunz & Farah", "Jesse Cook",
        "Ottmar Liebert", "Acoustic Alchemy"],
    "Adrian Legg": ["Acoustic Alchemy", "Tommy Emmanuel", "Ottmar Liebert"],
    "David Arkenstone": ["Diane Arkenstone", "Karunesh", "Govi", "Robert Mirabal"],
    "Leah": ["Lindsey Stirling", "Cellardoor", "Battlelore", "Tarja",
        "Karliene"],
    "Gloaming": ["Lúnasa", "Solas", "Andy Irvine", "Iarla Ó Lionáird", "Martin Hayes"],
    "David Garrett": ["Lindsey Stirling", "Vanessa-Mae", "Maxim Vengerov", "2Cellos",
        "Bond"],
},

# ─── Pop-Rock / Crossover ──────────────────────────────────────────────
"pop-rock": {
    "Andrea Bocelli": ["Sarah Brightman", "Josh Groban", "Il Divo", "Il Volo",
        "Russell Watson"],
    "Sigur Rós": ["Mum", "Jonsi", "Olafur Arnalds", "Mogwai", "Explosions in the Sky",
        "Stars of the Lid", "Hammock", "Mono"],
    "Foo Fighters": ["Nirvana", "Queens of the Stone Age", "Stone Sour", "Audioslave",
        "Pearl Jam"],
    "Hans Zimmer": ["John Williams", "James Newton Howard", "Howard Shore",
        "Ramin Djawadi", "Two Steps from Hell"],
    "Hans Zimmer - Interstellar": ["Hans Zimmer", "Howard Shore", "John Williams",
        "Thomas Newman", "Alexandre Desplat"],
    "Bon Jovi": ["Def Leppard", "Aerosmith", "Whitesnake", "Mr. Big", "Journey",
        "Foreigner"],
    "Bon Jovi 2010": ["Bon Jovi", "Def Leppard", "Aerosmith", "Journey"],
    "Deep Purple": ["Black Sabbath", "Rainbow", "Led Zeppelin", "Uriah Heep",
        "Whitesnake", "Dio"],
    "Death Cab For Cutie": ["The Postal Service", "Iron & Wine", "Bright Eyes",
        "The Shins", "Wilco"],
    "Death Cab for Cutie": ["The Postal Service", "Iron & Wine", "Bright Eyes",
        "The Shins", "Wilco"],
    "Eminem": ["Dr. Dre", "50 Cent", "D12", "Royce da 5'9\"", "Kendrick Lamar"],
    "Dua Lipa": ["Ariana Grande", "Doja Cat", "The Weeknd", "Olivia Rodrigo",
        "Charli XCX"],
    "Steely Dan": ["Donald Fagen", "Walter Becker", "Toto", "Boz Scaggs",
        "Doobie Brothers"],
    "Tarja": ["Within Temptation", "Nightwish", "Epica", "Sirenia", "Delain"],
    "The Zombies": ["The Kinks", "Beach Boys", "The Hollies", "The Beatles",
        "The Yardbirds"],
    "Vienna Boys' Choir": ["King's College Choir", "Tölzer Knabenchor", "Libera",
        "Vocal Ensemble", "Anúna"],
    "Voces8": ["The King's Singers", "VOCES8 Foundation", "Tenebrae Choir",
        "Stile Antico", "The Tallis Scholars"],
    "Jamiroquai": ["Brand New Heavies", "Incognito", "Stevie Wonder",
        "Maroon 5", "Pharrell Williams"],
    "Paco de Lucía": ["Vicente Amigo", "Tomatito", "Strunz & Farah",
        "Pepe Habichuela", "Rodrigo y Gabriela"],
    "Priscilla Ahn": ["Norah Jones", "Diana Krall", "Madeleine Peyroux",
        "Stacey Kent", "Lily & Madeleine"],
},

# ─── JPOP — major artists ──────────────────────────────────────────────
"jpop": {
    "B'z": ["GLAY", "L'Arc en Ciel", "TM Network", "Mr. Children", "Spitz"],
    "BUMP OF CHICKEN": ["RADWIMPS", "Mr. Children", "ASIAN KUNG-FU GENERATION",
        "Spitz", "Sambomaster"],
    "GLAY": ["L'Arc en Ciel", "B'z", "JUDY AND MARY", "Luna Sea", "X JAPAN"],
    "L'Arc en Ciel": ["GLAY", "Luna Sea", "X JAPAN", "Dir En Grey", "Buck-Tick"],
    "L’Arc en Ciel": ["L'Arc en Ciel", "GLAY", "Luna Sea", "X JAPAN", "Buck-Tick"],
    "Official髭男dism": ["King Gnu", "Vaundy", "back number", "Mrs. GREEN APPLE",
        "Saucy Dog"],
    "Aimer": ["Yuki Kajiura", "Lia", "Kalafina", "Eir Aoi", "ReoNa", "Sayuri"],
    "Ado": ["Yuki Kajiura", "Aimer", "Yoasobi", "Reol", "majiko"],
    "Yoasobi": ["Eve", "Vaundy", "Ado", "Reol", "Mafumafu", "Ayase"],
    "ReoNa": ["Aimer", "Lisa", "Eir Aoi", "Sayuri", "Yuki Kajiura"],
    "Garnet Crow": ["B'z", "ZARD", "Mr. Children", "WANDS", "Field of View"],
    "kokia": ["Yuki Kajiura", "Akiko Shikata", "Hatsune Yura", "Eri Itoh"],
    "Mili": ["Sound Horizon", "Linked Horizon", "Penguin Research", "Lyn",
        "Akiko Shikata"],
    "Rurutia": ["Yuki Kajiura", "Akiko Shikata", "Origa", "Ryuko Tsushima"],
    "Suara": ["Yui Sakakibara", "Lia", "Kotoko", "ave;new feat. Sakura"],
    "Uru": ["Aimer", "Milet", "DAOKO", "Eir Aoi"],
    "fhána": ["nano.RIPE", "ROUND TABLE feat. Nino", "petit milady", "OxT", "TrySail"],
    "eufonius": ["Lia", "I've Sound", "ave;new", "fhána", "Mami Kawada"],
    "ORIGA": ["Yuki Kajiura", "Mell", "Kalafina", "Loituma", "Le Mystère des Voix Bulgares"],
    "Reol": ["Eve", "Yoasobi", "Mafumafu", "DAOKO", "Sou"],
    "Ali project": ["Yuki Kajiura", "Akiko Shikata", "Sound Horizon", "Mell",
        "Hisako Ishikawa"],
    "Gackt": ["Hyde", "MALICE MIZER", "Versailles", "KAMIJO", "Kiyoharu"],
    "Kalafina": ["Yuki Kajiura", "FictionJunction", "Aimer", "Mell", "Lia"],
    "Yuki Kajiura": ["Kalafina", "FictionJunction", "Aimer", "Mell", "Eri Itoh", "ORIGA"],
    "fripSide": ["I've Sound", "MELL", "Kotoko", "Eir Aoi", "Lia"],
    "MELL": ["I've Sound", "Kotoko", "Lia", "fripSide", "Eir Aoi"],
    "Lia": ["I've Sound", "Lia*Cinema", "Riya", "veil", "Eufonius"],
    "ずっと真夜中でいいのに。": ["Yoasobi", "Eve", "DAOKO", "Vaundy", "Ado", "Reol"],
    "あたらよ": ["yama", "Mafumafu", "yorushika", "Ano", "Mrs. GREEN APPLE"],
    "Sound Horizon": ["Linked Horizon", "Mili", "Akiko Shikata", "Hisako Ishikawa",
        "Yuki Kajiura"],
    "wowaka": ["Hatsune Miku", "DECO*27", "Mafumafu", "Hitorie", "Buruburu"],
    "Yousei Teikoku 3.0": ["Ali project", "Kanon Wakeshima", "Akiko Shikata",
        "Hisako Ishikawa"],
    "Wolpis Carter": ["Eve", "Mafumafu", "Soraru", "Sou", "VALSHE"],
},

# ─── Anime — composers and OST series ─────────────────────────────────
"anime": {
    "Code Geass Sound Collection": ["Akeboshi", "FLOW", "ALI PROJECT", "Sunset Swish",
        "Kotoko"],
    "Hunter X Hunter": ["Yoshihisa Hirano", "Yasuharu Takanashi", "Kohei Tanaka"],
    "violet evergarden": ["Evan Call", "Yuki Kajiura", "Joe Hisaishi", "Hiroyuki Sawano"],
    "Charlotte Original Soundtrack": ["Anant-Garde Eyes", "Yanagi Nagi",
        "Aoi Tada", "Lia"],
    "Frieren Beyond Journey's End Original Soundtrack": ["Evan Call", "Joe Hisaishi",
        "Yuki Kajiura", "Hiroyuki Sawano"],
    "Studio Ghibli": ["Joe Hisaishi", "Mamoru Fujisawa", "Sōta Fujimori",
        "Akira Senju"],
    "Elfen Lied Original Soundtrack": ["Kondoh Kayo", "Yuki Kajiura", "Hisako Ishikawa"],
    "KOTOKO": ["I've Sound", "MELL", "Lia", "fripSide", "Eir Aoi"],
    "高橋洋子": ["Lia", "MELL", "Kotoko", "Eir Aoi", "Suara"],
},

# ─── Game — composers and OST series ──────────────────────────────────
"game": {
    "Final Fantasy": ["Nobuo Uematsu", "Masashi Hamauzu", "Yoko Shimomura",
        "Yasunori Mitsuda", "Hitoshi Sakimoto"],
    "Dragon Quest": ["Koichi Sugiyama", "Nobuo Uematsu", "Yasunori Mitsuda",
        "Hitoshi Sakimoto"],
    "Falcom Sound Team jdk collection": ["Yuzo Koshiro", "Mitsuda Yasunori",
        "Falcom Sound Team", "Joe Hisaishi"],
    "Yoko Shimomura": ["Nobuo Uematsu", "Yasunori Mitsuda", "Joe Hisaishi", "Masashi Hamauzu"],
    "Yu-peng Chen": ["Yasunori Mitsuda", "Yoko Shimomura", "Joe Hisaishi", "Hans Zimmer"],
    "Kingdom Hearts": ["Yoko Shimomura", "Nobuo Uematsu", "Hikaru Utada",
        "Joe Hisaishi"],
    "Chrono": ["Yasunori Mitsuda", "Nobuo Uematsu", "Joe Hisaishi", "Yoko Shimomura"],
    "NieR": ["Keiichi Okabe", "MONACA", "Joe Hisaishi", "Hiroyuki Sawano",
        "Eir Aoi"],
    "Undertale": ["Toby Fox", "Camellia", "Lena Raine", "Disasterpeace"],
    "Castlevania": ["Michiru Yamane", "Konami Kukeiha Club", "Akira Yamaoka",
        "Yamane Michiru"],
    "Christopher Tin": ["Hans Zimmer", "Howard Shore", "James Horner", "John Williams"],
    "ENDER LILIES": ["Mili", "Hans Zimmer (dark fantasy)", "NieR composers",
        "DARK SOULS Motoi Sakuraba"],
    "Bravely Default OST": ["Revo", "Linked Horizon", "Yasunori Mitsuda",
        "Yoko Shimomura"],
    "Xenoblade Original Soundtrack": ["ACE+", "Manami Kiyota", "Yoko Shimomura",
        "Yasunori Mitsuda"],
    "OCTOPATH TRAVELER Original Soundtrack": ["Yasunori Nishiki", "Yasunori Mitsuda",
        "Joe Hisaishi"],
    "Monster Hunter": ["Capcom Sound Team", "Yuko Komiyama", "Akihiko Narita"],
},

# ─── Indies — JP underground ──────────────────────────────────────────
"indies": {
    "Imperial Circus Dead Decadence": ["Unlucky Morpheus", "Asriel", "Dragon Guardian",
        "Cross Vein", "Yousei Teikoku"],
    "Asriel": ["Imperial Circus Dead Decadence", "Marchen Station", "Dragon Guardian"],
    "Dragon Guardian": ["Asriel", "Imperial Circus Dead Decadence", "Unlucky Morpheus"],
    "Unlucky Morpheus": ["Imperial Circus Dead Decadence", "Light Bringer",
        "Cross Vein", "Aldious"],
    "TEARS OF TRAGEDY": ["Aldious", "Lovebites", "Versailles", "Mary's Blood",
        "Frozen Crown"],
    "CROSS VEIN": ["Aldious", "Unlucky Morpheus", "Mary's Blood", "Versailles"],
    "Aura Noctis": ["Theodor Bastard", "Lacrimosa", "Trobar de Morte",
        "Ataraxia", "Faith and the Muse"],
    "Theodor Bastard": ["Aura Noctis", "Faith and the Muse", "Lebanon Hanover",
        "Heilung", "Wardruna"],
    "TAMUSIC": ["Touhou Strings Quartet", "Yuki Akabane", "C-CLAYS",
        "MN-logic24"],
    "love solfege": ["Yuki Kajiura", "Akiko Shikata", "Yousei Teikoku",
        "Ali project", "ChouCho"],
},

# ─── Nature — field recording ─────────────────────────────────────────
"nature": {
    "Gordon Hempton": ["Bernie Krause", "Chris Watson", "Jana Winderen",
        "Francisco López", "Andreas Bick"],
    "Hennie Bekker": ["Dan Gibson's Solitudes", "Karunesh", "Llewellyn", "Mike Rowland"],
    "Dan Gibson's Solitudes": ["Hennie Bekker", "Karunesh", "Anugama", "Llewellyn"],
},

}
