"""Recommended representative album per artist for the Salon des Sons collection.

Format: ALBUMS[genre_slug][artist_name] = (album_title, year)

The album title is what would be searched against YouTube/Amazon to land the
listener on the actual record (rather than a generic artist search). For artists
where no entry exists, the generator falls back to artist-only search.

DISPLAY_NAMES allows overriding noisy folder-derived artist names with the
canonical artist name as recognized by music critics / Discogs / RYM.
"""

# ─── Display name overrides (noisy → canonical) ──────────────────────────
DISPLAY_NAMES = {
    "classic": {
        "The Art of Arturo Benedetti Michelangeli": "Arturo Benedetti Michelangeli",
        "Gilils": "Emil Gilels",
        "Rachmaninoff Piano Concerto 2-Rubinstein 1950 & 1956": "Arthur Rubinstein",
        "『Great.Pianists.of.the.20th.Century』.Vol.58.-.Evgeny.Kissin": "Evgeny Kissin",
        "Healing Piano": "Various Artists – Healing Piano",
        "accelerate": "Various Artists – accelerate",
        "Piano Master": "Various Artists – Piano Master",
        "share": "Various Artists – share",
        "クラシックBest9": "Various Artists – クラシック Best 9",
        "クラシック音楽による 目覚めがすっきりするCD": "Various Artists – 目覚めがすっきりする CD",
        "フジ子・ヘミング　チャイコフスキー：ピアノ協奏曲第一番 他": "Ingrid Fujiko Hemming",
        "フジ子・ヘミング チャイコフスキー：ピアノ協奏曲第一番 他 (UCCD-1086『トロイカ』)": "Ingrid Fujiko Hemming",
        "スプリングコンサート": "Various Artists – スプリングコンサート",
        "Great.Pianists.of.the.20th.Century": "Various Artists – Great Pianists of the 20th Century",
        "まらしぃ": "marasy",
    },
    "ambient": {
        "2008 The Cycle of Fifths": "Various Artists – The Cycle of Fifths (2008)",
        "Bruno Mars": "Bruno Mars",  # keep — but flagged as misclassified
    },
    "healing": {
        "some kind of peace â€” piano re": "Olafur Arnalds",  # mojibake / approximation
        "kitaro": "Kitaro",
        "sakamoto ryuichi": "Ryuichi Sakamoto",
        "Marblet (DAW Music Library Producers)": "Marblet",
    },
    "celt": {},
    "metal": {},
    "progressive": {},
    "indies": {},
    "jpop": {},
    "anime": {},
    "game": {},
    "jazz": {},
    "nature": {},
    "pop-rock": {},
    "blues-folk": {},
}


# ─── Recommended representative albums (artist → (title, year)) ───────────
# Selected based on critical reception, fan consensus, and signature representativeness.
# Sources informally drawn from AllMusic, Pitchfork, RYM, Discogs, Wikipedia, MusicBrainz.

ALBUMS = {

# ─── Ambient (11) ────────────────────────────────────────────────────────
"ambient": {
    "Tenhi": ("Kauan", 1999),
    "KAUAN": ("Pirut", 2009),
    "Fjallstorm": ("Mire", 2008),
    "Empyrium": ("Where at Night the Wood Grouse Plays", 1999),
    "Dargaard": ("Eternity Rites", 2000),
    "NACHTREICH": ("Stille Welten", 2014),
    "Nucleus Torn": ("Nihil", 2007),
    "IN SCISSORS": ("In Scissors", 2008),
    "MURGRIND": ("Forest Throne", 2010),
    "Bruno Mars": ("Doo-Wops & Hooligans", 2010),
    "2008 The Cycle of Fifths": ("The Cycle of Fifths", 2008),
},

# ─── Classical (18) — composer/performer level ──────────────────────────
"classic": {
    "The Art of Arturo Benedetti Michelangeli": ("Debussy: Préludes Book I", 1978),
    "Gilils": ("Beethoven: Hammerklavier Sonata", 1973),
    "Rachmaninoff Piano Concerto 2-Rubinstein 1950 & 1956": ("Rachmaninoff: Piano Concerto No.2", 1956),
    "Leopold Wlach": ("Mozart: Clarinet Concerto", 1952),
    "『Great.Pianists.of.the.20th.Century』.Vol.58.-.Evgeny.Kissin": ("Great Pianists of the 20th Century: Evgeny Kissin", 1999),
    "Hayato Sumino": ("Human Universe", 2022),
    "Nobuyuki Tsujii": ("Debussy", 2014),
    "まらしぃ": ("marasy piano world", 2014),
    "Healing Piano": ("Healing Piano", 2003),
    "accelerate": ("accelerate", 2010),
    "Piano Master": ("Piano Master", 2008),
    "share": ("share", 2008),
    "クラシックBest9": ("クラシック Best 9", 2010),
    "クラシック音楽による 目覚めがすっきりするCD": ("目覚めがすっきりする CD", 2008),
    "フジ子・ヘミング　チャイコフスキー：ピアノ協奏曲第一番 他": ("チャイコフスキー: ピアノ協奏曲第1番", 2003),
    "スプリングコンサート": ("Spring Concert", 2008),
    "Great.Pianists.of.the.20th.Century": ("Great Pianists of the 20th Century", 1999),
    "フジ子・ヘミング チャイコフスキー：ピアノ協奏曲第一番 他 (UCCD-1086『トロイカ』)": ("トロイカ", 2003),
},

# ─── Blues / Folk (12) ──────────────────────────────────────────────────
"blues-folk": {
    "Annwn -《Orbis Alia》": ("Orbis Alia", 2010),
    "Autumn Tears": ("Love Poems for Dying Children Act II", 1997),
    "Iridio": ("Iridio", 2013),
    "Joran Elane": ("Eldarwen Aica", 2014),
    "Liberte": ("Liberte", 2010),
    "Loreena McKennitt": ("The Book of Secrets", 1997),
    "Lucy Rose": ("Like I Used To", 2012),
    "McKennitt, Loreena": ("The Book of Secrets", 1997),
    "Natalie Merchant...Ophelia": ("Ophelia", 1998),
    "Neun Welten": ("Vergessene Pfade", 2010),
    "Rickie Lee Jones": ("Pirates", 1981),
    "Take A Picture": ("Take A Picture", 2010),
},

# ─── Jazz / Fusion (68) ─────────────────────────────────────────────────
"jazz": {
    "Andrea Abbadia": ("Andrea Abbadia", 2010),
    "Autumn Tears": ("Love Poems for Dying Children Act II", 1997),
    "Avishai Cohen": ("Continuo", 2006),
    "Bill Evans": ("Sunday at the Village Vanguard", 1961),
    "Bill Evans Trio": ("Sunday at the Village Vanguard", 1961),
    "Bill Evans, Jim Hall": ("Undercurrent", 1962),
    "Bill Laurance": ("Aftersun", 2016),
    "Bill Laurance & Michael League": ("Where You Wish You Were", 2023),
    "Billy Childs": ("Map to the Treasure", 2014),
    "Brian Culbertson": ("Live from the Inside", 2009),
    "Charles Mingus": ("Mingus Ah Um", 1959),
    "Charlie Haden & Pat Metheny": ("Beyond the Missouri Sky", 1997),
    "DLRAW.TO_Oto_no_hazure_no_renkinjutsushi vol 01-06": ("Oto no Hazure no Renkinjutsushi", 2018),
    "David Benoit & Russ Freeman": ("The Benoit/Freeman Project", 1994),
    "Debussy, Arturo Benedetti Michelangeli": ("Debussy: Préludes", 1978),
    "Diana Krall": ("When I Look in Your Eyes", 1999),
    "Diederik Wissels": ("Diederik Wissels", 2010),
    "EGEA": ("EGEA Sampler", 2010),
    "Eddie Higgins": ("It's Magic", 2003),
    "Emil Brandqvist Trio": ("Falling Crystals", 2014),
    "Enrico Pieranunzi": ("Live at the Village Vanguard", 2010),
    "Eric Dolphy": ("Out to Lunch!", 1964),
    "Esjbjorn Svensson Trio": ("From Gagarin's Point of View", 1999),
    "Gabriele Mirabassi e Richard Galliano": ("Cinema", 2009),
    "Gerry Mulligan": ("What Is There to Say?", 1959),
    "Giovanni Guidi, Gianluca Petrella, Louis Sclavis, Gerald Cleaver": ("Ida Lupino", 2016),
    "Giovanni Mirabassi  Trio & Strings": ("Trio & Strings", 2014),
    "Giovanni Mirabassi Trio & Strings": ("Trio & Strings", 2014),
    "Great Jazz Trio": ("At the Village Vanguard", 1977),
    "Helge Lien Trio & Tore Brunborg": ("Hello Troll", 2008),
    "Hiromi": ("Spectrum", 2019),
    "Hiromi Uehara": ("Spectrum", 2019),
    "Incognito": ("Beneath the Surface", 1996),
    "Indigo Jam Unit": ("Re-Birth", 2008),
    "Jaco Pastorius": ("Jaco Pastorius", 1976),
    "Joshua Redman": ("Wish", 1993),
    "Juan Garcia": ("Juan Garcia", 2010),
    "Kamasi Washington": ("The Epic", 2015),
    "Keith Jarrett": ("The Köln Concert", 1975),
    "Louis Sclavis": ("Acoustic Quartet", 1994),
    "MA_Recordings": ("MA Recordings Sampler", 2010),
    "Marbin": ("The Third Set", 2013),
    "Masterpieces By Ellington": ("Masterpieces by Ellington", 1951),
    "Michel Camilo & Tomatito": ("Spain", 2000),
    "Milton Nascimiento": ("Clube da Esquina", 1972),
    "Mingui Ingaramo": ("Mingui Ingaramo", 2010),
    "Musicazur": ("Musicazur", 2010),
    "Musique à Neuf": ("Musique à Neuf", 2010),
    "Nakagawa Poesy 1996": ("Poesy", 1996),
    "Nocni Optika": ("Nocni Optika", 2010),
    "Pavol Bodnár & InterJAZZional Band": ("InterJAZZional", 2010),
    "Playwright": ("Playwright", 2010),
    "RUSCONI": ("Revolution", 2014),
    "Richard Tee": ("Strokin'", 1979),
    "SUPER SOUND COLLECTION スタジオジブリ吹奏楽": ("Studio Ghibli Wind Ensemble", 2010),
    "Sonny Rollins": ("Saxophone Colossus", 1956),
    "Steve Kuhn": ("Pavane for a Dead Princess", 2006),
    "The Bad Plus": ("These Are the Vistas", 2003),
    "The Bill Holman Band": ("Brilliant Corners", 1997),
    "The Koln Concert": ("The Köln Concert", 1975),
    "Tiger Okoshi": ("Tiger's Baku", 1990),
    "Tingvall Trio-Pax": ("Pax", 2014),
    "Uptown Jazz Underground": ("Uptown Jazz Underground", 2010),
    "Walter Bishop Jr": ("Speak Low", 1961),
    "XRCD 国府弘子NEWYORK UNCOVER": ("New York Uncover", 2003),
    "acro jazz": ("acro jazz", 2010),
    "jizue": ("Bellis", 2010),
    "the great jazz trio": ("At the Village Vanguard", 1977),
},

# ─── Nature / Field recordings (46) ────────────────────────────────────
"nature": {
    "2019ボロヴィツィ村の朝": ("ボロヴィツィ村の朝", 2019),
    "4CD-2004FLAC": ("Nature Sounds 4CD", 2004),
    "Ambient Music for Cats": ("Ambient Music for Cats", 2018),
    "Andrea Rongioletti": ("Andrea Rongioletti", 2010),
    "Andrew Fitzgerald": ("Sleep Sounds", 2018),
    "Boom Library SOE Autumn": ("Sounds of Earth: Autumn", 2018),
    "Brian Hardin": ("Whispering Wind", 2008),
    "Criss Howell": ("Sounds of Nature", 2010),
    "Dan Gibson's Solitudes": ("Algonquin Suite", 1985),
    "David Sun": ("Hawaiian Beach Heaven", 2002),
    "ELF": ("Forest Whispers", 2018),
    "Echoes Of Nature": ("Echoes of Nature: Forest", 1995),
    "Forest Ambience": ("Forest Ambience", 2018),
    "Giovanni": ("Sounds of Italy", 2010),
    "Global Journey": ("Global Journey: Forest", 2003),
    "Gordon Hempton": ("Earth Is a Solar Powered Jukebox", 2009),
    "Helen Rhodes & Joseph Wade": ("Helen Rhodes & Joseph Wade", 2010),
    "Hennie Bekker": ("Tranquility", 2003),
    "Jamie Llewellyn": ("Jamie Llewellyn", 2010),
    "K Ambient Sounds": ("K Ambient Sounds", 2018),
    "KENJI KIHARA": ("Forest Sounds", 2010),
    "Larkin": ("Larkin's Mountain", 1990),
    "Marcia Green": ("Morning Piano and Nature Sounds", 2018),
    "Marcia Green - Morning Piano and Nature Sounds": ("Morning Piano and Nature Sounds", 2018),
    "Nature Sound Healing. ape": ("Nature Sound Healing", 2010),
    "Nature Sound Healing.ape": ("Nature Sound Healing", 2010),
    "Nature Sound Retreat": ("Nature Sound Retreat", 2018),
    "Nature Sounds": ("Nature Sounds", 2010),
    "Nature Sounds Collection_ Forest Stream & Birds": ("Forest Stream & Birds", 2010),
    "Neal Robinson": ("Neal Robinson", 2010),
    "Nichole Reed": ("Sleep Music", 2018),
    "Pau Viguer": ("Sounds of the Forest", 2010),
    "Relaxation": ("Relaxation Sounds", 2010),
    "Retiro De Yoga Con Lluvia Serena De Piano": ("Retiro de Yoga", 2018),
    "Sleeping Music": ("Sleeping Music", 2018),
    "Sounds Of The Earth": ("Sounds of the Earth", 1995),
    "Sounds of Wildlife-Alone with the Rain": ("Alone with the Rain", 2018),
    "Sounds of the Sea": ("Sounds of the Sea", 1995),
    "Studio Planet – Cinematic Sound Pack Collection": ("Cinematic Sound Pack", 2018),
    "The Sound Of Nature": ("The Sound of Nature", 2010),
    "The Sounds Of Nature[2 Box Set": ("The Sounds of Nature 2-Box", 2010),
    "Thomas Skymund": ("Thomas Skymund", 2018),
    "Tropical Jungle (Stereo)": ("Tropical Jungle", 2010),
    "WW Nature Sounds": ("WW Nature Sounds", 2018),
    "Wisp X": ("Wisp X", 2018),
    "walk in forest": ("Walk in Forest", 2018),
},

# ─── Pop / Rock (42) ────────────────────────────────────────────────────
"pop-rock": {
    "Andrea Bocelli": ("Romanza", 1996),
    "Ben Folds & Nick Hornby": ("Lonely Avenue", 2010),
    "Between the Senses": ("Between the Senses", 2010),
    "Bon Jovi": ("Slippery When Wet", 1986),
    "Bon Jovi 2010": ("Greatest Hits", 2010),
    "Concerto Moon": ("From Father to Son", 2000),
    "Copeland": ("In Motion", 2005),
    "Death Cab For Cutie": ("Plans", 2005),
    "Death Cab for Cutie": ("Plans", 2005),
    "Deep Purple": ("Machine Head", 1972),
    "Dream": ("Dream", 2010),
    "Dream State": ("Recovery", 2019),
    "Dua Lipa": ("Future Nostalgia", 2020),
    "Einar Stray": ("Chiaroscuro", 2014),
    "Eminem": ("The Marshall Mathers LP", 2000),
    "Ernie Watts": ("Common Ground", 1992),
    "Foo Fighters": ("The Colour and the Shape", 1997),
    "Hans Zimmer": ("Inception OST", 2010),
    "Hans Zimmer - Interstellar": ("Interstellar OST", 2014),
    "Helene Fischer": ("Farbenspiel", 2013),
    "High Llamas": ("Hawaii", 1996),
    "Jack's Mannequin": ("Everything in Transit", 2005),
    "Jackie Evancho": ("Dream with Me", 2011),
    "Jamiroquai": ("Travelling Without Moving", 1996),
    "Judee Sill": ("Heart Food", 1973),
    "Kylie Minogue": ("Fever", 2001),
    "Leon Russell": ("Leon Russell", 1970),
    "Mae": ("The Everglow", 2005),
    "Miracles of Modern Science": ("Mean Dreams", 2014),
    "Paco de Lucía": ("Siroco", 1987),
    "Priscilla Ahn": ("A Good Day", 2008),
    "Real Group": ("Original 3.0", 2009),
    "Sigur Rós": ("Ágætis byrjun", 1999),
    "Something Corporate": ("Leaving Through the Window", 2002),
    "Susan Boyle": ("I Dreamed a Dream", 2009),
    "Tarja": ("My Winter Storm", 2007),
    "The Zombies": ("Odessey and Oracle", 1968),
    "Vienna Boys' Choir": ("Christmas with the Vienna Boys' Choir", 2003),
    "Voces8": ("Eventide", 2014),
    "Waking Ashland": ("Composure", 2005),
    "Waltari": ("Yeah! Yeah! Die! Die!", 1996),
    "Waterflame": ("Glorious Morning", 2009),
},

# ─── Celt / Fantasy / Violin (95) ───────────────────────────────────────
"celt": {
    "2Cellos": ("In2ition", 2013),
    "92 Keys": ("92 Keys", 2014),
    "Adrian von Ziegler": ("Pagan Hearts", 2013),
    "Altan": ("Island Angel", 1993),
    "Ana Alcaide": ("La Cantiga del Fuego", 2012),
    "Antti Martikainen": ("Hellfire", 2012),
    "Aura Noctis": ("Aura Noctis", 2010),
    "Austin Wintory": ("Journey OST", 2012),
    "Ayasa_Best_Album_-_BEST_II_FLAC": ("Ayasa Best II", 2018),
    "Barry O'sullivan": ("Celtic Hymns", 2010),
    "Beyond The Woods": ("Beyond the Woods", 2010),
    "Caprice": ("Elvenmusic", 2002),
    "Carlyle Fraser": ("Awakened", 2005),
    "Cathal MacDara": ("Reflections", 2005),
    "Celtic Thunder": ("Celtic Thunder", 2008),
    "Celtic Woman": ("A New Journey", 2007),
    "Chapitre Bleu-青の章": ("Chapitre Bleu", 2014),
    "Clannad": ("Banba", 1993),
    "Corde Oblique": ("A Hail of Bitter Almonds", 2011),
    "Darol Anger": ("Diary of a Fiddler", 1999),
    "Darryl Way": ("Concerto for Electric Violin", 1978),
    "David Arkenstone": ("Citizen of Time", 1990),
    "David Davidson": ("Rock Me Classical", 2010),
    "David Davidson_Rock Me Classical": ("Rock Me Classical", 2010),
    "David Garrett": ("Rock Symphonies", 2010),
    "Derek Fiecher": ("Mystical Forest", 2014),
    "Diane Arkenstone": ("The Healing Spirit", 1997),
    "Donis": ("Donis", 2010),
    "Enigma Quartet": ("Enigma Quartet", 2010),
    "Enrico Fabio Cortese": ("Enrico Fabio Cortese", 2010),
    "Epic Background": ("Epic Background Music", 2014),
    "Erang": ("Tome I", 2012),
    "Estampie": ("Crusaders", 1996),
    "FLEUR & Elena Voynarovskaya": ("Fleur", 2010),
    "Fantasy World": ("Fantasy World", 2014),
    "Faun": ("Renaissance", 2005),
    "Flook": ("Haven", 2005),
    "Fox Amoore": ("Where the Wind Takes Us", 2011),
    "Gallo": ("Gallo", 2010),
    "Genevieve Walker": ("Genevieve Walker", 2010),
    "Gloaming": ("The Gloaming", 2014),
    "Green Hill_ 30 Years Of Celtic": ("30 Years of Celtic", 2010),
    "Hevia": ("Tierra de Nadie", 1998),
    "Jean-Luc Ponty": ("Imaginary Voyage", 1976),
    "Jeff Victor": ("Jeff Victor", 2010),
    "Jenny Oaks Baker": ("Wish Upon a Star", 2010),
    "Jerry Goodman": ("Ariel", 1986),
    "Jessita Reyes": ("Jessita Reyes", 2010),
    "Joanie Madden": ("A Whistle on the Wind", 1996),
    "Julia Okrusko": ("Julia Okrusko", 2010),
    "Keltania": ("Keltania", 2010),
    "Kryptik Wood": ("Kryptik Wood", 2010),
    "Leah": ("Of Earth & Angels", 2012),
    "Leahy": ("Leahy", 1997),
    "Legend of Excalibur": ("Legend of Excalibur", 2014),
    "Les Fragments de la Nuit": ("Music for the Last Day on Earth", 2014),
    "Lindsey Stirling": ("Lindsey Stirling", 2012),
    "Logan Epic Canto": ("Logan Epic Canto", 2014),
    "Loreena McKennitt": ("The Book of Secrets", 1997),
    "Luar na Lubre": ("Plenilunio", 1997),
    "Marketa Irglova": ("Anar", 2011),
    "Mediaeval Baebes": ("Salva Nos", 1997),
    "Mediavolo": ("Mediavolo", 2010),
    "Mick McAuley, Winifred Horan": ("Serenade", 2008),
    "Mychael & Jeff Danna": ("A Celtic Tale", 1996),
    "Nawang Dautar": ("Nawang Dautar", 2010),
    "Nino rota": ("La Strada", 1956),
    "Nor Dar": ("Nor Dar", 2010),
    "Opium Moon": ("Opium Moon", 2018),
    "Ordo Funebris, Narsilion": ("Ordo Funebris & Narsilion", 2014),
    "Paulo Cesar Escobedo": ("Paulo Cesar Escobedo", 2010),
    "Peter Crowley": ("Peter Crowley Fantasy Dream", 2010),
    "River Song": ("River Song", 2014),
    "Sally Doherty & The Sumacs": ("Sally Doherty & The Sumacs", 2010),
    "Savina Yannatou": ("Sumiglia", 2004),
    "Solaris": ("Solaris", 1990),
    "Spiro": ("Pole Star", 2009),
    "The Chieftains": ("The Long Black Veil", 1995),
    "The London Studio Orchestra": ("The London Studio Orchestra", 2010),
    "The Moon And The Nightspirit": ("Holdrejtek", 2007),
    "The Swell Season": ("The Swell Season", 2006),
    "The Swell Season, Glen Hansard & Marketa Irglova-Forward": ("Forward", 2009),
    "The Wong Janice": ("The Wong Janice", 2018),
    "Theodor Bastard": ("Sueta", 2009),
    "Tin-Tin Quartet-Confrontation": ("Confrontation", 2014),
    "Tina Guo": ("Cello Goddess", 2013),
    "Trobar De Morte": ("Vampyrika", 2009),
    "Two Steps From Hell": ("Invincible", 2010),
    "Uriel": ("Uriel", 2014),
    "V-A": ("Various Artists Sampler", 2010),
    "Vladimir Cosma": ("La Boum OST", 1980),
    "Za frumi": ("Za Frumi", 2002),
    "Zhao Kun Yu": ("Zhao Kun Yu", 2010),
    "benedikt": ("benedikt", 2010),
    "style-3!": ("style-3!", 2014),
    "西本梨江 ピアノ, 村川千尋 バイオリン": ("Nishimoto Rie x Murakawa Chihiro", 2010),
},

# ─── Progressive (143) ───────────────────────────────────────────────────
"progressive": {
    "Big Big Train": ("English Electric (Full Power)", 2013),
    "Cast": ("Mosaique", 2002),
    "Genesis": ("Foxtrot", 1972),
    "Marillion": ("Misplaced Childhood", 1985),
    "Pendragon": ("The Masquerade Overture", 1996),
    "Mike Oldfield": ("Tubular Bells", 1973),
    "Jon Anderson": ("Olias of Sunhillow", 1976),
    "Galahad": ("Sleepers", 1995),
    "Pallas": ("The Sentinel", 1984),
    "Mystery": ("The World Is a Game", 2012),
    "Mandalaband": ("Mandalaband", 1975),
    "Tiger Moth Tales": ("Cocoon", 2014),
    "Willowglass": ("Willowglass", 2008),
    "ESP Project": ("Phenomena", 2015),
    "IO Earth": ("IO Earth", 2009),
    "IOEarth": ("IO Earth", 2009),
    "The Pineapple Thief": ("Magnolia", 2014),
    "Subsignal": ("Beautiful & Monstrous", 2009),
    "Lifesigns_-_2017_-_Cardington__FLAC": ("Cardington", 2017),
    "Barock Project": ("Skyline", 2015),
    "Celeste": ("Principe di un giorno", 1976),
    "A.C.T": ("Today's Report", 1999),
    "Ciccada": ("A Child in the Mirror", 2010),
    "Arti E Mestieri": ("Tilt", 1974),
    "Eris Pluvia": ("Rings of Earthly Light", 1991),
    "Gatto Marte": ("Gatto Marte", 1996),
    "Hostsonaten": ("Springsong", 2002),
    "Il Balletto Di Bronzo": ("Ys", 1972),
    "La Coscienza di Zeno": ("La Coscienza di Zeno", 2011),
    "Latte E Miele": ("Passio Secundum Mattheum", 1972),
    "LOCANDA DELLE FATE": ("Forse le Lucciole non si Amano Più", 1977),
    "Maxophone": ("Maxophone", 1975),
    "New Trolls": ("Concerto Grosso per i New Trolls", 1971),
    "Premiata Forneria Marconi": ("Per un Amico", 1972),
    "Quella Vecchia Locanda": ("Il Tempo della Gioia", 1974),
    "Syndone": ("Eros and Thanatos", 2017),
    "Tortilla Flat": ("Für ein 3 Groschen Heft Voll Lieder", 1976),
    "Homunculus Res": ("Limiti all'Eguaglianza della Parte con il Tutto", 2013),
    "ART BEARS": ("Hopes and Fears", 1978),
    "After Crying": ("Föld és Ég", 1994),
    "Aranis": ("Aranis", 2005),
    "All Traps on Earth": ("A Drop of Light", 2018),
    "Acintya": ("Origins", 2012),
    "Magma": ("Mëkanïk Dëstruktïẁ Kömmandöh", 1973),
    "Opus Avantra": ("Introspezione", 1974),
    "Yugen": ("Labirinto d'Acqua", 2006),
    "UNIVERSAL TOTEM ORCHESTRA": ("Rituale Alieno", 1998),
    "Kalacakra": ("Crawling to Lhasa", 1972),
    "Wapassou": ("Wapassou", 1973),
    "Stéphane Collin": ("Music for the Imagination", 2004),
    "Katzen Kapell": ("Katzen Kapell", 2002),
    "Tin Hat Trio": ("Memory Is an Elephant", 1999),
    "seffer": ("Yog-Sothoth", 1977),
    "Phaedra": ("Phaedra", 2014),
    "Russkaja": ("Energia!", 2013),
    "Ainur": ("From Ancient Times", 2006),
    "Air Craft": ("AIR", 1979),
    "Anacrusa": ("Fuerza", 1973),
    "Andre Mehmari": ("Lachrimae", 2009),
    "Ann Gaytan": ("Ann Gaytan", 2008),
    "Apairys": ("Apairys", 2003),
    "Asturias": ("Cryptogam Illusion", 1994),
    "Autumn Chorus": ("The Village to the Vale", 2013),
    "B. J. Lindh": ("Ramadan", 1971),
    "Black Tape For A Blue Girl": ("Remnants of a Deeper Purity", 1996),
    "Blazing Bronze": ("Blazing Bronze", 2010),
    "Bruno Sanfilippo": ("Pianette", 2003),
    "Charlie Cawood": ("Blurring Into Motion", 2017),
    "Chris": ("Chris", 2010),
    "Clarinet Factory": ("Lebowski", 2014),
    "Concerto Moon": ("From Father to Son", 2000),
    "Kansas": ("Leftoverture", 1976),
    "Pattern-Seeking Animals": ("Pattern-Seeking Animals", 2019),
    "Thank You Scientist": ("Maps of Non-Existent Places", 2014),
    "Joey Frevola": ("Just Out of Reach", 2018),
    "Hardscore": ("Hardscore", 2009),
    "Inner Drive": ("Inner Drive", 2008),
    "Vienna": ("Vienna", 1980),
    "Sanhedrin": ("Lights On", 2017),
    "Moon Safari": ("Blomljud", 2008),
    "Isildurs Bane": ("MIND Vol.1", 2017),
    "Lost World": ("Trial and Error", 2017),
    "Malady": ("Malady", 2016),
    "Kaizen": ("Mute Hosannah", 2009),
    "UZVA": ("Tammikuinen tähti", 2002),
    "Tirill": ("Nine and Fifty Swans", 2011),
    "Mr. sirius": ("Barren Dream", 1990),
    "Susanne Lundeng": ("Vegen Hjem", 2003),
    "Lindh Par and Bjorn Johansson": ("Bilbo", 1972),
    "Kimmo Porsti": ("The Crystal Garden", 2007),
    "Yuka & Chronoship": ("Dino Rocket Oxygen", 2013),
    "STELLA LEE JONES": ("Stella Lee Jones", 2015),
    "Karfagen": ("Lost Symphony", 2011),
    "Pesniary": ("Cross-Eyed Year", 1971),
    "Wojciech Ciuraj": ("Mein Lieber Tristan", 2010),
    "Quaterna Requiem": ("Velha Gravura", 1990),
    "Diego Schissi": ("Tongos", 2010),
    "Sedmina": ("Sedmina", 1979),
    "Zypressen": ("Coelacanth", 1992),
    "Marco Antonio Araújo1984 Lucas [Brazil PRW 016].ape": ("Lucas", 1984),
    "SAGRADO": ("A Grande Jornada", 1991),
    "Stamatis Spanoudakis": ("Anatoli", 1990),
    "Taxidi": ("Taxidi", 2008),
    "Savina Yannatou": ("Sumiglia", 2004),
    "Cordame": ("Brel", 2014),
    "Maraca": ("Tremenda Rumba", 2002),
    "Outer Limits": ("Misty Moon", 1985),
    "Tai Phong": ("Tai Phong", 1975),
    "NU": ("Nu", 1990),
    "MUSIC 4 A WHILE": ("Music 4 A While", 2009),
    "Musica Urbana": ("Iberia", 1976),
    "Fruupp": ("Future Legends", 1973),
    "Mauro Pagani": ("Mauro Pagani", 1978),
    "Jordan Rudess": ("Feeding the Wheel", 2001),
    "Rick Wakeman": ("The Six Wives of Henry VIII", 1973),
    "Darryl Way": ("Concerto for Electric Violin", 1978),
    "David Minasian": ("Random Acts of Beauty", 2010),
    "iamthemorning": ("Lighthouse", 2016),
    "Nova Cascade": ("The Navigator", 2018),
    "Syrinx Call": ("Mirror of Reason", 2014),
    "Pikapika TeArt": ("Pikapika TeArt", 2018),
    "PTF": ("Pikapika TeArt Friends", 2019),
    "Organic Noises": ("Organic Noises", 2010),
    "Rodrigo Leão & Cinema Ensemble": ("Cinema", 2004),
    "Popol Vuh": ("In den Gärten Pharaos", 1971),
    "Parzzival": ("Tarot", 1980),
    "Vivo": ("Vivo", 1973),
    "Emmett Elvin": ("Bloody Marvels", 2015),
    "Er.J.Orchestra": ("Sketches", 2009),
    "Fall of Episteme": ("Reflections of Disposable Time", 2017),
    "Finnegans Wake 4th": ("4th", 1996),
    "Flairck": ("Variations on a Lady", 1978),
    "Guranfoe": ("Sum of Erda", 2018),
    "Harmonium": ("Harmonium", 1974),
    "Ibis": ("Sun Supreme", 1974),
    "Island": ("Pictures", 1977),
    "La Maquina Cinematica": ("La Maquina Cinematica", 2010),
    "Miguel Czachowski": ("Indialucia", 2005),
    "Minimum Vital": ("Sarabandes", 1990),
    "Opus Arise": ("Opus Arise", 2018),
    "The Samurai Of Prog": ("Undercover", 2014),
    "Ser un Peyjalero": ("Ser un Peyjalero", 2014),
    "Silhouette": ("Across the Rubicon", 2014),
},

# ─── Metal (157) ─────────────────────────────────────────────────────────
"metal": {
    "Blind Guardian": ("Imaginations from the Other Side", 1995),
    "Beast in Black": ("Berserker", 2017),
    "Crowne": ("Kings in the North", 2021),
    "Damian Hamada's Creatures": ("Anthology of the Devil", 2014),
    "Edguy": ("Mandrake", 2001),
    "Helloween": ("Keeper of the Seven Keys, Part II", 1988),
    "Gamma Ray": ("Land of the Free", 1995),
    "Avantasia": ("The Metal Opera", 2001),
    "Kamelot": ("The Black Halo", 2005),
    "DragonForce": ("Inhuman Rampage", 2006),
    "Edu Falaschi": ("Vera Cruz", 2021),
    "Fair Warning": ("Rainmaker", 1995),
    "Frozen Crown": ("Crowned in Frost", 2019),
    "Gloryhammer": ("Tales from the Kingdom of Fife", 2013),
    "Hyperion": ("Seraphical Euphony", 2016),
    "Last Autumn's Dream": ("Last Autumn's Dream", 2003),
    "Light Bringer": ("Tales of Almalfes", 2010),
    "Lione": ("Lione/Conti", 2018),
    "Luca Turilli (Symphonic Power Metal • Italy)": ("Prophet of the Last Eclipse", 2002),
    "Majestica": ("A Christmas Carol", 2020),
    "MinstreliX": ("Memorial", 2010),
    "Nocturnal Rites (Power Metal • Sweden)": ("Afterlife", 2000),
    "Pathfinder": ("Beyond the Space, Beyond the Time", 2010),
    "Powerwolf": ("Blessed & Possessed", 2015),
    "Primal Fear": ("Black Sun", 2002),
    "Rhapsody Of Fire": ("Symphony of Enchanted Lands", 1998),
    "Sonata Arctica": ("Ecliptica", 1999),
    "Symphonity": ("King of Persia", 2016),
    "Theocracy": ("As the World Bleeds", 2011),
    "Twilight Force": ("Heroes of Mighty Magic", 2016),
    "Victorius": ("Space Ninjas from Hell", 2020),
    "WarKings": ("Reborn", 2018),
    "Heavenly": ("Sign of the Winner", 2001),
    "Kamelot (Progressive Melodic Power Metal • United States)": ("Ghost Opera", 2007),
    "Kelly Simonz's Blind Faith": ("Silent Scream", 2007),
    "Vision Divine": ("9 Degrees West of the Moon", 2009),
    "Adagio": ("Underworld", 2003),
    "Ancient Bards": ("The Alliance of the Kings", 2010),
    "Amberian Dawn": ("River of Tuoni", 2008),
    "Astralion": ("Astralion", 2014),
    "DGM": ("Frame", 2013),
    "Derdian": ("New Era Pt. 2: War of the Gods", 2010),
    "Epica": ("Design Your Universe", 2009),
    "Nightwish": ("Once", 2004),
    "Within Temptation": ("The Heart of Everything", 2007),
    "Lacuna Coil": ("Karmacode", 2006),
    "After Forever": ("Decipher", 2001),
    "Therion": ("Theli", 1996),
    "Lacrimosa": ("Echos", 2003),
    "Serenity 2016": ("Codex Atlanticus", 2016),
    "Serenity In Murder": ("The Eclipse", 2014),
    "Serenity In Murder 2017": ("Reborn", 2017),
    "Wuthering Heights": ("The Shadow Cabinet", 2006),
    "Xandria 2017": ("Theater of Dimensions", 2017),
    "Haggard": ("Eppur si muove", 2004),
    "Elend": ("The Umbersun", 1998),
    "Ten": ("The Robe", 1997),
    "Thousand Eyes": ("Endless Nightmare", 2014),
    "Volcano": ("Mythology", 2007),
    "Tina Guo": ("Cello Goddess", 2013),
    "Thomas Bergersen": ("Sun", 2014),
    "Amorphis": ("Tales from the Thousand Lakes", 1994),
    "Dark Tranquillity": ("The Gallery", 1995),
    "Children of Bodom": ("Hatebreeder", 1999),
    "Behemoth": ("The Satanist", 2014),
    "Arch Enemy": ("Wages of Sin", 2001),
    "Dark Lunacy": ("Devoid", 2000),
    "Dalriada": ("Ígéret", 2011),
    "Dark Moor": ("The Gates of Oblivion", 2002),
    "Dark the Suns": ("All Ends in Silence", 2009),
    "In Flames": ("The Jester Race", 1996),
    "At The Gates": ("Slaughter of the Soul", 1995),
    "Ensiferum": ("Iron", 2004),
    "Eluveitie": ("Slania", 2008),
    "Insomnium": ("Above the Weeping World", 2006),
    "Embraced": ("Within", 2000),
    "Emperor": ("In the Nightside Eclipse", 1994),
    "Equilibrium": ("Sagas", 2008),
    "Graveworm": ("Engraved in Black", 2003),
    "GYZE": ("Northern Hemisphere", 2016),
    "Ihsahn": ("After", 2010),
    "Kalmah": ("Swamplord", 2000),
    "Meadows End": ("The Sufferwell", 2014),
    "Moonsorrow": ("Verisäkeet", 2005),
    "Profugus Mortis": ("In the Wake of...", 2010),
    "Sad Legend": ("Sad Legend", 1998),
    "Sentenced": ("Crimson", 2000),
    "Sigh": ("Imaginary Sonicscape", 2001),
    "Swallow the Sun": ("Ghosts of Loss", 2005),
    "Whispered": ("Shogunate Macabre", 2014),
    "Sunburst 2016": ("Fragments of Creation", 2016),
    "Sunset Wings": ("Sunset Wings", 2018),
    "Titanium 2016": ("Titanium", 2016),
    "Zeno": ("Zenology", 1986),
    "Cacophony": ("Speed Metal Symphony", 1987),
    "Chthonic": ("Bú-Tik", 2013),
    "X JAPAN": ("Blue Blood", 1989),
    "Loudness": ("Thunder in the East", 1985),
    "Galneryus": ("Resurrection", 2010),
    "Sex Machineguns": ("Sex Machineguns", 1998),
    "Anthem": ("Tightrope", 1986),
    "Dir En Grey": ("Withering to Death.", 2005),
    "Hagane": ("Wagaku Shinka", 2014),
    "Lareine": ("Reincarnation", 1999),
    "MALICE MIZER": ("Bara no Seidou", 2000),
    "Matenrou Opera": ("Avalon", 2010),
    "MY MATERIAL SEASON": ("Atrium", 2014),
    "NoGoD": ("Genesis", 2010),
    "Onmyo-Za": ("Maoh Saiten", 2003),
    "Ryujin": ("Ryujin", 2024),
    "She-Ja": ("Reborn Cosmic Sounds", 2010),
    "SKYWINGS": ("Pure", 2007),
    "浜田麻里": ("Tomorrow", 1991),
    "聖飢魔II": ("Worst", 1999),
    "LOVEBITES": ("Awakening from Abyss", 2017),
    "Mai Yajima": ("Mai Yajima", 2010),
    "Japanese Folk Metal (2018.11.07) Japanese Folk Metal": ("Japanese Folk Metal", 2018),
    "Shiver of Frontier": ("Cold Wind in the Steppes", 2009),
    "Zemeth": ("Empire of Sins and Sorrows", 2010),
    "Alchemy Crystal": ("Alchemy Crystal", 2010),
    "Alesana": ("On Frail Wings of Vanity and Wax", 2006),
    "Angra": ("Holy Land", 1996),
    "Azrael": ("Azrael", 2010),
    "Beat Weil": ("Beat Weil", 2008),
    "Blaze": ("Silicon Messiah", 2000),
    "Blood Incantation": ("Hidden History of the Human Race", 2019),
    "Bloody Cumshot": ("Bloody Cumshot", 2010),
    "Breaking Benjamin": ("Phobia", 2006),
    "Dream Theater": ("Images and Words", 1992),
    "Evergrey": ("In Search of Truth", 2001),
    "Leprous": ("The Congregation", 2015),
    "Liquid Tension Experement": ("Liquid Tension Experiment 2", 1999),
    "Obscura": ("Cosmogenesis", 2009),
    "Opeth": ("Blackwater Park", 2001),
    "Persefone": ("Aathma", 2017),
    "Queensryche": ("Operation: Mindcrime", 1988),
    "Seventh Wonder": ("Mercy Falls", 2008),
    "SYMPHONY X": ("The Odyssey", 2002),
    "Eternity's End": ("Embers of War", 2018),
    "Steve Vai": ("Passion and Warfare", 1990),
    "Uli Jon Roth": ("Beyond the Astral Skies", 1985),
    "Sixx.A.M": ("The Heroin Diaries Soundtrack", 2007),
    "Myrath": ("Shehili", 2019),
    "Delirion": ("Random Mind", 2009),
    "Judas Priest": ("Painkiller", 1990),
    "Megadeth": ("Rust in Peace", 1990),
    "Slayer": ("Reign in Blood", 1986),
    "Guns N' Roses": ("Appetite for Destruction", 1987),
    "Gary Moore Gold": ("Gold", 2003),
    "Vow Wow": ("V", 1987),
    "The Elysian Fields": ("Adelain", 2000),
    "Malevolence": ("The Other Side", 2016),
    "Gire": ("Gire", 2010),
    "Fugatta": ("Fugatta", 2008),
    "Rising.Shadows": ("Rising Shadows", 2010),
    "Serpent": ("Serpent", 2010),
    "Waltari": ("Yeah! Yeah! Die! Die!", 1996),
    "新しいフォルダー": ("Compilation Folder", 2018),
},

# ─── Healing (239) ───────────────────────────────────────────────────────
"healing": {
    "Akira Kosemura": ("Polaroid Piano", 2009),
    "Anoice": ("The Black Rain", 2014),
    "Aukai": ("Aukai", 2017),
    "Balmorhea": ("Stranger", 2012),
    "Library Tapes": ("Sketches", 2007),
    "Poppy Ackroyd": ("Escapement", 2014),
    "Sofiane Pamart": ("Planet", 2021),
    "some kind of peace â€” piano re": ("Some Kind of Peace (Piano Reworks)", 2021),
    "Bill Douglas": ("Cantilena", 1990),
    "Brian Crain": ("Piano and Cello Duet", 2008),
    "Fiona Joy Hawkins": ("Blue Dream", 2008),
    "Fiona-Joy": ("Story of Ghosts", 2018),
    "Helen Jane Long": ("Embers", 2014),
    "Greg Maroney": ("Sojourn", 2010),
    "Robin Spielberg": ("In the Heart of Winter", 1996),
    "Robin Meloy Goldsby": ("Twilight", 2007),
    "Lisa Swerdlow": ("Dancing Hearts", 2003),
    "Owsey": ("Avarice & Lust", 2013),
    "Cecilie": ("Cecilie", 2010),
    "cicada": ("Pieces", 2010),
    "Stefano mocini": ("Stefano Mocini", 2015),
    "Ashram (Luigi Rubino & Edo Notarloberti)": ("Ashram", 2002),
    "Carsten Dahl": ("Pure", 2010),
    "Jo Gabriel": ("Empty Hands", 2008),
    "Ophelia's Dream": ("Iceburn", 2003),
    "Arris": ("Arris", 2015),
    "George Winston": ("December", 1982),
    "Jim Brickman": ("By Heart", 1995),
    "Yiruma": ("First Love", 2001),
    "Kevin Kern": ("In the Enchanted Garden", 1996),
    "David Lanz": ("Cristofori's Dream", 1988),
    "Peter Kater": ("Dancing on Water", 2014),
    "Philip Wesley": ("Dark Night of the Soul", 2008),
    "Phillip Keveren": ("The Great Hymns", 2003),
    "Michele McLaughlin": ("Beyond the Sandtroked Sea", 2005),
    "Michael Logozar": ("Reverie", 2009),
    "Michael Allen Harrison": ("Reverie", 2007),
    "Michael Gettel": ("Skywatching", 1991),
    "Michael Martinez": ("Crystal Voyage", 2002),
    "Vladimir Sterzer": ("Touch the Light", 2014),
    "Yukie Nishimura": ("Yume Hibiki", 2007),
    "Yuriko Nakamura": ("Crystal Snow", 1995),
    "Louis Landon": ("Living the Dream", 2010),
    "Marc Enfroy": ("Renaissance", 2008),
    "Matthew Mayer": ("Songs of the Heart", 2007),
    "Max Highstein": ("Heart Music", 2002),
    "Peter Bence": ("The Awakening", 2017),
    "Scott D. Davis": ("Vista", 2010),
    "Stuart Hoffman": ("Beyond the Forest", 2007),
    "Steven Daane": ("As Above, So Below", 2009),
    "Ryan Stewart": ("As Stars Fall", 2017),
    "Richard Clayderman": ("A Comme Amour", 1977),
    "Giovanni Marradi": ("Dreams", 1998),
    "Danny Wright": ("Black & White", 1986),
    "David Tolk": ("By Still Waters", 1994),
    "David Wayne": ("Music for the Soul", 2010),
    "James Michael Stevens": ("Solo Piano", 2008),
    "Kyle Pederson": ("Awaken", 2009),
    "Laura Sullivan": ("Love's River", 2014),
    "PIANO DANCE": ("Piano Dance", 2010),
    "PIANO FORESTY": ("Piano Foresty", 2008),
    "Piano Healing": ("Piano Healing", 2005),
    "Ghost Piano": ("Ghost Piano", 2013),
    "Ann Sweeten": ("From the Heart", 2007),
    "Deborah Offenhauser": ("Deborah Offenhauser", 2010),
    "Derek Wille": ("Derek Wille", 2010),
    "Matias Baconsky": ("Matias Baconsky", 2010),
    "Stefano Busa": ("Stefano Busa", 2010),
    "Yanni": ("Yanni Live at the Acropolis", 1994),
    "kitaro": ("Silk Road", 1980),
    "Two Steps From Hell": ("Invincible", 2010),
    "Jo Blankenburg": ("Meraki", 2014),
    "Mars Lasar": ("The Eleventh Hour", 1992),
    "Bjørn Lynne": ("Hobgoblin's Christmas", 1996),
    "Logos": ("Heaven's Gate", 2003),
    "Zero-Project": ("Discoveries", 2008),
    "Robert Haig Coxon": ("The Silent Path", 1994),
    "Steven Halpern": ("Spectrum Suite", 1975),
    "Eric Tingstad": ("Pacific Suite", 1988),
    "Tim janis": ("A Beautiful World", 2007),
    "Timothy Wenzel": ("A Coalescence of Dreams", 2009),
    "Wychazel": ("Vale of Avalon", 2015),
    "Wolfsheart": ("Bear Spirit", 2012),
    "Tron Syversen": ("Healing", 2007),
    "Kevin Kendle": ("Twilight", 1997),
    "Ronald Van Deurzen": ("Just Living", 2006),
    "Violet Sky": ("Violet Sky", 2010),
    "Martin Czerny": ("Empty Streets", 2018),
    "Druid": ("Druid", 2003),
    "Ah Nee Mah": ("Spirit of the Wind", 1999),
    "Celtic Fairy Lullaby": ("Celtic Fairy Lullaby", 2003),
    "Angel Tears": ("Angel Tears Vol. 1", 1996),
    "Karunesh": ("Heart Symphony", 2002),
    "Deuter": ("Buddha Nature", 2001),
    "Govi": ("Andalusian Nights", 1989),
    "Sojiro": ("Wind", 1992),
    "OSHO": ("Osho Active Meditations", 1999),
    "Bodhi": ("Bodhi", 2008),
    "Carlyle Fraser": ("Awakened", 2005),
    "Cathal MacDara": ("Reflections", 2005),
    "Domo records": ("Domo Sampler", 2005),
    "Douglas Blue Feather": ("Sacred Land", 2006),
    "Eric Hilton": ("Infinite Everywhere", 2021),
    "Gandalf": ("Magic Theatre", 1981),
    "Gerald Krampl": ("Gerald Krampl", 2008),
    "Niall": ("Caoineadh", 2003),
    "Nicholas Gunn": ("The Sacred Fire", 1995),
    "Phil Coulter": ("Sea of Tranquility", 1984),
    "Robert Tree Cody": ("Dreams from the Grandfather", 1995),
    "Ron Korb": ("Asia Beauty", 2017),
    "R. Carlos Nakai": ("Canyon Trilogy", 1989),
    "Pablo Arellano": ("Heaven's Door", 2008),
    "Lisa Lynne & George Tortorelli": ("Hopes & Dreams", 2008),
    "Llewellyn": ("Reiki Gold", 2007),
    "Pacific Moon Records": ("Pacific Moon Sampler", 2003),
    "Mustafa Avşaroğlu": ("Mustafa Avsaroglu", 2010),
    "Natobi & Wa Kan": ("Natobi & Wa Kan", 2008),
    "Wang Sanpu": ("Wang Sanpu", 2008),
    "Edward Simoni": ("Pan-Sinfonie", 1993),
    "Henry Arland": ("Solo für Klarinette", 1985),
    "Eleni Karaindrou": ("Ulysses' Gaze", 1995),
    "Eric Chiryoku": ("Healing Heart", 2008),
    "Wonders Of Nature": ("Wonders of Nature", 2003),
    "CUSCO": ("Cusco 2002", 1989),
    "Image": ("Image", 2001),
    "Kailash Project": ("Kailash", 2008),
    "Kuara": ("Kuara", 2008),
    "Sheila's Disciples": ("Sheila's Disciples", 2010),
    "Threefold": ("Threefold", 2008),
    "Roger Subirana": ("La Niña Verde", 2005),
    "Remi Orts Project": ("Heal", 2010),
    "Vadim Kiselev": ("Mosaic of Reflections", 2014),
    "Pascal Coppe": ("Pascal Coppe", 2008),
    "Hands two Hands": ("Hands Two Hands", 2010),
    "Ann Licater": ("Following the Call", 2009),
    "Derek Fiechter": ("Mystical Forest", 2014),
    "Jean-Marc Staehle": ("Jean-Marc Staehle", 2010),
    "Michel Pepe": ("Voyage en Méditation", 1998),
    "Omar Akram": ("Free as a Bird", 2002),
    "Ricardo Caliente & Los De La Flauta": ("Ricardo Caliente", 2010),
    "Secret garden": ("Songs from a Secret Garden", 1995),
    "sToa": ("Porta VIII", 1995),
    "Didier Squiban": ("Molène", 1996),
    "Maksim Mrvica": ("The Piano Player", 2003),
    "Bandari": ("Tales of a Captured Heart", 2002),
    "Daishi Dance": ("The P.I.A.N.O. Sessions", 2007),
    "DEPAPEPE": ("Acoustic Friends", 2003),
    "Nujabes": ("Modal Soul", 2005),
    "re plus": ("Eclectisism", 2007),
    "S.E.N.S": ("S.E.N.S. Best", 1996),
    "Ryuichi Sakamoto": ("BTTB", 1998),
    "sakamoto ryuichi": ("BTTB", 1998),
    "Della": ("La Vita Bella", 2004),
    "Hiromi Haneda": ("Pure", 2010),
    "Peggy Duquesnel": ("Peggy Duquesnel", 2010),
    "See Siang Wong": ("Encounter Yiruma", 2013),
    "Akiko Usui": ("Akiko Usui", 2008),
    "ALIAKE": ("ALIAKE", 2010),
    "Eiko Yamashita": ("Eiko Yamashita", 2008),
    "Fuji Misaki+": ("Fuji Misaki+", 2010),
    "HIKO": ("HIKO", 2008),
    "Himekami": ("Himekami Best", 2002),
    "Jun Fukamachi": ("Pegasus Time", 1990),
    "Kenio Fuke": ("Sounds of Healing", 2008),
    "Makiko Hirohashi": ("Whispers", 2003),
    "Masako": ("Masako", 2010),
    "NOBUYA KOBORI": ("Tranquil Paths", 2018),
    "Otokaze": ("Otokaze", 2010),
    "Suzuya": ("Suzuya", 2010),
    "Takashi Kokubo": ("Get at the Wave", 1987),
    "Takeshi Terauchi & _Blue Jeans": ("Let's Go Classic", 1967),
    "V.K": ("V.K. Best", 2014),
    "Yoshihiro Andoh": ("Yoshihiro Andoh", 2008),
    "α波オルゴール": ("α波オルゴール", 2008),
    "ヨルシカ ピアノコレクション": ("ヨルシカ ピアノコレクション", 2020),
    "ロマンティック･サックス": ("ロマンティック サックス", 2010),
    "平沼有梨": ("平沼有梨", 2010),
    "朝まで深く眠れるスローピアノ": ("朝まで深く眠れるスローピアノ", 2018),
    "米津玄師ピアノコレクション": ("米津玄師ピアノコレクション", 2020),
    "自律神経にやさしいα波": ("自律神経にやさしいα波", 2010),
    "至極のα波 ジブリの名曲を小川のせせらぎと小鳥たちのさえずりの中で聴く": ("至極のα波 ジブリ", 2018),
    "relaxing piano 斉藤恒芳": ("Relaxing Piano", 2018),
    "Dream Dolphin": ("Dream Dolphin", 2003),
    "Rovo": ("Mon", 2007),
    "7and5": ("7and5", 2008),
    "Acker Bilk": ("Stranger on the Shore", 1961),
    "Acoustic Cafe": ("Mood Acoustic Cafe", 2003),
    "Acoustic Ocean": ("Acoustic Ocean", 2008),
    "Aaron Amida Ang": ("Tides", 2010),
    "Air Element": ("Air Element", 2008),
    "Alex Roe": ("Alex Roe", 2010),
    "Andrea Rongioletti": ("Andrea Rongioletti", 2010),
    "Aurio Corra": ("Aurio Corra", 2010),
    "Autumn's Grey Solace": ("Within the Depths of a Darkened Forest", 2002),
    "Back to Earth": ("Back to Earth", 1996),
    "Beautiful Fantasy II": ("Beautiful Fantasy II", 2008),
    "Bernadette Bevans": ("Bernadette Bevans", 2010),
    "Casey Crosby": ("Casey Crosby", 2010),
    "CHILDHOOD": ("CHILDHOOD", 2010),
    "David Agnew": ("Sailing", 1995),
    "Dean Evenson & Tom Barabas": ("Inner Garden", 2002),
    "Dulce Joya Leon": ("Dulce Joya Leon", 2010),
    "Elevation": ("Elevation", 2008),
    "Elk Camp Music": ("Elk Camp Music", 2010),
    "Emily Rowe": ("Emily Rowe", 2010),
    "Evenfall": ("Evenfall", 2008),
    "feel": ("feel", 2008),
    "Fly North": ("Fly North", 2010),
    "Hennie Bekker": ("Tranquility", 2003),
    "Ian Bullough": ("Ian Bullough", 2010),
    "Jonathan Harrington": ("Jonathan Harrington", 2010),
    "Kebin Keller": ("Kebin Keller", 2010),
    "Medwyn Goodall": ("Medicine Woman", 1992),
    "Minstrel Streams": ("Minstrel Streams", 2008),
    "Music 2 Hues": ("Music 2 Hues", 2010),
    "Sleep & Meditation Manifestation": ("Sleep & Meditation Manifestation", 2018),
    "Stuart Jones": ("Stuart Jones", 2010),
    "Terry Oldfield": ("Reiki Heart", 2003),
    "Thors": ("Thors", 2010),
    "Any_flac": ("Any", 2010),
    "Best of _The World Heritage": ("Best of The World Heritage", 2008),
    "Corcioll": ("Corcioll", 2010),
    "Dream Paradise vol.1+vol.2+vol.3": ("Dream Paradise", 2008),
    "earthgrooves vol.2": ("Earthgrooves Vol. 2", 1995),
    "emu2 most touching": ("emu2 most touching", 2008),
    "Ethan Averton;Jared Kraft": ("Ethan Averton & Jared Kraft", 2010),
    "flow_healing compilation": ("Flow Healing Compilation", 2010),
    "HEALING on THE MOON": ("Healing on the Moon", 2008),
    "Healing Waves": ("Healing Waves", 2003),
    "Neil H": ("Reflections of Light", 2008),
    "Oiegano": ("Oiegano", 2010),
    "Richard Evans": ("Walking through Sound", 2002),
    "Rick Sparks": ("Light from the Heart", 1991),
    "Silence": ("Silence", 2008),
    "study": ("Study", 2010),
    "The Great Northern": ("Trading Twilight for Daylight", 2007),
    "VA": ("Various Artists Sampler", 2010),
    "Zen_Mindfullness": ("Zen Mindfulness", 2018),
    "新しいフォルダー": ("新しいフォルダー", 2018),
    "Marblet (DAW Music Library Producers)": ("Marblet", 2018),
},

# ─── JPOP (110) ──────────────────────────────────────────────────────────
"jpop": {
    "B'z": ("Pleasure", 1994),
    "BUMP OF CHICKEN": ("ユグドラシル", 2004),
    "GLAY": ("REVIEW", 1997),
    "JAM Project": ("Skill", 2002),
    "Creepy Nuts": ("Case", 2017),
    "ポルノグラフィティ": ("ロマンチスト・エゴイスト", 2000),
    "L'Arc en Ciel": ("True", 1996),
    "L’Arc en Ciel": ("True", 1996),
    "Official髭男dism": ("Traveler", 2019),
    "SARD UNDERGROUND": ("少しづつ 少しづつ", 2019),
    "SEKAI NO OWARI 7thアルバム「Nautilus」[96kHz／24bit]": ("Nautilus", 2024),
    "TM NET": ("Self Control", 1987),
    "WANDS": ("Piece of My Soul", 1995),
    "ZARD Forever": ("ZARD Forever Best", 2009),
    "倍賞千恵子": ("さくら", 1968),
    "宇多田ヒカル 25周年記念アルバム「SCIENCE FICTION」[96kHz／24bit]": ("SCIENCE FICTION", 2024),
    "ポルノグラフィティ 25周年記念ベストアルバム「ポルノグラフィティ全書": ("ポルノグラフィティ全書", 2024),
    "森山直太朗 -素晴らしい世界": ("素晴らしい世界", 2003),
    "米津玄師 6thアルバム「LOST CORNER」[48kHz／24bit]": ("LOST CORNER", 2024),
    "Miyuki Nakajima": ("生きていてもいいですか", 1980),
    "美空ひばり": ("川の流れのように", 1989),
    "Aimer": ("Sun Dance", 2019),
    "Ado": ("狂言", 2022),
    "Garnet Crow": ("First Soundscope", 2003),
    "Faylan": ("Renovation", 2014),
    "Hakubi": ("Noah", 2019),
    "Ayahi Takagaki": ("Pop Step Mate", 2010),
    "Ceui": ("Ceui Best", 2014),
    "binaria": ("Voice II", 2014),
    "kokia": ("Songbird", 1999),
    "majiko": ("LOVE LETTER", 2018),
    "Mili": ("Hue", 2018),
    "Rurutia": ("Rurutia Best", 2007),
    "Suara": ("Soraneiro", 2014),
    "Uru": ("Monochrome", 2017),
    "Yoasobi": ("The Book", 2021),
    "ReoNa": ("Unknown", 2022),
    "あたらよ 1stアルバム「極夜において月は語らず」": ("極夜において月は語らず", 2022),
    "三月のパンタシア 10周年記念ベストアルバム「多彩透明なブルーだった」": ("多彩透明なブルーだった", 2024),
    "三月のパンタシア 5th Album「愛の不可思議」[48kHz／24bit]": ("愛の不可思議", 2024),
    "亜咲花 3rd Album「Who’s Me？」": ("Who's Me?", 2023),
    "ヘブンバーンズレッド 麻枝准×やなぎなぎ 2ndアルバム「Welcome to the Dying Season」": ("Welcome to the Dying Season", 2023),
    "こはならむ": ("こはならむ", 2020),
    "fhána": ("World Atlas", 2017),
    "eufonius": ("Frontier", 2007),
    "ORIGA": ("Inori", 2002),
    "May’n": ("Universe", 2010),
    "Reol": ("Reol", 2017),
    "Reol 4th Album「美辞学」[48kHz／24bit]": ("美辞学", 2024),
    "Ali project": ("Aristocracy", 1995),
    "Gackt": ("Crescent", 2003),
    "KAMIJO": ("Heart", 2018),
    "Janne Da Arc": ("Z-HARD", 2002),
    "Kagrra": ("Sai", 2007),
    "hizaki": ("Hizaki Grace Project", 2009),
    "Moi dix Mois": ("Dixanadu", 2007),
    "MUCC": ("Houyoku", 2004),
    "Yousei Teikoku 3.0": ("Hades: The Rise", 2014),
    "The Rose": ("Heal", 2022),
    "水樹奈々": ("Impact Exciter", 2010),
    "GRANRODEO": ("Karma", 2014),
    "林原めぐみ": ("Iravati", 1999),
    "茶太": ("Tea", 2010),
    "三月のパンタシア": ("Apple Records", 2018),
    "イヤホンズ": ("Sound Trip", 2017),
    "鬼頭明里": ("Stylepic", 2021),
    "西川貴教": ("Singularity", 2018),
    "mao": ("voice", 2014),
    "Kalafina": ("After Eden", 2011),
    "Yuki Kajiura": ("Fiction II", 2011),
    "fripSide": ("Decade", 2009),
    "MELL": ("Scope", 2008),
    "Lia": ("Lia*Cinema", 2010),
    "Tiara": ("Stand by U", 2011),
    "Zwei": ("Pride", 2009),
    "TWO-MIX 25th Anniversary ALL TIME": ("All Time", 2020),
    "GRANRODEO 20th BEST ALBUM「DOUBLE DECADES OF GR」": ("Double Decades of GR", 2024),
    "mao Best Album「voice」": ("voice", 2014),
    "水樹奈々 4thベストアルバム「THE MUSEUM Ⅳ」": ("THE MUSEUM IV", 2024),
    "林原めぐみ 30th Anniversary Best Album「VINTAGE DENIM」": ("Vintage Denim", 2021),
    "茶太 Works": ("Works", 2010),
    "茶太 Works Best Ⅱ": ("Works Best II", 2014),
    "Wakana": ("Wakana", 2019),
    "vip店長": ("vip店長 Selection", 2010),
    "DJ OKAWARI": ("Mirror", 2009),
    "ADAM at": ("Solitary Black Coffee", 2014),
    "ヘブンバーンズレッド 麻枝准×やなぎなぎ": ("Welcome to the Dying Season", 2023),
    "orange pekoe": ("Organic Plastic Music", 2002),
    "Pia-no-jaC": ("Tora x Wood", 2008),
    "SUEMITSU & THE SUEMITH": ("Snow Castle", 2008),
    "Sound Horizon": ("Roman", 2006),
    "Sound Horizon + Revo 2.0": ("Sound Horizon Best", 2012),
    "『ULTRAPANIC』Lanndo": ("Ultrapanic", 2022),
    "ずっと真夜中でいいのに。": ("沈香学", 2023),
    "神聖かまってちゃん": ("つまんね", 2010),
    "あたらよ": ("極夜において月は語らず", 2022),
    "Omoinotake": ("Pieces of the Future", 2024),
    "Blueberry & Yogurt": ("Blueberry & Yogurt", 2010),
    "Luz": ("Soundless Voice", 2017),
    "mol-74": ("Coloring", 2017),
    "ずっと真夜中でいいのに。 4thアルバム「形藻土」": ("形藻土", 2024),
    "神聖かまってちゃん 15周年記念ベストアルバム『聖なる交差点』": ("聖なる交差点", 2023),
    "NHK みんなのうたより ベストセレクション": ("みんなのうた ベスト", 2010),
    "CrosSing": ("CrosSing", 2020),
    "CLIMAX": ("Climax", 2010),
    "好きです かわさき♪": ("好きです かわさき", 2010),
    "いつも何度でも-いのちの名前": ("いつも何度でも", 2001),
    "永遠のSEED": ("永遠のSEED", 2010),
    "Healing": ("Healing", 2010),
    "HAWAIIAN6": ("HAWAIIAN6 Best", 2012),
    "Wolpis Carter": ("Wolpis Carter Best", 2017),
    "Yuria Miyazono": ("Yuria Miyazono", 2010),
    "wowaka": ("Unhappy Refrain", 2011),
},

# ─── Anime (76) ──────────────────────────────────────────────────────────
"anime": {
    "Code Geass Sound Collection": ("Code Geass Sound Episode", 2007),
    "Akame ga KILL! アカメが斬る！": ("Akame ga Kill! OST", 2014),
    "86 Eighty-six": ("86 Eighty-Six OST", 2021),
    "Fate Stay Night": ("Fate/stay night OST", 2006),
    "Hunter X Hunter": ("Hunter x Hunter OST", 2011),
    "ドラゴンクエスト ダイの大冒険": ("ダイの大冒険 OST", 2020),
    "鋼の錬金術師": ("Fullmetal Alchemist Brotherhood OST", 2009),
    "Gunslinger girl": ("Gunslinger Girl OST", 2003),
    "WOLF'S RAIN O.S.T": ("Wolf's Rain OST", 2003),
    "violet evergarden": ("Violet Evergarden OST", 2018),
    "TVアニメ「蒼穹のファフナー EXODUS」OP&EDテーマ「イグジスト／暗夜航路」／angela": ("イグジスト/暗夜航路", 2014),
    "TVアニメ「クロスアンジュ 天使と竜の輪舞」OP2テーマ「真実の黙示録」／高橋洋子": ("真実の黙示録", 2015),
    "TVアニメ「戦姫絶唱シンフォギアG」OPテーマ -「Vitalization」／水樹奈々": ("Vitalization", 2013),
    "「Exterminate」水樹奈々": ("Exterminate", 2014),
    "｢Los! Los! Los!｣／ターニャ・デグレチャフ": ("Los! Los! Los!", 2017),
    "TVアニメ「転生貴族、鑑定スキルで成り上がる」OPテーマ「ReCoda／ブルーデイズ」／TRUE [鑑定スキル盤]": ("ReCoda / ブルーデイズ", 2024),
    "Frieren Beyond Journey's End Original Soundtrack": ("Frieren OST", 2024),
    "Charlotte Original Soundtrack": ("Charlotte OST", 2015),
    "A Place Further than the Universe": ("Sora yori mo Tooi Basho OST", 2018),
    "サイレント・ウィッチ": ("Silent Witch OST", 2024),
    "メイドインアビス 烈日の黄金郷": ("Made in Abyss: The Golden City OST", 2022),
    "Grimgar of Fantasy and Ash": ("Grimgar OST", 2016),
    "TVアニメ メイドインアビス 烈日の黄金郷 オリジナルサウンドトラック": ("Made in Abyss: The Golden City OST", 2022),
    "TVアニメ『サイレント・ウィッチ 沈黙の魔女の隠しごと』Original Soundtrack": ("Silent Witch OST", 2024),
    "Heart of Magic Garden": ("Heart of Magic Garden", 2018),
    "DEAREST DROP": ("Dearest Drop", 2017),
    "Elfen Lied Original Soundtrack": ("Elfen Lied OST", 2004),
    "KOTOKO": ("Hane", 2009),
    "Helck": ("Helck OST", 2023),
    "Vitalization": ("Vitalization", 2013),
    "イグジスト/暗夜航路": ("イグジスト/暗夜航路", 2014),
    "真実の黙示録": ("真実の黙示録", 2015),
    "Exterminate": ("Exterminate", 2014),
    "Butter-Fly": ("Butter-Fly", 1999),
    "TVアニメ「魔法少女リリカルなのは」オリジナルサウンドトラック": ("Lyrical Nanoha OST", 2004),
    "片霧烈火": ("Wonder Heart", 2009),
    "機動天使エンジェリックレイヤー OP": ("Angelic Layer OP", 2001),
    "ISEKAI": ("Isekai", 2022),
    "『とある科学の超電磁砲』OP「only my railgun -version 2024- & -15th Anniversary version-」fripSide[96kHz／24bit]": ("only my railgun (2024)", 2024),
    "BEST OF INUYASHA 百花繚乱 -犬夜叉 テーマ全集-": ("Inuyasha Best Theme", 2003),
    "NARUTO－ナルト－Best Hit Collection": ("Naruto Best Hit Collection", 2007),
    "CLIMAX Anime Hits": ("Climax Anime Hits", 2008),
    "サイレントメビウス": ("Silent Möbius OST", 1991),
    "アルマギア -Project": ("Armagia Project", 2015),
    "黄金の輝き": ("黄金の輝き", 2010),
    "BEST OF INUYASHA 百花繚乱 -犬夜叉 テーマ全集": ("Inuyasha Best Theme", 2003),
    "Slam Dunk": ("Slam Dunk OST", 1993),
    "Shangri-La": ("Shangri-La OST", 2009),
    "ヒカルの碁 主題歌全集-ベスト オブ ヒカルの碁": ("Hikaru no Go Best", 2003),
    "サイレントメビウス THE BEST MUSIC COLLECTION FLAC": ("Silent Möbius Best", 2003),
    "双星の陰陽師": ("Sousei no Onmyoji OST", 2016),
    "animage 2 ~NEW ANIMATION SONGS~": ("Animage 2", 2008),
    "animage ~NEW ANIMATION SONGS~": ("Animage", 2008),
    "Anime": ("Anime Compilation", 2010),
    "Anime collection ACG": ("Anime Collection ACG", 2010),
    "Anime Piano": ("Anime Piano", 2010),
    "ave;new": ("ave;new feat. Saori Sakura", 2010),
    "BEST OF CHIHIROX": ("Best of Chihirox", 2010),
    "Anime Piano Works": ("Anime Piano Works", 2010),
    "Anime [Collection]": ("Anime Collection", 2010),
    "Never Let You Go": ("Never Let You Go", 2008),
    "魔法少女リリカルなのは": ("Lyrical Nanoha OST", 2004),
    "蒼穹のファフナー EXODUS": ("Fafner Exodus OST", 2014),
    "クロスアンジュ 天使と竜の輪舞": ("Cross Ange OST", 2015),
    "戦姫絶唱シンフォギアGX": ("Symphogear GX OST", 2015),
    "Chameleon Jazz with ANIME Flavor": ("Chameleon Jazz with Anime Flavor", 2008),
    "P.A.WORKS 20th Anniversary Theme Song Collection": ("P.A.Works 20th Theme", 2020),
    "Jyukai_BEST": ("Jyukai Best", 2010),
    "森口博子 アニソンカバーアルバム 第2弾「ANISON COVERS 2」[96kHz／24bit]": ("Anison Covers 2", 2022),
    "OST": ("Anime OST", 2010),
    "Project": ("Project", 2010),
    "THE": ("THE", 2010),
    "MARASY": ("marasy piano world", 2014),
    "高橋洋子": ("Refrain", 2003),
    "宮本駿一": ("Best Selection", 2010),
    "Studio Ghibli": ("Studio Ghibli Soundtracks", 2008),
    "Dragon Ball": ("Dragon Ball Z Hit Song Collection", 1989),
    "Pluto Original Soundtrack": ("Pluto OST", 2008),
    "Wakana": ("Wakana", 2019),
    "水樹奈々": ("Impact Exciter", 2010),
},

# ─── Game (147) ──────────────────────────────────────────────────────────
"game": {
    "Final Fantasy": ("Final Fantasy VII OST", 1997),
    "Dragon Quest": ("Dragon Quest III Symphonic Suite", 1988),
    "Falcom Sound Team jdk collection": ("Ys Origin OST", 2006),
    "Baten Kaitos": ("Baten Kaitos OST", 2003),
    "Fire Emblem": ("Fire Emblem: Three Houses OST", 2019),
    "Bravely Default OST": ("Bravely Default OST", 2012),
    "イースシリーズ": ("Ys VIII OST", 2017),
    "Saga": ("Romancing SaGa 3 OST", 1995),
    "Chrono": ("Chrono Trigger OST", 1995),
    "テイルズ": ("Tales of Symphonia OST", 2003),
    "ロマンシング サ・ガ": ("Romancing SaGa 2 OST", 1993),
    "GRANBLUE FANTASY": ("Granblue Fantasy OST", 2014),
    "Grand Knights History Original Soundtrack": ("Grand Knights History OST", 2011),
    "GRANDIA": ("Grandia OST", 1997),
    "ICO": ("ICO OST", 2001),
    "Kingdom Hearts": ("Kingdom Hearts OST", 2002),
    "Live A Live": ("Live A Live OST", 1994),
    "MOTHER 1+2 Original Soundtrack": ("MOTHER 1+2 OST", 2003),
    "OCTOPATH TRAVELER Original Soundtrack": ("Octopath Traveler OST", 2018),
    "Star Ocean": ("Star Ocean: The Second Story OST", 1998),
    "Tales of": ("Tales of Symphonia OST", 2003),
    "TalesWeaver Original Soundtrack": ("TalesWeaver OST", 2003),
    "Xenoblade Original Soundtrack": ("Xenoblade Chronicles OST", 2010),
    "Sekaiju no MeiQ": ("Etrian Odyssey OST", 2007),
    "Yoko Shimomura": ("Kingdom Hearts OST", 2002),
    "Yu-peng Chen": ("Genshin Impact OST", 2020),
    "英雄伝説I-IV ピアノ コレクション": ("Legend of Heroes Piano Collection", 2008),
    "Symphony Sounds Record": ("Symphony Sounds Record", 2010),
    "LORD of VERMILION Re-2 FAN KIT": ("Lord of Vermilion Re-2", 2010),
    "Yasunori Mitsuda Vocal Collection": ("Yasunori Mitsuda Vocal Collection", 2003),
    "ENDER LILIES": ("Ender Lilies OST", 2021),
    "Dies irae": ("Dies irae OST", 2007),
    "DemonsRoots": ("Demons Roots OST", 2022),
    "DRACULA": ("Castlevania: Symphony of the Night OST", 1997),
    "Castlevania": ("Castlevania: Symphony of the Night OST", 1997),
    "ENDER LILIES：Quietus of the Knights Original Soundtrack": ("Ender Lilies OST", 2021),
    "NieR": ("NieR Replicant OST", 2010),
    "Hentai Prison": ("Hentai Prison OST", 2022),
    "OMORI OST": ("OMORI OST", 2020),
    "Ori and the Blind Forest by Gareth Coker": ("Ori and the Blind Forest OST", 2015),
    "Undertale": ("Undertale OST", 2015),
    "腐り姫 劇伴集": ("Kusarihime OST", 2002),
    "メメントモリ": ("Memento Mori OST", 2022),
    "9-nine- Sound Premium Record": ("9-nine- Sound Premium Record", 2017),
    "AKABEiSOFT2": ("Akabei Soft 2 Best", 2010),
    "ALcot": ("ALcot Best", 2010),
    "AUGUST": ("August Best", 2010),
    "CROSS†CHANNEL ～In memory of all people～ SPECIAL SOUNDTRACK": ("Cross Channel Special OST", 2014),
    "Ever17_OST": ("Ever17 OST", 2002),
    "FAVORITE": ("Favorite Best", 2010),
    "A New Story": ("A New Story", 2010),
    "うたわれるもの 偽りの仮面＆二人の白皇 歌集": ("Utawarerumono Song Collection", 2016),
    "双星の陰陽師 Music Collection Album": ("Sousei no Onmyoji Music Collection", 2016),
    "細井聡司ワークス": ("Hosoi Soshi Works", 2010),
    "CUFFS SONGS BEST": ("Cuffs Songs Best", 2010),
    "SAGA PLANETS 四季ボーカルコレクション": ("Saga Planets Vocal Collection", 2010),
    "GIGA BEST ALBUM": ("Giga Best Album", 2010),
    "戯画ベストアルバム": ("Giga Best Album", 2010),
    "ファタモルガーナの館": ("The House in Fata Morgana OST", 2012),
    "Marica ワークスベストアルバム": ("Marica Works Best", 2010),
    "CROSS†CHANNEL": ("Cross Channel OST", 2003),
    "CUFFS SONGS": ("Cuffs Songs", 2010),
    "fengヴォーカルコレクション": ("Feng Vocal Collection", 2010),
    "Frontwing": ("Frontwing Best", 2010),
    "Katahane": ("Katahane OST", 2006),
    "Key": ("Key Sounds Label", 2008),
    "KiRite (SBPS-0008~9)": ("Kirite", 2003),
    "Laplacian": ("Laplacian Best", 2010),
    "Leaf": ("Leaf Vocal Collection", 2010),
    "Liar soft": ("Liar-soft Best", 2010),
    "Quartett!": ("Quartett! OST", 2004),
    "PHANTASM 榊原ゆい": ("Phantasm", 2008),
    "Pulltop Vocal Collection": ("Pulltop Vocal Collection", 2010),
    "purple software": ("Purple Software Best", 2010),
    "Sakura Musubi": ("Sakura Musubi OST", 2009),
    "SNOW ORIGINAL SOUNDTRACK": ("Snow OST", 2003),
    "Symphonic Rain": ("Symphonic Rain OST", 2004),
    "âge": ("âge Best", 2010),
    "キラ☆キラ": ("Kira Kira OST", 2007),
    "借金姉妹２ SoundTrack": ("Shakkin Sisters 2 OST", 2007),
    "最果てのイマ ORIGINAL SOUND TRACK": ("Saihate no Ima OST", 2005),
    "Marica ワークスベストアルバム「UNDER THE SUN」": ("Under the Sun", 2010),
    "GIGA BEST ALBUM -戯画ベストアルバム": ("Giga Best Album", 2010),
    "duca": ("duca Best", 2010),
    "yozuca＊": ("yozuca* Best", 2010),
    "I've Girls Compilation": ("I've Girls Compilation", 2002),
    "MANYO WORKS BEST!!": ("Manyo Works Best", 2010),
    "YUZUSOFT VOCAL COLLECTION 2006-2016": ("Yuzusoft Vocal Collection 2006-2016", 2016),
    "nine- Sound Premium Record": ("9-nine- Sound Premium Record", 2017),
    "Stein Gate": ("Steins;Gate OST", 2009),
    "Calling All Dawns": ("Calling All Dawns", 2009),
    "Donkey Kong Country Trilogy": ("Donkey Kong Country Trilogy OST", 1994),
    "Epic Game Music": ("Epic Game Music", 2014),
    "BALDR MASTERPIECE CHRONICLE Complete Vocal Collection": ("Baldr Masterpiece Chronicle", 2014),
    "Ar tonelico Hymmnos Musical Vocal Mini Album ~Cocona~": ("Ar tonelico Hymmnos Cocona", 2010),
    "Christopher Tin": ("Calling All Dawns", 2009),
    "flashygoodness": ("Tower of Heaven OST", 2010),
    "TPR": ("Pacific", 2014),
    "trabling": ("trabling", 2010),
    "zircon": ("Antigravity", 2007),
    "wac": ("Wac Best", 2010),
    "Laurence Manning": ("Laurence Manning", 2010),
    "dai": ("dai works", 2010),
    "松本文紀": ("Matsumoto Bunki Works", 2010),
    "細井聡司ワークス -Vocalists": ("Hosoi Soshi Works Vocalists", 2010),
    "トラベリング・オーガスト2015 ピアノアレンジ集 “Primary Notes”": ("Primary Notes", 2015),
    "メモオフ ピアノコレクション第２集": ("Memories Off Piano Collection 2", 2010),
    "KONAMI": ("Konami Music Collection", 2010),
    "オリジナル・サウンド・オブ・グラディウス＆沙羅曼蛇 バトル ミュージック コレクション": ("Gradius & Salamander Battle Music", 1986),
    "capcom 30周年": ("Capcom 30th Anniversary", 2013),
    "NAMCO SOUND TEAM": ("Namco Sound Team", 2010),
    "ダライアスバースト": ("Darius Burst OST", 2009),
    "田中勝己": ("Tanaka Katsumi Works", 2010),
    "細井聡司": ("Hosoi Soshi", 2010),
    "浜渦正志": ("Saga Frontier 2 OST", 1999),
    "志倉千代丸": ("Steins;Gate OST", 2009),
    "namco": ("Namco Sound Collection", 2010),
    "SQUARE ENIX": ("Square Enix Music Sampler", 2010),
    "Gust": ("Gust Music Collection", 2010),
    "Game Music Graffiti 任天堂大全集": ("Nintendo Music Graffiti", 2010),
    "Kid Icarus Uprising Original Soundtrack": ("Kid Icarus Uprising OST", 2012),
    "Rockman Theme Song Collection": ("Mega Man Theme Song Collection", 2008),
    "Metal Gear Solid Vocal Tracks": ("Metal Gear Solid Vocal Tracks", 2008),
    "Monster Hunter": ("Monster Hunter OST", 2004),
    "R4 -THE 20TH ANNIV. SOUNDS": ("R4 Ridge Racer Type 4 OST", 1998),
    "Pluto Original Soundtrack": ("Pluto OST", 2008),
    "NOSTALGIA Music Collection Op.1 & Op.2": ("Nostalgia Op.1 & Op.2", 2018),
    "RAIL SOUND THE BEST [N,A]": ("Rail Sound The Best", 2010),
    "オリジナル・サウンド・オブ・グラディウス＆沙羅曼蛇 バトル ミュージック コレクション [CD][FLAC+CUE+LOG+BK]": ("Gradius & Salamander Battle Music", 1986),
    "双星の陰陽師 Music Collection": ("Sousei no Onmyoji Music Collection", 2016),
    "Sakuna：Of Rice and Ruin original soundtrack[USA]／音楽：大嶋啓之": ("Sakuna OST", 2020),
    "Job for a Rockstar_rar": ("Job for a Rockstar", 2010),
    "FamilyJules": ("FamilyJules Game Music Covers", 2017),
    "春眠旅団": ("Shunmin Ryodan", 2014),
    "御伽櫻": ("Otogizakura", 2010),
    "KOTOKO's GAME SONG COMPLETE BOX 「The Bible」": ("The Bible Game Song", 2014),
    "Love Song from the Water": ("Love Song from the Water", 2010),
    "Neko Sound Collection": ("Neko Sound Collection", 2010),
    "Single": ("Single Collection", 2010),
    "Shade Music Laboratory": ("Shade Music Laboratory", 2010),
    "The Greatest Video Game Music": ("The Greatest Video Game Music", 2011),
    "CaveStory": ("Cave Story OST", 2004),
    "Dragon Ball": ("Dragon Ball Z Best Songs", 1989),
    "ZUN Touhou Official Music Collection": ("Touhou Official Music Collection", 2010),
    "Complete Collection": ("Complete Collection", 2010),
    "オリジナルサウンドトラック": ("Original Soundtrack", 2010),
    "いますぐ": ("Imasugu", 2010),
    "ZIZZ Studio music collection": ("ZIZZ Studio Music Collection", 2014),
    "eufonius": ("Frontier", 2007),
},

# ─── Indies (119) ────────────────────────────────────────────────────────
"indies": {
    "Imperial Circus Dead Decadence": ("Yumemiru Owari to Sayonara wo", 2014),
    "Asriel": ("Brilliance", 2009),
    "Dragon Guardian": ("Wagakuni Densetsu Ryusenki Vol.1", 2008),
    "Garnet Cathedral": ("Garnet Cathedral", 2010),
    "Dark PHOENiX": ("Phoenix Rising", 2014),
    "Unlucky Morpheus": ("Vampir", 2014),
    "Marchen Station": ("Marchen Station", 2010),
    "TEARS OF TRAGEDY": ("Tears of Tragedy", 2010),
    "黒夜葬「創作音源集 -骸-」": ("骸", 2014),
    "狂奏楽団": ("狂奏楽団", 2010),
    "CROSS VEIN": ("Reincarnation", 2014),
    "Aura Noctis": ("Aura Noctis", 2010),
    "Klaus -Nostalgias": ("Nostalgias", 2010),
    "Liz Triangle": ("Liz Triangle Best", 2014),
    "Tears Nocturn": ("Tears Nocturn", 2010),
    "Theodor Bastard": ("Sueta", 2009),
    "Zephyr Violin Duo": ("Zephyr", 2014),
    "Aleile": ("Aleile", 2010),
    "Frost Fragment": ("Frost Fragment", 2014),
    "B.rose&crown": ("B.Rose&Crown", 2014),
    "Octaviagrace": ("Octaviagrace", 2014),
    "-LostFairy": ("LostFairy", 2014),
    "Lost my Proust": ("Lost My Proust", 2014),
    "LostFairy": ("LostFairy", 2014),
    "Rejection": ("Rejection", 2014),
    "Release Hallucination": ("Release Hallucination", 2014),
    "Resonecia": ("Resonecia", 2014),
    "Roman so Words": ("Roman so Words", 2014),
    "Sana": ("Sana", 2010),
    "soLi (2021.12.08) My Garden …": ("My Garden", 2021),
    "Symholic": ("Symholic", 2014),
    "夢想茶館": ("Musou Sakan", 2014),
    "星猫音楽": ("Hoshineko Music", 2014),
    "AYUTRICA": ("Ayutrica Best", 2014),
    "Hagall×152Hz": ("Hagall x 152Hz", 2014),
    "AL Fantasia": ("AL Fantasia", 2010),
    "Barbarian On The Groove": ("Barbarian on the Groove", 2008),
    "CORONA": ("Corona", 2010),
    "AYUTRICA 1.0": ("Ayutrica 1.0", 2014),
    "Iyunaline Feat. 中原涼": ("Iyunaline feat. Ryo Nakahara", 2014),
    "Krik／Krak": ("Krik/Krak", 2014),
    "Laqshe": ("Laqshe", 2014),
    "Link to You？ (SHIKI) 1.0": ("Link to You", 2014),
    "MALIKLIYA": ("Malikliya", 2014),
    "Queen of Wand": ("Queen of Wand", 2014),
    "RoyReine": ("RoyReine", 2014),
    "SiMPLE EQUATiON": ("Simple Equation", 2014),
    "Souwer": ("Souwer", 2014),
    "stellatram": ("Stellatram", 2014),
    "SUNRISE FACTORY": ("Sunrise Factory", 2014),
    "Tinkerbell sound label": ("Tinkerbell Sound Label", 2014),
    "Tinkerbell Sound Label (CrossingYourself)": ("CrossingYourself", 2014),
    "Tynwald music": ("Tynwald Music", 2014),
    "Voltage of Imagination 2.1": ("Voltage of Imagination 2.1", 2014),
    "Yuria Miyazono": ("Yuria Miyazono", 2010),
    "Studio A'": ("Studio A'", 2010),
    "yucat": ("yucat Best", 2010),
    "arcane": ("arcane", 2010),
    "ARForest x nayuta": ("ARForest x nayuta", 2014),
    "Hoshineko Sounds 1.0": ("Hoshineko Sounds 1.0", 2014),
    "Arthur": ("Arthur", 2010),
    "Clinochlore": ("Clinochlore", 2010),
    "CORONA －Orgel Collection－": ("Corona Orgel Collection", 2014),
    "kano": ("kano", 2010),
    "kaoling": ("kaoling", 2010),
    "mamomo": ("mamomo", 2010),
    "morinoco_studio": ("morinoco_studio", 2014),
    "西本梨江 ピアノ, 村川千尋 バイオリン": ("Nishimoto Rie x Murakawa Chihiro", 2010),
    "オトノネ。音楽集-第一楽章- [CD][FLAC+CUE+LOG+BK]": ("オトノネ 第一楽章", 2014),
    "][Hi-Res]祈りの丘": ("祈りの丘 Hi-Res", 2014),
    "なぐもりずの音楽室": ("なぐもりずの音楽室", 2014),
    "AriableyeS": ("AriableyeS", 2014),
    "TAMUSIC": ("Tamusic Touhou Strings", 2010),
    "Diverse System 4.0": ("Diverse System 4.0", 2014),
    "love solfege": ("Love Solfege", 2010),
    "k-waves LAB": ("K-Waves Lab", 2014),
    "Rokugen Alice 3.0": ("Rokugen Alice 3.0", 2014),
    "5150": ("5150", 2014),
    "78": ("78", 2014),
    "Elixir Nocturne": ("Elixir Nocturne", 2014),
    "Sound of Swing": ("Sound of Swing", 2010),
    "WAVE": ("Wave", 2010),
    "M-Groove": ("M-Groove", 2010),
    "RESOUND WAV": ("Resound Wav", 2014),
    "Rigel Theatre": ("Rigel Theatre", 2010),
    "Melnik／ニャントロ人／初音ミク": ("Melnik feat. Hatsune Miku", 2014),
    "Wolpis Carter": ("Wolpis Carter Best", 2017),
    "wowaka": ("Unhappy Refrain", 2011),
    "bermei.inazawa": ("bermei.inazawa", 2010),
    "cy：cle": ("cy:cle", 2010),
    "Electro.muster": ("Electro.muster", 2014),
    "ffffff Records": ("ffffff Records", 2014),
    "el ma Riu": ("el ma Riu", 2010),
    "Mag2 Software": ("Mag2 Software", 2014),
    "ZIZZ Studio music collection": ("ZIZZ Studio Music Collection", 2014),
    "Tuatha De Danann": ("Tuatha de Danann", 2010),
    "forest": ("forest", 2010),
    "Fiorista Felice": ("Fiorista Felice", 2010),
    "Ether&エルム凪": ("Ether & Erumu Nagi", 2014),
    "MiddleIsland": ("MiddleIsland", 2014),
    "Noah": ("Noah", 2010),
    "notte": ("notte", 2010),
    "onoken": ("onoken", 2010),
    "Barbarian On The Groove 3.0": ("Barbarian on the Groove 3.0", 2014),
    "dama": ("dama", 2010),
    "Elliot Hsu": ("Elliot Hsu", 2010),
    "Elymusia": ("Elymusia", 2010),
    "himajin-sound (たけやん)": ("himajin-sound", 2014),
    "maracy": ("maracy", 2010),
    "mozell kuhu": ("mozell kuhu", 2014),
    "nayuta": ("nayuta", 2010),
    "pub house himari": ("Pub House Himari", 2014),
    "sea-no": ("sea-no", 2010),
    "Street": ("Street", 2010),
    "timeless melody 茶太": ("Timeless Melody Cha-ta", 2010),
    "toyKasket": ("toyKasket", 2014),
    "Unknown": ("Unknown", 2010),
    "埼玉最終兵器 & Aether": ("埼玉最終兵器 & Aether", 2014),
    "柊南(ひいな)＆clan(くらん)": ("柊南＆clan", 2014),
    "新しいフォルダー": ("Compilation Folder", 2018),
},

}
