import fs from "node:fs/promises";
import path from "node:path";
const root = "/home/ubuntu/hitori-source/data/hitori";
const id = "manual-kanagawa-bayside-sauna-nokendai-20260813";
const [prefRaw, curatedRaw, summaryRaw] = await Promise.all([fs.readFile(path.join(root, "pref/14.json"), "utf8"), fs.readFile(path.join(root, "curated.json"), "utf8"), fs.readFile(path.join(root, "summary.json"), "utf8")]);
const pref = JSON.parse(prefRaw), curated = JSON.parse(curatedRaw), summary = JSON.parse(summaryRaw);
const rows = pref.items.filter(item => item[0] === id);
if (rows.length !== 1 || rows[0].length !== 23) throw new Error("静的施設配列が一意の23列ではありません。");
const row = rows[0];
if (row[1] !== "BAYSIDE SAUNA" || row[2] !== 35.36177724194611 || row[3] !== 139.62943656644933 || row[4] !== "bath") throw new Error("名称・座標・業態が想定と異なります。");
const entry = curated[id];
if (!entry || entry.checked !== "2026-08-13" || entry.facts?.length !== 7 || !entry.facts.every(f => f.official && !f.conflict)) throw new Error("確認済み根拠が想定と異なります。");
const price = entry.facts.find(f => f.k === "price")?.v || "", reservation = entry.facts.find(f => f.k === "reservation")?.v || "";
if (!/3,000円/.test(price) || !/150分前/.test(reservation)) throw new Error("料金・予約締切の公式根拠が不足しています。");
if (summary.total !== 40579 || summary.checked_count !== 761) throw new Error(`集計値が想定と異なります: ${summary.total}/${summary.checked_count}`);
console.log(JSON.stringify({ status: "ok", id, total: summary.total, checkedCount: summary.checked_count, factCount: entry.facts.length, row }, null, 2));
